import {A2000_BASIS,A2000_INPUTS,calculateA2000} from './a2000-basis.js';
import {A400_BASIS} from './a400-basis.js';
export function mountA2000Basis(model){
 if(model.scope==='future')return;
 const card=document.createElement('details');card.className='method-note a400-basis-card';card.id='a2000-basis';
 card.innerHTML='<summary>A-2000 reclaimed water · design basis</summary><p class="small-note">FEED-PFD-2000 · V5.1 page 16. Single-pass RO with two duty trains and one standby. Draft arrangement; sizing and water quality require qualification.</p><div class="a2000-screening"><label>Feed screening flow (m³/h)<input id="ro-feed" type="number" min="1" max="300" step="1" value="100"></label><label>RO recovery scenario<select id="ro-recovery"><option value="0.6">60% · PFD base</option><option value="0.7">70% · scaling study required</option><option value="0.75">75% · scaling study required</option></select></label><label>T-2001 residence time<select id="ro-hours"><option value="8">8 hours · modeled base</option><option value="10">10 hours · comparison</option><option value="12">12 hours · comparison</option></select></label></div><p class="small-note">Scenario calculations do not resize the 3D equipment. Media recovery 98% is an allowance; UF recovery 92.5% is within the draft 90–95% range. Values are not measured production.</p><div id="ro-calculation" aria-live="polite"></div>';
 const result=card.querySelector('#ro-calculation');function refresh(){result.replaceChildren();try{const i={...A2000_INPUTS,feedM3H:Number(card.querySelector('#ro-feed').value),roRecovery:Number(card.querySelector('#ro-recovery').value),equalizationHours:Number(card.querySelector('#ro-hours').value)},c=calculateA2000(i),n=v=>v.toFixed(2),rows=[['Gross feed into pretreatment',n(i.feedM3H)+' m³/h'],['Media backwash allowance',n(c.mediaWasteM3H)+' m³/h'],['UF reject / backwash',n(c.ufWasteM3H)+' m³/h'],['RO feed',n(c.roFeedM3H)+' m³/h'],['RO permeate',n(c.permeateM3H)+' m³/h'],['RO concentrate',n(c.brineM3H)+' m³/h'],['Single-through recovery',n(c.overallRecovery*100)+'%'],['Ideal retained-solute concentration factor',n(c.concentrationFactor)+' × (screen only)'],['T-2001 working / nominal storage',n(c.feedTankWorkingM3)+' / '+n(c.feedTankNominalM3)+' m³'],['T-2002 / T-2003 nominal buffers',n(c.productTankNominalM3)+' / '+n(c.brineTankNominalM3)+' m³'],['Two duty RO trains · capacity allowance',n(c.dutyCapacityM3H)+' m³/h permeate'],['Duty membrane flux',n(c.trainFluxLmh)+' L/m²·h'],['A-400 duty alone',n(A400_BASIS.calculated.permeateM3H)+' m³/h'],['Supplemental water for A-400 alone',n(Math.max(0,A400_BASIS.calculated.permeateM3H-c.permeateM3H))+' m³/h']];const table=document.createElement('table');table.innerHTML='<thead><tr><th>Screening result</th><th>Value</th></tr></thead>';for(const row of rows){const tr=document.createElement('tr');for(const v of row){const td=document.createElement('td');td.textContent=v;tr.append(td);}table.append(tr);}result.append(table);const p=document.createElement('p');p.className='small-note';p.textContent=(c.capacityFits?'Within the illustrative duty-train flow allowance. ':'Exceeds the illustrative duty-train flow allowance. ')+(i.roRecovery>.6?'Higher recovery is conditional on vendor scaling analysis and an accepted brine outlet. ':'')+'Plant-wide net recovery is unresolved: return flows, other process users, flushing and outages must be included.';result.append(p);model.reclaimedWater.screeningScenario={inputs:i,calculated:c,changesGeometry:false};}catch(e){result.textContent=e.message;}}
 for(const e of card.querySelectorAll('input,select'))e.addEventListener('change',refresh);refresh();
 function notes(title,items){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=title;d.append(s);for(const text of items){const p=document.createElement('p');p.className='small-note';p.textContent=text;d.append(p);}card.append(d);}
 notes('Draft PFD product-water targets',A2000_BASIS.qualityTargets.map(([name,value])=>name+': '+value));
 notes('Design reasoning and open qualifications',A2000_BASIS.holds);
 const refs=document.createElement('details'),summary=document.createElement('summary');summary.textContent='PFD and engineering references';refs.append(summary);for(const source of A2000_BASIS.sources){const p=document.createElement('p'),a=document.createElement('a');a.textContent=source.title;a.href=source.url;a.target='_blank';a.rel='noopener';p.append(a);refs.append(p);}card.append(refs);document.getElementById('process-overview').append(card);
}
