import {A3000_BASIS,A3000_INPUTS,calculateA3000} from './a3000-basis.js';
export function mountA3000Basis(model){if(model.scope==='future')return;const card=document.createElement('details');card.id='a3000-basis';card.className='method-note a400-basis-card';card.innerHTML='<summary>A-3000 assembled build · exhaust groups and PFD review</summary><p class="small-note">FEED-PFD-3000 · V5.1 page 17. Proposed wet acid train. Furnace, peroxide, powder and relief services remain separate. No operating scrubber bypass.</p>';
 const flow=document.createElement('p');flow.className='small-note';flow.textContent='HD-3100 → V-3110 bulk-liquid separation → T-3140 acid absorption → proposed ME-3150 fine-mist polishing → FN-3160 → ST-3170. P-3181A/B recirculate liquor; closed condensate and blowdown transfers have separate acceptance controls.';card.append(flow);
 function table(parent,headers,rows){const t=document.createElement('table');t.className='a3000-table';const h=document.createElement('thead'),hr=document.createElement('tr');for(const x of headers){const th=document.createElement('th');th.textContent=x;hr.append(th);}h.append(hr);t.append(h);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const x of row){const td=document.createElement('td');td.textContent=String(x);tr.append(td);}body.append(tr);}t.append(body);parent.append(t);}
 function detail(title){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=title;d.append(s);card.append(d);return d;}
 const mechanical=detail('Modeled assembly review');
 const note=document.createElement('p');note.className='small-note';note.textContent='Inspect assembled equipment, nozzles, pump interfaces and supports. Open connection and maintenance findings remain in the review register.';mechanical.append(note);const history=document.createElement('details'),historyTitle=document.createElement('summary');historyTitle.textContent='Revision history · assembly corrections';history.append(historyTitle);const historyNote=document.createElement('p');historyNote.textContent='FN-3160 now has an enclosed casing, real inlet and tangential outlet, coaxial drive and guarded coupling. The V-3110 inlet now approaches its nozzle along the nozzle axis through a routed elbow. Pump adapters match their adjoining pipes. Radial nozzle ends follow the vessel curvature, with matching bore openings. Directly connected pipework remains visible across equipment ownership groups. Every inspect button resets explosion to zero, turns sectioning off and reveals the relevant equipment and its supports.';history.append(historyNote);mechanical.append(history);
 function inspect(parent,ids,label){const button=document.createElement('button');button.type='button';button.textContent='Inspect '+label;button.onclick=()=>document.dispatchEvent(new CustomEvent('inspect-exhaust-group',{detail:{ids,label}}));parent.append(button);}
 inspect(mechanical,[600,601,605,606,609],'fan, demister and stack');inspect(mechanical,[602,603,604,607,608,610,611,612,615,616],'liquid handling');
 inspect(mechanical,[615,616],'makeup receiver · intentional air gap');const gap=document.createElement('p');gap.className='small-note';gap.textContent='TK-3184: the water outlet is intentionally separated from the receiving funnel by 520 mm in this proposed model. Do not bridge this gap. Flood level, splash capture, overflow capacity, support loads and BC plumbing acceptance remain to be verified.';mechanical.append(gap);
 const link=document.createElement('a');link.href='./a3000-review.html';link.textContent='Open assembled projections and complete endpoint register';link.target='_blank';link.rel='noopener';mechanical.append(link);
 const groups=detail('Separate exhaust groups · chemistry, combustion, pressure and mechanism');
 for(const g of model.exhaustGroups.groups){const d=document.createElement('details'),summary=document.createElement('summary');summary.textContent=g.name;d.append(summary);table(d,['Basis','Proposed disposition'],[['Sources',g.sources.join(', ')],['Chemistry',g.chemistry],['Combustion',g.combustion],['Pressure',g.pressure],['Mechanism',g.mechanism],['Qualification',g.status]]);inspect(d,g.equipment,g.name);groups.append(d);}
 const groupingNote=document.createElement('p');groupingNote.className='small-note';groupingNote.textContent='BL-VENT801 is dry inventory / mixer breathing; BL-REL801 is emergency relief. Normal off-gas, reactive feeder exhaust and relief have separate destinations. The satellite floor reservation is a separate 23.0 × 2.9 m rectangle (66.7 m²), not part of the 10 × 10 m wet-train footprint. Package dimensions, maintenance withdrawal, source pressure and treatment performance remain unqualified.';groups.append(groupingNote);
 const endpoints=detail('Connection reconciliation · each endpoint has a disposition');const cr=model.ventGas.connectionReview;table(endpoints,['Disposition','Entries'],Object.entries(cr.summary));table(endpoints,['Mechanical interface','Disposition'],[...model.ventGas.interfaces,...model.exhaustGroups.interfaces].map(i=>[i.equipment+' · '+i.name,i.status+(i.closure?' / '+i.closure:'')+' · '+(i.note||'Mating geometry provided')]));const cn=document.createElement('p');cn.className='small-note';cn.textContent='Connected means a model interface is joined; it does not imply pressure integrity or operating approval. The downloadable configuration and assembled review include every route endpoint and nozzle, including unresolved items.';endpoints.append(cn);
 const review=detail('12 PFD findings · corrections and reasons');for(const [priority,topic,found,recommend]of A3000_BASIS.review){const d=document.createElement('details'),s=document.createElement('summary');s.textContent=priority+' · '+topic;const p=document.createElement('p');p.className='small-note';p.textContent=found+' '+recommend;d.append(s,p);review.append(d);}
 const sources=detail('Source compatibility and connection register');table(sources,['Source','Disposition / reason'],model.ventGas.sourceReview.map(r=>[r.tag,r.status+' — '+r.reason]));
 const calc=detail('Screening calculator · example inputs, not PFD gas duty');calc.innerHTML+='<p class="small-note">All numbers below are adjustable engineering examples. Nm³/h means dry gas at 0°C and 101.325 kPa. Temperature, absolute pressure and water-vapour fraction convert it to actual wet flow. Changing inputs does not resize the model.</p><div class="a2000-screening"><label>Dry gas (Nm³/h)<input data-gas="normalM3H" type="number" min="1" step="100" value="5000"></label><label>Temperature (°C)<input data-gas="temperatureC" type="number" min="0" max="100" value="40"></label><label>Captured HCl (kg/h)<input data-gas="hclKgH" type="number" min="0" step="0.1" value="5"></label><label>Captured H₂SO₄ equivalent (kg/h)<input data-gas="h2so4KgH" type="number" min="0" step="0.1" value="2"></label></div><div class="a3000-calculation" aria-live="polite"></div>';
 const result=calc.querySelector('.a3000-calculation');function refresh(){result.replaceChildren();try{const i={...A3000_INPUTS};for(const el of calc.querySelectorAll('[data-gas]'))i[el.dataset.gas]=Number(el.value);const c=calculateA3000(i),n=x=>x.toFixed(2);table(result,['Example result','Value'],[['Actual wet flow',n(c.actualWetM3H)+' m³/h'],['Diameter at assumed 1.5 m/s',n(c.screenDiameterM)+' m'],['Modeled tower diameter',n(c.modeledDiameterM)+' m · '+(c.diameterFits?'screening allowance only':'example exceeds model')],['Liquor at assumed 3 L/m³ actual gas',n(c.liquorM3H)+' m³/h'],['Fan shaft power at assumed 3.5 kPa / 65%',n(c.fanShaftKW)+' kW'],['NaOH pure / 25 wt% solution',n(c.naohPureKgH)+' / '+n(c.naohSolutionKgH)+' kg/h'],['Stoichiometric sodium-salt generation',n(c.saltKgH)+' kg/h'],['Blowdown and removal efficiency','Unresolved · composition and testing required']]);const p=document.createElement('p');p.className='small-note';p.textContent='Assumptions: 99 kPa absolute; 5 mol% water vapour; 15% NaOH excess. Neutralization uses HCl + NaOH → NaCl + H₂O and H₂SO₄ + 2NaOH → Na₂SO₄ + 2H₂O. Other acids, CO₂ demand, mist drain split, evaporation, makeup salts, flooding, packing height and fan motor margin are excluded. No removal guarantee or approved operating setpoint is inferred.';result.append(p);model.ventGas.screeningScenario={inputs:i,calculated:c,changesGeometry:false};}catch(e){result.textContent=e.message;}}
 for(const e of calc.querySelectorAll('input'))e.addEventListener('change',refresh);refresh();
 const capture=detail('Local containment capacity · open design action');table(capture,['Capture zone','Inventory / local capacity / shortfall (m³)'],model.ventGas.bunds.map(b=>[b.tag,[b.screenInventoryM3,b.screenNetM3,b.screenShortfallM3].map(v=>v.toFixed(2)).join(' / ')]));const captureNote=document.createElement('p');captureNote.className='small-note';captureNote.textContent='The compact liquor and condensate curbs are capture only where a shortfall is shown. Enlarge containment or add a separately verified off-line retention cell before construction. Additional drains are deliberately not shown as approved disposal paths.';capture.append(captureNote);const holds=detail('Layout and commissioning limits');for(const text of ['The 10 m × 10 m area is a floor-planning allowance. Tall scrubber internals require vendor platforms, safe access and a lifting plan; the vertical removal space is reserved. Stack height and sampling access remain subject to dispersion and permit design.','T-3180 return crest is above the proposed operating liquid level. Seal depth, maximum pressure difference, minimum inventory, anti-siphon design and low-point drains require hydraulic verification. Fan/stack condensate remains separate closed collection.','The NaOH diaphragm-metering concept requires vendor calibration, backpressure control and pressure relief. Pumps, fan curves, NPSH, dry-running protection and spare strategy require selection.','Chemical capture curbs are proposed geometry. Determine net capacity from credible inventories, displacement, wash water and firewater; verify liner, joints, drain isolation and support penetrations. Pipe-support and clearance screening findings remain visible. Yellow ES-3000 uses independent emergency water; exposure-based location, flow, temperature and freeze protection require qualification.','No live controls, emissions measurements, approved setpoints or construction approval are supplied by this model. Source generation is permitted in the inspection only when illustrative conditions are satisfied.']){const p=document.createElement('p');p.className='small-note';p.textContent=text;holds.append(p);}
 const refs=detail('Engineering sources and original PFD');for(const [title,url]of A3000_BASIS.sources){const p=document.createElement('p'),a=document.createElement('a');a.href=url;a.textContent=title;a.target='_blank';a.rel='noopener';p.append(a);refs.append(p);}document.getElementById('process-overview').append(card);
}
