const pumps=s=>['XV-3181'+s+'-SUC','XV-3181'+s+'-DIS'];
const common=['flow','pressure','level','drive','design','capacity','scrubchem','draft','mist'];
export const A3000_UNIT={title:'A-3000 wet vent treatment',requires:common,note:'Illustrative inspection only. Start liquid circulation and prove draft before authorizing emissions. Shutdown inhibits new source feed/heat while available treatment handles residual gas. The model contains no operating bypass, relief credit or combustible-gas treatment guarantee.',states:{
 start:{label:'Establish circulation and draft · sources not released',open:pumps('A'),seed:'Compatible wet vent inlet',extra:['T-3180 liquid inventory'],drives:['P-3181A','FN-3160']},
 run:{label:'Qualified wet treatment · pump A duty',open:[...pumps('A'),'XV-3182-DOSE'],seed:'Compatible wet vent inlet',extra:['T-3180 liquid inventory','T-3182 NaOH inventory'],drives:['P-3181A','FN-3160','P-3182'],sourcePermission:true},
 standby:{label:'Pump B duty · pump A isolated',open:[...pumps('B'),'XV-3182-DOSE'],seed:'Compatible wet vent inlet',extra:['T-3180 liquid inventory','T-3182 NaOH inventory'],drives:['P-3181B','FN-3160','P-3182'],sourcePermission:true},
 shutdown:{label:'Stop source generation · continue available treatment',open:pumps('A'),seed:'Compatible wet vent inlet',extra:['T-3180 liquid inventory'],drives:['P-3181A','FN-3160'],sourcePermission:false},
 makeup:{label:'Controlled makeup · physical air gap upstream',open:['XV-3184-MAKEUP'],seed:'TK-3184 makeup inventory',drives:['P-3184'],requires:['level','drive','capacity','design']},
 wash:{label:'Offline fine-mist wash · sources stopped',open:['XV-3184-MAKEUP','XV-3150-WASH'],seed:'TK-3184 makeup inventory',drives:['P-3184'],requires:['level','drive','capacity','design']},
 blowdown:{label:'Qualified separate wastewater transfers',open:['XV-3111-WW','XV-3183-WW'],seed:'TK-3111 acidic inventory',extra:['T-3180 blowdown inventory'],drives:['P-3111','P-3183'],requires:['capacity','endpoint','level','drive','design']}
}};
export function ventGasConfiguration(model,state,condition,labels){const st=A3000_UNIT.states[state];if(!st)throw Error('Unknown vent treatment state');const valves=Object.fromEntries(model.edges.filter(e=>e.barrierTag).map(e=>[e.barrierTag,'closed']));const enabled=condition==='ready'||!(st.requires||common).includes(condition);let seeds=[st.seed,...st.extra||[]],drives=st.drives||[],open=st.open,protectiveNote='';
 if(!enabled){seeds=[];drives=[];open=[];if(['start','run','standby','shutdown'].includes(state)){protectiveNote='New source feed/heat inhibited. Available treatment remains demanded for residual emissions; no automatic blanket closure of vessel vents. Approved failure and emergency response required.';if(!['draft','drive'].includes(condition)){seeds.push('Compatible wet vent inlet');drives.push('FN-3160');}if(!['flow','level','drive'].includes(condition)){seeds.push('T-3180 liquid inventory');drives.push(state==='standby'?'P-3181B':'P-3181A');open=pumps(state==='standby'?'B':'A');}}}
 for(const tag of open)valves[tag]='open';return {unit:'ventgas',state,condition,enabled,protectionActive:!enabled&&seeds.length>0,valves,seeds,drives,illustrative:true,sourcePermission:enabled&&!!st.sourcePermission,reasons:enabled?[]:[labels[condition]||condition],protectiveNote};
}
// Keep gas, liquor, makeup and segregated waste traces distinct at the contact equipment.
export function traceVentGas(model,cfg,graph){const queue=[];for(const label of cfg.seeds){const r=model.routes.find(r=>r.label===label);if(!r)throw Error('Missing vent route '+label);queue.push({i:r.edgeIndices[0],phase:r.circuit});}const visited=new Set(),seen=new Set(),blocked=new Set();for(let q=0;q<queue.length;q++){const {i,phase}=queue[q],key=i+'|'+phase;if(seen.has(key))continue;seen.add(key);const e=model.edges[i];if(e.reactor<600||e.reactor>616||e.circuit&&e.circuit!==phase)continue;if(e.barrierTag&&cfg.valves[e.barrierTag]==='closed'){blocked.add(e.barrierTag);continue;}visited.add(i);for(const j of graph[i])queue.push({i:j,phase});}const partIds=new Set([...visited].map(i=>model.edges[i].part));for(const r of model.routes)if(r.edgeIndices.length&&r.edgeIndices.every(i=>visited.has(i)))for(const id of r.partIds)partIds.add(id);return {partIds,edges:[...visited].map(i=>model.edges[i]),edgeIndices:visited,blocked:[...blocked],boundaries:[],configuration:cfg};}
