import {A4000_BASIS,A4000_IDS,A4000_HOLDS,A4000_SCENARIOS,A4000_SOURCES} from './a4000-basis.js';
import {calculateAir,airScenario} from './a4000-logic.js';
export function mountA4000Basis(model){
 if(model.scope==='future'||!model.compressedAir)return;
 const el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;},card=el('details');card.id='a4000-basis';card.className='method-note a400-basis-card';card.append(el('summary','A-4000 · Compressed air and protected instrument supply'));
 card.append(el('p','Two compressor branches → wet receiver → protected desiccant dryer → outlet filters → quality release → dry reserve → instrument / service branches. Proposed 8 × 10 m arrangement. Capacities and air-quality targets are unqualified.'));
 const inspect=el('button','Inspect A-4000 assembled');inspect.type='button';inspect.onclick=()=>document.dispatchEvent(new CustomEvent('inspect-air-system',{detail:{ids:A4000_IDS,scenario:scenario.value}}));card.append(inspect);
 const label=el('label','Operating / failure inspection'),scenario=el('select');label.htmlFor=scenario.id='air-scenario';for(const[value,text]of A4000_SCENARIOS){const o=el('option',text);o.value=value;scenario.append(o);}card.append(label,scenario);
 const stateBox=el('div');stateBox.setAttribute('aria-live','polite');card.append(stateBox);
 const table=(parent,heads,rows)=>{const wrap=el('div');wrap.className='air-table-scroll';const t=el('table');t.className='a3000-table';const head=el('thead'),tr=el('tr');heads.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');rows.forEach(row=>{const r=el('tr');row.forEach(value=>r.append(el('td',String(value))));body.append(r);});t.append(body);wrap.append(t);parent.append(wrap);};
 function state(){const r=airScenario(scenario.value);stateBox.replaceChildren();table(stateBox,['Function','Illustrative response'],[['Compression',r.compressorA?'A running; B '+(r.compressorB?'running':'stopped / standby'):r.compressorB?'B running':'Stopped'],['Quality release',r.qualityRelease?'Eligible only after verified quality':'Closed'],['Instrument air',r.instrumentAir?(r.reserveOnly?'Previously qualified reserve only; endurance HOLD':'Supply path enabled; capacity HOLD'):'No supply credited'],['Service air',r.serviceAir?'Branch enabled; outlet capped':'Priority isolation closed'],['Process-contact air','Isolated and positively blinded']]);stateBox.append(el('p',r.reason),el('p',r.qualification));}
 scenario.onchange=()=>{state();document.dispatchEvent(new CustomEvent('air-scenario-change',{detail:{scenario:scenario.value}}));};state();
 const detail=title=>{const d=el('details');d.append(el('summary',title));card.append(d);return d;};
 const schedule=detail('Consumer schedule · four connections and area surveys');table(schedule,['Area / consumer','Connection / duty'],model.compressedAir.consumers.map(c=>[c.area+' · '+c.equipment,c.tag+' — '+c.status]));schedule.append(el('p','Flow, simultaneous peak, minimum pressure, air quality and reserve duration remain blank until supplier data is supplied. A-600 blower air and process inerting gases are excluded.'));
 const calc=detail('Capacity and reserve calculator · documented inputs'),inputs={};calc.append(el('p',A4000_BASIS.flowsReference+'. Enter explicit zero where an allowance is intentionally zero. Inputs do not resize geometry.'));
 const fields=[['normalNm3H','Normal simultaneous users (Nm³/h)'],['peakNm3H','Peak simultaneous users (Nm³/h)'],['purgeNm3H','Dryer purge (Nm³/h)'],['leakNm3H','Leakage allowance (Nm³/h)'],['growthNm3H','Planned growth (Nm³/h)'],['oneCompressorNm3H','One compressor delivered capacity (Nm³/h)'],['receiverM3','Qualified dry receiver usable vessel volume (m³)'],['highBarg','Reserve starting pressure (bar gauge)'],['lowBarg','Minimum reserve pressure incl. losses (bar gauge)'],['temperatureC','Stored air temperature (°C)'],['criticalNm3H','Critical demand during outage (Nm³/h)'],['requiredMinutes','Required reserve (minutes)']];
 const grid=el('div');grid.className='a2000-screening';for(const[key,text]of fields){const lab=el('label',text),input=el('input');input.type='number';input.step='any';if(key!=='temperatureC')input.min='0';input.placeholder='TBD';input.setAttribute('aria-label',text);lab.append(input);grid.append(lab);inputs[key]=input;}calc.append(grid);const result=el('p','HOLD — documented demand and receiver inputs are needed.');result.setAttribute('role','status');calc.append(result);
 for(const input of Object.values(inputs))input.oninput=()=>{const entered=Object.fromEntries(Object.entries(inputs).map(([k,v])=>[k,v.value])),r=calculateAir(entered);result.textContent=r.totalNm3H===undefined?r.status+' — '+r.reason:`SCREEN ONLY — normal ${r.totalNm3H.toFixed(2)} / peak ${r.peakNm3H.toFixed(2)} Nm³/h. One compressor: normal ${r.oneUnitNormalFits?'fits':'shortfall'}, peak ${r.oneUnitPeakFits?'fits':'shortfall'}. Reserve ${r.reserveMinutes.toFixed(2)} min (${r.reserveFits?'meets':'below'} entered duration). ${r.reason}`;model.compressedAir.screeningInputs=entered;model.compressedAir.screeningResult=r;};
 const endpoint=detail('Connections and PFD reconciliation');table(endpoint,['Interface','Disposition'],model.compressedAir.interfaces.map(i=>[i.tag,i.disposition+' · '+(i.reason||'Mating model geometry')]));endpoint.append(el('p','Model line numbers identify geometry. PFD streams 4001–4013 remain unassigned until their exact endpoints are verified against the source drawing. F-4002 / F-4003 duties and the proposed protective prefilter require vendor reconciliation.'));
 const holds=detail('Engineering decisions and release requirements');for(const[title,reason]of A4000_HOLDS){const p=el('p');p.append(el('strong',title+' — '),document.createTextNode(reason));holds.append(p);}
 const refs=detail('BC requirements and technical references');for(const[title,url]of A4000_SOURCES){const p=el('p'),a=el('a',title);a.href=url;a.target='_blank';a.rel='noopener';p.append(a);refs.append(p);}
 const dl=el('button','Download A-4000 design review');dl.type='button';dl.onclick=()=>{const blob=new Blob([JSON.stringify(model.compressedAir,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='A4000-design-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};card.append(dl);document.getElementById('process-overview').append(card);
}
