// Codes, regulations and practices that bear on the A-5400 thermal-oil package, tracked by ID (V317). The equipment descriptions quote the IDs and the
// A-5400 assembly & design review (dist/a5400-review.html) holds the full register with the model evidence. Nothing here is an approval: every row stays
// 'to confirm' until a named reviewer records it, and the BC Fire Code text was read in its 2018 edition (confirm the edition in force and the authority
// having jurisdiction). Article numbers marked unconfirmed were read from the section text without a reliable article heading.
export const A5400_CODES_BASIS={revision:'V317',date:'2026-10-08',edition:'BC Fire Code 2018 (Division B, Part 4) as published at free.bcpublications.ca; confirm the edition in force.',
 note:'Researched for the pad position (QFL 2026-10-08). The BC codes found set no minimum distance between a fired heater and a building wall; the position is limited by the tank, containment and vent rules below, by the road and walkway beside the wall, and by separation from A-800 and A-900 (industry practice).'};
export const A5400_CODES=[
 {id:'CR-1',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Art. 4.1.2.2(1) Heated liquids',referenceConfirmed:true,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s41',
  subject:'Heated oil is a Class I liquid',requirement:'A liquid with a flash point at or above 37.8 °C that is processed, stored, handled or used at or above its flash point is treated as a Class I liquid.',
  applies:['A-5400','H-5400','V-5401','T-5401'],check:'The oil runs at 250–280 °C, above any thermal-oil flash point, so the Class I rules apply to the hot system. The oil product and its flash point are not selected (vendor, U8).'},
 {id:'CR-2',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Art. 4.1.5.2(1) Ignition sources',referenceConfirmed:true,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s41',
  subject:'Open flame and sparks near Class I liquids',requirement:'A device, operation or activity that produces open flames, sparks or heat is not permitted in an area where Class I liquids are handled unless controlled so that it does not create a fire or explosion hazard.',
  applies:['A-5400','H-5400'],check:'The burner is the controlled ignition source of the system. Burner management and the hot-oil leak scenarios belong to the HAZOP (U8, FEED-PS-HOP-001).'},
 {id:'CR-3',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Art. 4.3.2.1(2) and Table 4.3.2.1; (6) not relied on',referenceConfirmed:true,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s43',
  subject:'Tank to a building on the same property',requirement:'An outside aboveground tank for stable liquids at up to 17 kPa gauge stands at least 3 m from a building on the same property (tanks up to 250 000 L); half that where fire or explosion protection in the tank conforms to Sentence 4.3.2.5.(2). The reduction for Class II and IIIA liquids (1.5 m, tanks up to 50 000 L) is not relied on because the heated oil is treated as Class I.',
  applies:['V-5401','T-5401'],limitM:3,evidence:'tankToWall'},
 {id:'CR-4',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Subsection 4.3.7 Secondary containment, Clearances (article number unconfirmed)',referenceConfirmed:false,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s43',
  subject:'Containment wall clear of the tank shell',requirement:'No part of a secondary containment wall is less than 1.5 m from a storage tank shell. The distance can be waived for a tank of up to 80 000 L that is double-walled or built to incorporate secondary containment, or that conforms to ULC-S655.',
  applies:['T-5401','V-5401'],limitM:1.5,evidence:'curbToTank'},
 {id:'CR-5',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Section 4.3 Vent piping, Location of vent pipe outlets (article number unconfirmed)',referenceConfirmed:false,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s43',
  subject:'Tank vent outlets',requirement:'Normal vent outlets for tanks of Class I liquids are outside buildings at least 3.5 m above the adjacent ground and 1.5 m from any building opening, and discharge so vapours cannot enter or be trapped near the building. Emergency vent outlets are at least 1.5 m from building openings and from combustible parts of an exterior wall.',
  applies:['V-5401','T-5401'],limitM:3.5,evidence:'ventHeight'},
 {id:'CR-6',kind:'Standard (BC Gas Safety Regulation adopts CSA B149)',source:'CSA B149.1 Natural gas and propane installation code',reference:'Gas train and vent terminal clearances (clause numbers and edition unconfirmed)',referenceConfirmed:false,url:'https://www.technicalsafetybc.ca/regulatory-resources/regulatory-notices/directive-special-venting-system-and-type-bh-venting-system-termination-clearances',
  subject:'Gas-fired appliance clearances',requirement:'Manufacturer tables for Canadian installations show vent terminals 0.9 m or more from an openable window or door and 1.2–1.8 m from air inlets. The heater certification and installation instructions set the clearance to combustible walls.',
  applies:['A-5400','H-5400'],limitM:1.8,evidence:'stackToWall',check:'Heater vendor data and the gas-appliance evaluation set the real clearances (U8).'},
 {id:'CR-7',kind:'BC regulation',source:'Power Engineers, Boiler, Pressure Vessel and Refrigeration Safety Regulation, B.C. Reg. 104/2004',reference:'s. 6 and s. 84.1 (low pressure thermal fluid plants)',referenceConfirmed:true,url:'https://www.technicalsafetybc.ca/thermal-pressure-fluid-plants',
  subject:'Low-pressure thermal fluid plant',requirement:'A plant protected so it cannot keep operating at the vapour point of the fluid is exempt from certified operator staffing if it has an automated control system whose design is registered with the provincial safety manager, with approval by a professional engineer, before installation starts. The owner designates and notifies a competent responsible person.',
  applies:['A-5400','H-5400'],check:'No distance rule found. Registration of the control system design and the responsible-person notice are open (owner).'},
 {id:'CR-8',kind:'BC Fire Code',source:'BC Fire Code 2018, Division B',reference:'Section 4.3, Fire department access (article number unconfirmed)',referenceConfirmed:false,url:'https://free.bcpublications.ca/civix/document/id/public/bcfc2018/bcfc_2018dbp4s43',
  subject:'Fire department access to tanks',requirement:'Outdoor storage areas allow fire department vehicles to approach within 60 m travelling distance of any storage tank.',
  applies:['T-5401','V-5401'],limitM:60,evidence:'roadToTank'},
 {id:'CR-9',kind:'Industry practice (not a BC code)',source:'General fired-heater siting practice; HAZOP (U8, FEED-PS-HOP-001)',reference:'About 15 m from flammable process areas (not verified against a named standard)',referenceConfirmed:false,url:null,
  subject:'Separation from hydrogen and flammable areas',requirement:'Fired heaters are commonly kept about 15 m from areas that can release flammable gas or vapour. The distance is measured to the release source or the classified area, not to a block outline.',
  applies:['A-5400','H-5400'],limitM:15,evidence:'toA800'},
 {id:'CR-10',kind:'Not yet researched',source:'BC Gas Safety Regulation and CSA B149.3 (field evaluation of fuel-related equipment); BC Building Code spatial separation if the wall becomes a rated exposure; stack emission permitting',reference:'—',referenceConfirmed:false,url:null,
  subject:'Open research',requirement:'Not read for V317. Needed before the position is treated as final.',applies:['A-5400'],researched:false}
];
// The IDs that bear on each tagged record, quoted in the equipment descriptions.
const USE={'A-5400':['CR-1','CR-2','CR-3','CR-4','CR-5','CR-6','CR-7','CR-8','CR-9'],'H-5400':['CR-1','CR-2','CR-6','CR-7','CR-9'],'V-5401':['CR-1','CR-3','CR-4','CR-5','CR-8'],'T-5401':['CR-1','CR-3','CR-4','CR-5','CR-8']};
export const A5400_POSITION_SENTENCE=' Outside the east building wall, 6.4 m from its outer face (V317, option C); ≈ 47 m from the A-600 edge (DR-601), ≈ 17 m from the A-800 block edge, ≈ 43 m from the PY-801 hydrogen off-gas point and ≈ 24 m from the A-900 block; the perimeter logistics road is rerouted around the pad — HAZOP inputs (U8, FEED-PS-HOP-001), not a spacing ruling.';
export function a5400CodesSentence(tag){const ids=USE[tag];if(!ids)return '';const rows=A5400_CODES.filter(c=>ids.includes(c.id));
 return ' Codes and regulations, tracked in the A-5400 assembly & design review (a5400-review.html), all to confirm: '+rows.map(c=>c.id+' '+c.reference.replace(/ \(.*$/,'')+' ('+c.source.replace(/, Division B$/,'').replace(/ Natural gas and propane installation code$/,'')+')').join('; ')+'.';}
