import * as T from './vendor/three.module.js';
import {ACCESS_BASIS,ACCESS_ZONES,ROUTING_RULES} from './access-layout.js';
const V=a=>new T.Vector3(...a),arr=p=>p.toArray(),box=(min,max)=>new T.Box3(V(min),V(max));
export function componentEnvelope(p,allowance=0){p.geometry.computeBoundingBox();return p.geometry.boundingBox.clone().applyMatrix4(new T.Matrix4().compose(p.position,p.quaternion,p.scale)).expandByScalar(allowance);}
// Retain a conservative local mesh box, but respect its orientation. A diagonal
// conveyor's world AABB spans empty space on both sides of its actual casing.
export function componentIntersectsBox(p,target,allowance=0,broadBounds=null){
 if(!(broadBounds||componentEnvelope(p,allowance)).intersectsBox(target))return false;
 p.geometry.computeBoundingBox();const local=p.geometry.boundingBox,center=local.getCenter(new T.Vector3()).multiply(p.scale).applyQuaternion(p.quaternion).add(p.position),half=local.getSize(new T.Vector3()).multiply(p.scale.clone().set(Math.abs(p.scale.x),Math.abs(p.scale.y),Math.abs(p.scale.z))).multiplyScalar(.5).addScalar(allowance),otherHalf=target.getSize(new T.Vector3()).multiplyScalar(.5),delta=target.getCenter(new T.Vector3()).sub(center);
 const world=[V([1,0,0]),V([0,1,0]),V([0,0,1])],axes=world.map(a=>a.clone().applyQuaternion(p.quaternion)),separators=[...world,...axes,...world.flatMap(a=>axes.map(b=>a.clone().cross(b)))],sizes=half.toArray();
 for(const axis of separators){if(axis.lengthSq()<1e-12)continue;const a=axes.reduce((r,u,i)=>r+sizes[i]*Math.abs(axis.dot(u)),0),b=otherHalf.x*Math.abs(axis.x)+otherHalf.y*Math.abs(axis.y)+otherHalf.z*Math.abs(axis.z);if(Math.abs(delta.dot(axis))>a+b+1e-8)return false;}
 return true;
}
function pointInDeck(point,model){const decks=[...(model.accessSystem?.decks||[])];return decks.find(d=>point[0]>=d.min[0]&&point[0]<=d.max[0]&&point[2]>=d.min[2]&&point[2]<=d.max[2]&&point[1]-d.min[1]>=.6&&point[1]-d.min[1]<=1.7);}
export function buildAccessRegister(model){
 if(model.scope==='future')return {basis:ACCESS_BASIS,zones:[],components:[],routes:[],scope:'archive excluded'};
 const parts=model.parts,byId=new Map(parts.map(p=>[p.id,p])),components=[],covered=new Set();
 function record(tag,owner,ids,category,point,meta={}){
  if(meta.remoteDisplay)category='measurement-protection';
  const e=model.equipment[owner];if(!e||components.some(c=>c.equipmentId===owner&&c.tag===tag&&c.partIds[0]===ids[0]))return;const physical=ids.map(id=>byId.get(id)).filter(Boolean),control=physical.find(p=>/adjusting knob|handwheel rim|handle grip/.test(p.name))||physical.find(p=>/ display$/.test(p.name));
  const maintenancePoint=category==='automatic'||meta.thermal?physical.find(p=>/actuator/.test(p.name)):null;point=control?arr(control.position):maintenancePoint?arr(maintenancePoint.position):point;if(control?.name.includes('handwheel rim'))point[0]+=.14;const envelope=new T.Box3();for(const p of physical)envelope.union(componentEnvelope(p));
  const a400Rear=/^XV-TFF-[A-H]-RET$|^XV-RET402$|^PCV-TFF402/.test(tag),a400Standing=a400Rear?[point[0],0,/^PCV-TFF402/.test(tag)?18.4:18.25]:null;
  const waterTask=physical.find(p=>p.serviceAccess)?.serviceAccess;const task=model.accessSystem?.tasks.find(t=>t.equipmentId===owner&&physical.some(p=>p.name===t.partName)),desired=task?[...task.standing]:waterTask?[...waterTask.standing]:a400Standing||[point[0],0,point[2]+.8],deck=task?model.accessSystem.decks.find(d=>d.id===task.deckId):pointInDeck(desired.map((v,i)=>i===1?point[1]:v),model);if(deck)desired[1]=deck.min[1];
  const height=point[1]-desired[1],routine=category==='routine',automatic=category==='automatic',inReach=height>=ACCESS_BASIS.routineHandHeight[0]&&height<=(meta.display?ACCESS_BASIS.routineDisplayHeight[1]:ACCESS_BASIS.routineHandHeight[1]);
  const elevated=height>1.7;let method=deck?'Permanent platform '+deck.id:'Grade service bay',status='proposed';
  if(elevated&&!task){method=routine?'Permanent access or control relocation required':'Planned mobile access during isolated shutdown';status='access-review-open';if(!routine)desired[1]=Math.max(0,point[1]-1.3);}
  if(waterTask){method=waterTask.method;meta={...meta,accessQualification:'Proposed service position; vendor task envelope and isolation require verification'};}
  if(task){method=task.method;meta={...meta,taskId:task.id,accessQualification:task.qualification||task.gate,accessDeck:task.deckId};}
  const priorityZone=ACCESS_ZONES.find(z=>z.id===(owner===71?'SERVICE-DR601':owner===74?'SERVICE-F601':([46,92].includes(owner)||/^(XV-F161|XV-166-FEED|FCV-168|FT-168|XV-161-)/.test(tag))?'SERVICE-F161-UPPER':[93,94,95,96].includes(owner)?'SERVICE-F166':''));
  if(owner>=125&&!task&&!waterTask){
   if(e.tag.startsWith('P-')){desired[0]=e.x+1.1;desired[2]=e.z;}
   if(/manway|XV-DR/.test(tag)){desired[0]=point[0];desired[2]=point[2]-1.0;}
  }
  const footprint={min:[desired[0]-.45,desired[1]+.02,desired[2]-.45],max:[desired[0]+.45,desired[1]+2.12,desired[2]+.45]};
  const withdrawal={min:envelope.min.clone().add(new T.Vector3(-.15,0,-.1)).toArray(),max:envelope.max.clone().add(new T.Vector3(.15,.6,.75)).toArray()};
  if(task?.withdrawalAxis?.[2]<0||(owner>=125&&/manway|XV-DR/.test(tag))){withdrawal.min[2]=envelope.min.z-.75;withdrawal.max[2]=envelope.max.z+.1;}const actuator=physical.find(p=>/actuator/.test(p.name));
  components.push({id:'access-'+owner+'-'+tag+'-'+ids[0],tag,equipmentId:owner,equipmentTag:e.tag,areaId:e.areaId,designStatus:physical.some(p=>p.designStatus==='proposed')?'proposed':e.designStatus,category,partIds:ids,interactionPoint:point,standingPosition:desired,standingSpace:footprint,handOrDisplayHeight:point[1]-desired[1],heightAboveCurrentStandingSurface:height,horizontalReach:Math.hypot(point[0]-desired[0],point[2]-desired[2]),method,status,routineReach:!routine||inReach,maintenanceEnvelope:withdrawal,withdrawalBasis:task?.withdrawalAxis?'Outward cover withdrawal from the assigned service face; vendor tool and handling allowance HOLD.':'Provisional tool, actuator and probe envelope; replace with vendor dimensions.',mobileAccess:elevated&&!routine&&!task?{base:priorityZone?[(priorityZone.min[0]+priorityZone.max[0])/2,0,(priorityZone.min[2]+priorityZone.max[2])/2]:[desired[0],0,desired[2]],baseZone:priorityZone?.id||null,workingPosition:desired,requiredWorkingHeight:desired[1],status:'HOLD: approach, obstructions, outreach, stabilizers and rated lift capacity must be qualified'}:null,actuator:automatic?actuator?.name||'Actuator type to be specified':null,controlConnection:automatic?{controller:e.areaId+' controls',signal:tag+' command / feedback',energy:/electric/i.test(actuator?.name||'')?'Electrical power and control I/O':'Instrument air and solenoid I/O; connection qualification required',failureAction:null,status:'Proposed functional link; I/O, power/air and failure action unqualified'}:null,localIsolation:automatic||category==='periodic'?'Identify, lock and prove all pressure / electrical / pneumatic sources isolated; isolate process-side backflow before removal. Detailed isolation plan HOLD.':null,processConnectionPolicy:category==='measurement-protection'?ROUTING_RULES.measurementProtection:null,...meta});for(const id of ids)covered.add(id);
 }
 for(const [index,v]of model.valves.entries()){
  if(!v.a||!v.b)continue;const ids=v.partIds?.filter(id=>byId.has(id))||parts.filter(p=>p.reactor===v.reactor&&(p.name===v.label||p.name.startsWith(v.label+' ·')||p.name.startsWith(v.label+' '))).map(p=>p.id);if(!ids.length)continue;
  const tag=v.tag||v.label||'valve-'+index,category=/^PSV|relief/i.test(tag)?'measurement-protection':/BLD-|maintenance blind/i.test(tag)?'periodic':v.type==='check'?'periodic':v.type==='bulk-isolation'||v.thermal?'automatic':'routine';record(tag,v.reactor,ids,category,v.a.map((x,i)=>(x+v.b[i])/2),v.thermal?{thermal:true,areaId:v.serviceArea||model.equipment[v.reactor]?.areaId,servicePolicy:v.servicePolicy||'Actuated representation; control energy, I/O, failure position and isolation procedure remain unqualified'}:{});if(['lever','wheel'].includes(v.type)){const c=components.find(c=>c.equipmentId===v.reactor&&c.tag===tag&&c.partIds[0]===ids[0]),dir=V(v.b).sub(V(v.a)).normalize(),axis=Math.abs(dir.z)<.8?[0,0,1]:[0,1,0],pivot=V(v.a).lerp(V(v.b),.5).addScaledVector(V(axis),.2),r=v.type==='wheel'?.165:.34,size=axis.map(n=>n?.04:r);c.operatingEnvelope={min:pivot.clone().sub(V(size)).toArray(),max:pivot.clone().add(V(size)).toArray(),basis:'Conservative full handle sweep about modeled stem; replace with vendor travel envelope'};}
 }
 for(const p of parts){if(covered.has(p.id)||!(/ display$|adjusting knob|handwheel rim|handle grip|probe|maintenance blind|electric actuator|pneumatic actuator|generator cabinet|electric motor$|VFD motor$|metering motor$|20 hp vibration motor envelope$|P-401[A-Z0-9]+ motor$|feed motor$|agitator motor$|access cover$|manway cover$|plenum cover$|pump volute$|^PSV-.*(?:relief body|spring bonnet)$/i.test(p.name)))continue;
  const display=/display$/.test(p.name),tag=p.accessTag||p.name.split(' ')[0],category=display?'routine':/probe|relief|^PSV-/i.test(p.name)?'measurement-protection':/actuator/.test(p.name)?'automatic':'periodic';
  const ids=display||/^PSV-/.test(p.name)?parts.filter(q=>q.reactor===p.reactor&&q.system==='valve'&&(q.id===p.id||q.name.startsWith(p.name.split(' ')[0]+' '))).map(q=>q.id):[p.id];
  record(tag+' / '+p.name,p.reactor,ids,category,arr(p.position),{display,remoteSource:p.remoteSource||null,remoteDisplay:p.remoteDisplay||null});
 }
 const routes=model.routes.map(r=>{const classification=/suction|hydraulic passage/i.test(r.label)?'pumpSuction':/drain|effluent/i.test(r.service+' '+r.label)||/gravity drainage/i.test(r.label)?'gravityDrain':/sensing|sample|relief/i.test(r.service)?'measurementProtection':/off-gas|vent|exhaust|vapor/i.test(r.service)?'gasDischarge':/solid|powder|Dry GO|rGO|cake/i.test(r.service)?'containedSolids':/argon|nitrogen|water|cooling|thermal/i.test(r.service)?'pressurizedUtility':'processTransfer';return{id:r.id,name:r.label,areaId:model.equipment[r.reactor].areaId,classification,rule:ROUTING_RULES[classification],insulationAllowance:ACCESS_BASIS.pipeInsulationAllowance,elevationChangePolicy:['gravityDrain','pumpSuction'].includes(classification)?'Preserve profile; hydraulic review required before any elevation edit':'Review routing against reserved access zones'};});
 const zones=[...model.fireSafety?.accessZones||[],...ACCESS_ZONES.filter(z=>!(model.designScenario!=='enclosed'&&['APPROACH-PL166','SERVICE-F161-UPPER'].includes(z.id))&&!(model.designScenario==='baseline'&&z.id==='SERVICE-F166')),...model.thermalUtilities?.accessZones||[],...model.containment?.accessZones||[],...model.compressedAir?.accessZones||[],...model.reactorAir?.accessZones||[]];
 for(const c of components){const local=c.equipmentId===89?'701':c.equipmentId===112?'801':null;if(local){const upstream=c.tag==='XV-AR'+local+'-MAIN'?'XV-AR6201-'+(local==='701'?'700':'800'):'XV-AR'+local+'-MAIN';c.isolationPlan={upstreamTag:upstream,sharedBranchTag:'XV-AR6201-'+(local==='701'?'700':'800'),processSide:'Positive isolation from receiving equipment and proof of depressurization required; non-return valve alone is not maintenance isolation.',energy:'Lock and prove actuator energy isolated before removal.',status:'Supply tags assigned; approved isolation sequence HOLD'};if(c.localIsolation)c.localIsolation='Upstream supply isolation: '+upstream+'. '+c.isolationPlan.processSide+' '+c.isolationPlan.energy;}else if(c.category==='automatic'||c.category==='periodic'||c.category==='measurement-protection')c.isolationPlan={upstreamTag:c.equipmentId===117&&c.tag!=='XV-AR6201-MAIN'?'XV-AR6201-MAIN':c.equipmentId===122?(c.tag.includes('6102')?'XV-6102-RESERVE':'XV-6101-PRIMARY'):null,processSide:'Isolation boundary and proof points require equipment/P&ID review.',status:'HOLD: no unverified isolation valve tag assigned'};}
 for(const c of components)if(c.tag==='XV-DF402'){
  c.method='Automatic operation from HS-DF402 at grade; isolated shutdown maintenance by planned mobile access';
  c.controlConnection={controller:'A-400 controls / HS-DF402',signal:'XV-DF402 command and position feedback',energy:'Instrument air and solenoid I/O — supplier connection HOLD',failureAction:null,status:'Proposed; fail position, interlocks and isolation sequence require P&ID review'};
  c.mobileAccess={base:[9.15,0,23.2],baseZone:'SERVICE-RO402',workingPosition:[11.1,c.interactionPoint[1]-1.3,22.8],requiredWorkingHeight:c.interactionPoint[1]-1.3,status:'HOLD: rated lift, outreach, approach and stabilizer envelope must be qualified'};
  c.standingPosition=[...c.mobileAccess.workingPosition];c.handOrDisplayHeight=1.3;c.status='access-review-open';
  c.isolationPlan={upstreamTag:null,externalBoundary:'BL-RO400',processSide:'Isolate and prove both RO supply and tank-side pressure; the non-return valve is not positive maintenance isolation.',status:'External supply isolation and tank-side procedure require P&ID confirmation'};
 }
 for(const c of components)if(c.mobileAccess)c.mobileAccess.requiredHorizontalOutreach=Math.hypot(c.standingPosition[0]-c.mobileAccess.base[0],c.standingPosition[2]-c.mobileAccess.base[2]);
 return {basis:ACCESS_BASIS,permanentAccess:model.accessSystem,zones,components,routes,rules:ROUTING_RULES,scope:'Assembled FEED arrangement; all serviceable controls and displays identified in the model'};
}
// All modeled external geometry is screened, including fittings, handles, supports,
// actuator envelopes and fasteners. Internal process parts cannot obstruct an aisle.
export function inspectAccess(model,register=buildAccessRegister(model)){
 const envelopes=model.parts.filter(p=>p.system!=='internal').map(p=>({p,bounds:componentEnvelope(p,p.system==='pipe'?(p.insulationThickness??ACCESS_BASIS.pipeInsulationAllowance):0)}));
 for(const c of register.components)if(c.operatingEnvelope){const p=model.parts.find(p=>p.id===c.partIds[0]);if(p)envelopes.push({p,bounds:box(c.operatingEnvelope.min,c.operatingEnvelope.max),swept:true});}
 const conflicts=[];const inspect=(zone,exclude=new Set())=>{const bb=box(zone.min,zone.max);for(const {p,bounds,swept}of envelopes){const allowance=p.system==='pipe'?(p.insulationThickness??ACCESS_BASIS.pipeInsulationAllowance):0;if(exclude.has(p.id)||!bb.intersectsBox(bounds)||!swept&&!componentIntersectsBox(p,bb,allowance,bounds))continue;conflicts.push({zoneId:zone.id,kind:zone.kind,partId:p.id,equipmentId:p.reactor,part:p.name,underside:bounds.min.y,allowance});}};
 for(const z of register.zones)if(z.kind!=='utility')inspect(z);
 const standingConflicts=[],maintenanceConflicts=[];
 for(const c of register.components){const own=new Set(c.partIds),standing=box(c.standingSpace.min,c.standingSpace.max),maintenance=box(c.maintenanceEnvelope.min,c.maintenanceEnvelope.max);for(const {p,bounds}of envelopes){if(own.has(p.id))continue;if(standing.intersectsBox(bounds))standingConflicts.push({componentId:c.id,tag:c.tag,partId:p.id,part:p.name});if(maintenance.intersectsBox(bounds)&&p.reactor!==c.equipmentId)maintenanceConflicts.push({componentId:c.id,tag:c.tag,partId:p.id,part:p.name});}}
 const routineFailures=[];for(const c of register.components){if(c.category==='routine'&&!c.remoteDisplay&&!c.routineReach)routineFailures.push({id:c.id,tag:c.tag,point:c.interactionPoint,height:c.handOrDisplayHeight,reason:'Actual operating point outside proposed reach range'});}
 return {revision:ACCESS_BASIS.revision,geometryChecks:envelopes.length,zones:register.zones.length,components:register.components.length,conflicts,standingConflicts,maintenanceConflicts,routineFailures,passes:conflicts.length===0&&routineFailures.length===0&&standingConflicts.length===0&&maintenanceConflicts.length===0,qualification:'Screening only. Open findings are retained; a proposed access method is not a verified safe working arrangement.'};
}
