import {ACCESS_DESIGN} from './access-design.js';
import {structuralKit} from './structural-kit.js';

// Every tread, deck, rail and stringer has a modeled attachment path to grade.
export function accessKit(h,register){
 const s=structuralKit(h),{T,b,parts,structure}=h,V=p=>new T.Vector3(...p),C=ACCESS_DESIGN.criteria,columnCache=new Map();
 function mark(p,kind,tag){p.designStatus='proposed';p.accessGeometry={kind,tag};register.partIds.push(p.id);return p;}
 function beam(a,z,w,name,kind='member',d=w){return mark(s.beam(a,z,w,name,d),kind,name.split(' ')[0]);}
 function supportColumn(x,z,top,tag,w=.16){const key=x+','+z,old=columnCache.get(key);if(old&&old.top>=top)return old;const first=parts.length,col=s.column(x,z,top,tag,w);for(const p of parts.slice(first))mark(p,'support',tag.split(' ')[0]);columnCache.set(key,col);return col;}
 function deck(tag,min,max,y,{openings=[],guard=true,columns=true,holes=[],supportZ=[min[1]-.16,max[1]+.16],supportX=[min[0]-.16,max[0]+.16]}={}){
  let p;if(holes.length){const sh=new T.Shape(),cx=(min[0]+max[0])/2,cz=(min[1]+max[1])/2;sh.moveTo(min[0]-cx,min[1]-cz);sh.lineTo(max[0]-cx,min[1]-cz);sh.lineTo(max[0]-cx,max[1]-cz);sh.lineTo(min[0]-cx,max[1]-cz);sh.closePath();for(const hole of holes){const q=new T.Path();q.moveTo(hole.min[0]-cx,hole.min[1]-cz);q.lineTo(hole.min[0]-cx,hole.max[1]-cz);q.lineTo(hole.max[0]-cx,hole.max[1]-cz);q.lineTo(hole.max[0]-cx,hole.min[1]-cz);q.closePath();sh.holes.push(q);}p=mark(h.add(tag+' non-slip grating deck','frame',new T.ExtrudeGeometry(sh,{depth:.12,bevelEnabled:false}),[cx,y,cz],'steel',new T.Quaternion().setFromAxisAngle(new T.Vector3(1,0,0),Math.PI/2)),'deck',tag);}else p=mark(b(tag+' non-slip grating deck','frame',[max[0]-min[0],.12,max[1]-min[1]],[(min[0]+max[0])/2,y-.06,(min[1]+max[1])/2]),'deck',tag);s.load(p,tag);
  if(holes.length){let rects=[{min:[min[0],y-.12,min[1]],max:[max[0],y,max[1]]}];for(const hole of holes){const next=[];for(const r of rects){const x0=Math.max(r.min[0],hole.min[0]),x1=Math.min(r.max[0],hole.max[0]),z0=Math.max(r.min[2],hole.min[1]),z1=Math.min(r.max[2],hole.max[1]);if(x0>=x1||z0>=z1){next.push(r);continue;}for(const [a,z]of[[r.min,[x0,y,r.max[2]]],[[x1,y-.12,r.min[2]],r.max],[[x0,y-.12,r.min[2]],[x1,y,z0]],[[x0,y-.12,z1],[x1,y,r.max[2]]]])if(z[0]>a[0]&&z[2]>a[2])next.push({min:a,max:z});}rects=next;}p.screenBody={kind:'deck-with-holes',solids:rects};}
  const record={id:tag,partId:p.id,min:[min[0],y,min[1]],max:[max[0],y,max[1]],openings,holes,guardParts:[],gates:[],surface:'Slip-resistant grating; specification HOLD'};register.decks.push(record);
  if(y===0){structure.roots.push({part:p.id,local:[0,.5,0],elevation:0});}
  else if(columns){for(const zz of supportZ){const cols=supportX.map(x=>supportColumn(x,zz,y-.18,tag+' deck support',.16)),gz=Math.max(min[1]+.25,Math.min(max[1]-.25,zz)),girder=beam([cols[0].x,y-.18,gz],[cols[1].x,y-.18,gz],.24,tag+' landing edge girder','girder',.42);for(const col of cols){if(Math.abs(gz-zz)>.01){const cap=beam([col.x,y-.18,zz],[col.x,y-.18,gz],.20,tag+' column bearing arm');s.join(col.post,cap,[col.x,y-.18,zz],tag+' arm / column');s.join(cap,girder,[col.x,y-.18,gz],tag+' arm / girder');}else s.join(col.post,girder,[col.x,y-.18,zz],tag+' girder / column');}s.join(girder,p,[(min[0]+max[0])/2,y-.12,gz],tag+' deck bearing');}}

  if(guard)guardDeck(record,p);
  return {part:p,record};
 }
 function guardSegment(d,p,side,lo,hi,gate=false){
  if(hi-lo<.06)return;const alongX=side==='north'||side==='south',fixed=alongX?(side==='north'?d.max[2]-.015:d.min[2]+.015):(side==='east'?d.max[0]-.015:d.min[0]+.015),xy=t=>alongX?[t,d.min[1],fixed]:[fixed,d.min[1],t],a=xy(lo),z=xy(hi),posts=[];
  const n=Math.max(1,Math.ceil((hi-lo)/1.3));for(let i=0;i<=n;i++){const pt=V(a).lerp(V(z),i/n).toArray(),top=[pt[0],pt[1]+C.guardrail,pt[2]],post=beam(pt,top,.04,d.id+' guard post','guard-post');s.join(p,post,pt,d.id+' guard base');s.load(post,d.id+' guard post');posts.push({p:post,at:pt});d.guardParts.push(post.id);}
  for(const dy of[C.guardrail,.535]){const rail=beam([a[0],a[1]+dy,a[2]],[z[0],z[1]+dy,z[2]],.035,d.id+(gate?' self-closing service gate':' perimeter guardrail'),'guardrail');for(const post of posts)s.join(post.p,rail,[post.at[0],post.at[1]+dy,post.at[2]],d.id+' rail / post');s.load(rail,d.id+' guardrail');d.guardParts.push(rail.id);if(gate){rail.accessGeometry.gate=true;d.gates.push(rail.id);}}
  const center=V(a).add(V(z)).multiplyScalar(.5).toArray();center[1]+=C.toeboard/2;const toe=mark(b(d.id+' toeboard','frame',alongX?[hi-lo,C.toeboard,.025]:[.025,C.toeboard,hi-lo],center),'toeboard',d.id);for(const post of posts)s.join(post.p,toe,[post.at[0],post.at[1]+C.toeboard/2,post.at[2]],d.id+' toe / post');d.guardParts.push(toe.id);
  if(gate){toe.accessGeometry.gate=true;d.gates.push(toe.id);const hinge=mark(h.c(d.id+' spring-return gate hinge','frame',.055,.22,[a[0],a[1]+.8,a[2]],'dark'),'gate-hinge',d.id),latch=mark(b(d.id+' positive gate latch','frame',[.10,.09,.10],[z[0],z[1]+.8,z[2]],'dark'),'gate-latch',d.id);s.join(posts[0].p,hinge,[a[0],a[1]+.8,a[2]],d.id+' gate hinge fixing');s.join(posts.at(-1).p,latch,[z[0],z[1]+.8,z[2]],d.id+' gate latch fixing');d.guardParts.push(hinge.id,latch.id);d.gateHardware??=[];d.gateHardware.push({hinge:hinge.id,latch:latch.id,closed:true,opening:'Controlled opening only with task-specific fall protection; hardware and swing clearance HOLD'});}

 }
 function guardDeck(d,p){
  for(const side of['west','east','south','north']){const alongX=side==='north'||side==='south',min=d.min[alongX?0:2]+.015,max=d.max[alongX?0:2]-.015,holes=d.openings.filter(o=>o.side===side).sort((a,b)=>a.min-b.min);let cursor=min;
   for(const o of holes){guardSegment(d,p,side,cursor,Math.min(o.min,max));if(o.kind==='service-gate')guardSegment(d,p,side,Math.max(min,o.min),Math.min(max,o.max),true);cursor=Math.max(cursor,o.max);}guardSegment(d,p,side,cursor,max);
  }
 }
 function flight(tag,x,z0,z1,y0,y1,bottom,top){
  const n=Math.ceil((y1-y0)/C.maxRiser),riser=(y1-y0)/n,going=Math.abs(z1-z0)/(n-1),dir=Math.sign(z1-z0),width=C.minClearWidth+.14,stringers=[],treads=[],nosingIds=[],railIds=[];
  const seats=[];for(const [end,y,zz,d]of[['lower',y0,z0,bottom],['upper',y1,z1,top]]){const yy=y-(end==='upper'?.18:.08),sz=zz+(end==='upper'?dir*.10:0),seat=beam([x-width/2-.05,yy,sz],[x+width/2+.05,yy,sz],.20,tag+' '+end+' bearing seat');s.join(d.part,seat,[x,y-.12,zz],tag+' seat / landing');seats.push(seat);}
  for(const dx of[-width/2,width/2]){const a=[x+dx,y0+riser/2-.18,z0],z=[x+dx,y1-riser/2-.18,z1],p=beam(a,z,.10,tag+' stair stringer','stringer',.18);s.join(seats[0],p,a,tag+' lower stringer seat');s.join(seats[1],p,z,tag+' upper stringer seat');s.load(p,tag+' stringer');stringers.push(p);}
  for(let i=1;i<n;i++){const yy=y0+i*riser,zz=z0+dir*(i-.5)*going,p=mark(b(tag+' stair tread '+i,'frame',[width,.08,going],[x,yy-.04,zz]),'tread',tag);for(const [j,dx]of[-width/2,width/2].entries())s.join(p,stringers[j],[x+dx,yy-.08,zz],tag+' tread / stringer');s.load(p,tag+' tread '+i);treads.push(p.id);const nose=mark(b(tag+' anti-slip nosing '+i,'frame',[width,.012,.035],[x,yy-.0055,z0+dir*(i-1)*going+dir*.025],'dark'),'nosing',tag);s.join(p,nose,[x,yy,nose.position.z],tag+' nosing fixing');nosingIds.push(nose.id);}
  for(const dx of[-width/2,width/2]){
   const posts=[];for(const i of [...new Set([1,...Array.from({length:Math.ceil((n-1)/4)},(_,j)=>Math.min(n-1,1+j*4)),n-1])]){const zz=z0+dir*(i-1)*going,yy=y0+i*riser,post=beam([x+dx,yy,zz],[x+dx,yy+C.handrail,zz],.04,tag+' stair rail post','stair-post');s.join(parts.find(p=>p.id===treads[i-1]),post,[x+dx,yy,zz],tag+' stair post / tread');posts.push({part:post,y:yy,z:zz});}
   const upperPost=beam([x+dx,y1,z1],[x+dx,y1+C.handrail,z1],.04,tag+' upper landing handrail post','stair-post');s.join(top.part,upperPost,[x+dx,y1,z1],tag+' top handrail post / landing');posts.push({part:upperPost,y:y1,z:z1});
   for(const dy of[C.handrail,C.handrail/2]){const rail=beam([x+dx,y0+riser+dy,z0],[x+dx,y1+dy,z1],.035,tag+(dy===C.handrail?' continuous stair handrail':' stair midrail'),'stair-handrail');for(const p of posts)s.join(p.part,rail,[x+dx,p.y+dy,p.z],tag+' rail / baluster');s.load(rail,tag+' handrail');railIds.push(rail.id);}
  }
  const f={tag,bottom:bottom.record.id,top:top.record.id,y0,y1,x,z0,z1,riserCount:n,riser,going,clearWidth:C.minClearWidth,treads,nosingIds,stringers:stringers.map(p=>p.id),railIds,handrailHeight:C.handrail,headroom:C.headroom};register.flights.push(f);return f;
 }
 function tower(tag,cfg){
  const width=2.7,land=C.landingDepth,run=Math.max(...cfg.levels.slice(1).map((y,i)=>(Math.ceil((y-cfg.levels[i])/C.maxRiser)-1)*C.minGoing)),near=cfg.z,far=cfg.z+land+run,xs=[cfg.x+.675,cfg.x+2.025],landings=[];
  for(let i=cfg.levels.length-1;i>=0;i--){const north=i%2===1,z=north?far:near,side=north?'south':'north',openings=(tag==='PL-601'?[7.6,10,11.3].includes(cfg.levels[i]):i===cfg.levels.length-1)?[{side:tag==='PL-601'?'west':'east',min:z+.04,max:z+land-.04,kind:'bridge'}]:[];for(const lane of[i-1,i].filter(j=>j>=0&&j<cfg.levels.length-1))openings.push({side,min:xs[lane%2]-.62,max:xs[lane%2]+.62,kind:'stair'});const d=deck(tag+' landing '+i,[cfg.x,z],[cfg.x+width,z+land],cfg.levels[i],{openings,guard:i>0,...(tag==='PL-166'&&i===1?{supportZ:[z+.22,z+land-.22]}:{}),...(tag==='PL-601'&&north?{supportX:[cfg.x,cfg.x+width+.16]}:{})});landings[i]=d;}
  for(let i=0;i<cfg.levels.length-1;i++){const forward=i%2===0,z0=forward?near+land:far,zEnd=forward?far:near+land,n=Math.ceil((cfg.levels[i+1]-cfg.levels[i])/C.maxRiser),actualRun=(n-1)*C.minGoing,z1=z0+(forward?1:-1)*actualRun;let end=landings[i+1];if(Math.abs(zEnd-z1)>.01){end=deck(tag+' flight '+(i+1)+' extended landing',[xs[i%2]-.62,Math.min(z1,zEnd)],[xs[i%2]+.62,Math.max(z1,zEnd)],cfg.levels[i+1],{columns:false,openings:[{side:'south',min:xs[i%2]-.64,max:xs[i%2]+.64},{side:'north',min:xs[i%2]-.64,max:xs[i%2]+.64}]});s.join(end.part,landings[i+1].part,[xs[i%2],cfg.levels[i+1]-.06,zEnd],'Extended landing / main landing');for(const dx of[-.52,.52]){const girder=beam([xs[i%2]+dx,cfg.levels[i+1]-.22,z1],[xs[i%2]+dx,cfg.levels[i+1]-.22,zEnd],.20,tag+' extended landing girder');s.join(end.part,girder,[xs[i%2]+dx,cfg.levels[i+1]-.12,(z1+zEnd)/2],tag+' extension deck / girder');s.join(girder,landings[i+1].part,[xs[i%2]+dx,cfg.levels[i+1]-.12,zEnd],tag+' extension girder / landing');s.load(girder,tag+' extension girder');}register.links.push([end.record.id,landings[i+1].record.id]);}flight(tag+' flight '+(i+1),xs[i%2],z0,z1,cfg.levels[i],cfg.levels[i+1],landings[i],end);}
  const t={tag,...cfg,width,run,landingDepth:land,landings:landings.map(d=>d.record.id),entry:[xs[0],0,near+.6],partIds:parts.filter(p=>p.accessGeometry?.tag.startsWith(tag)).map(p=>p.id)};register.towers.push(t);return{...t,landings};
 }
 return{deck,flight,tower,beam,guardDeck,supportColumn,structural:s,mark};
}

export function buildPlantAccess(h,{a160,deck:optionDeck=null}={}){
 const register={basis:ACCESS_DESIGN,partIds:[],decks:[],flights:[],towers:[],links:[],tasks:[],lifting:[],findings:[]},k=accessKit(h,register),s=k.structural,{b,c,parts,setContext}=h;
 for(const [tag,cfg]of Object.entries(ACCESS_DESIGN.towers)){if(cfg.scenario&&cfg.scenario!==a160)continue;setContext(cfg.owner,tag+' permanent access');const t=k.tower(tag,cfg);
  if(tag==='PL-601'){
   for(const [level,zMin,zMax,label]of[[11.3,15.2,16.6,'atomizer handling bridge'],[10,8.4,9.95,'rear service bridge'],[7.6,15.2,16.6,'lower service bridge']]){
    const d=k.deck('PL-601 '+label,[56.6,zMin],[74.4,zMax],level,{columns:false,openings:[...(level===10?[{side:'east',min:zMin,max:zMax}]:[{side:'south',min:73,max:74.4},{side:'east',min:15.2,max:15.3}]),...(level===10?[{side:'north',min:57.45,max:58.55,kind:'service-gate'}]:level===7.6?[{side:'south',min:56.6,max:57.95,kind:'bridge'},{side:'south',min:62.2,max:64.6,kind:'bridge'}]:[])]});
    for(const x of[56.7,62.7,68.4,74.3]){const col=k.supportColumn(x,zMax+(level===10?.08:.16),level-.12,'PL-601 bridge support',.18);const arm=k.beam([x,level-.22,zMax+(level===10?.08:.16)],[x,level-.22,zMax-.15],.22,'PL-601 bridge bearing arm');s.join(col.post,arm,[x,level-.22,zMax+(level===10?.08:.16)],'PL-601 bridge column / arm');s.join(arm,d.part,[x,level-.12,zMax-.15],'PL-601 bridge bearing');}
    // Beam across the span transfers the bridge floor to the supporting columns.
    const girder=k.beam([56.7,level-.22,zMax-.1],[74.3,level-.22,zMax-.1],.24,'PL-601 bridge girder');s.join(girder,d.part,[65,level-.12,zMax-.1],'PL-601 deck / girder');
    let landing=t.landings[cfg.levels.indexOf(level)];if(level!==10){const link=k.deck('PL-601 '+level+' tower bridge link',[73.0,14.1],[74.4,16.6],level,{columns:false,openings:[{side:'east',min:14.1,max:15.3},{side:'west',min:15.2,max:16.6}]});s.join(link.part,landing.part,[74.4,level-.06,14.7],'PL-601 bridge link / landing');s.join(link.part,d.part,[73.1,level-.06,15.8],'PL-601 bridge link / corridor');register.links.push([link.record.id,landing.record.id],[link.record.id,d.record.id]);landing=link;}const contactZ=(Math.max(zMin,landing.record.min[2])+Math.min(zMax,landing.record.max[2]))/2;s.join(d.part,landing.part,[74.4,level-.06,contactZ],'PL-601 bridge / tower landing');register.links.push([d.record.id,landing.record.id]);
   }
   const bridge=register.decks.find(d=>d.id==='PL-601 lower service bridge'),bp=parts.find(p=>p.id===bridge.partId),fd=k.deck('PL-601 collector service bay',[62.2,14.15],[64.6,15.2],7.6,{columns:false,openings:[{side:'north',min:62.2,max:64.6},{side:'south',min:62.7,max:63.7,kind:'service-gate'}]}),md=k.deck('PL-601 lower manway bay',[56.6,14.15],[57.95,15.2],7.6,{columns:false,openings:[{side:'north',min:56.6,max:57.95},{side:'south',min:56.75,max:57.85,kind:'service-gate'}]});for(const bay of[fd,md]){s.join(bay.part,bp,[(bay.record.min[0]+bay.record.max[0])/2,7.54,15.2],'PL-601 bay / service bridge');register.links.push([bay.record.id,bridge.id]);}
   register.tasks.push({id:'DR601-LOWER-MANWAY',equipmentId:71,partName:'DR-601 lower manway cover',deckId:md.record.id,standing:[57.3,7.6,14.7],category:'periodic',method:'Permanent stair / lower working platform',gate:'Controlled service gate; restraint and cover-handling procedure before opening'},
    {id:'DR601-UPPER-MANWAY',equipmentId:71,partName:'DR-601 upper manway cover',deckId:'PL-601 rear service bridge',standing:[58,10,9.4],category:'periodic',withdrawalAxis:[0,0,-1],method:'Permanent stair / rear working platform',gate:'Controlled service gate; restraint and cover-handling procedure before opening'},
    {id:'F601-PLENUM',equipmentId:74,partName:'F-601 removable plenum cover',deckId:fd.record.id,standing:[63.85,7.6,14.7],category:'periodic',method:'Permanent platform for isolation and supervised lifting; no reaching into collector',qualification:'Vendor cover disconnection, lifting and bag-withdrawal procedure HOLD'});
   const col=s.column(59.2,16.85,15.8,'PL-601 atomizer handling mast',.20),arm=k.beam([59.2,15.7,16.85],[58,15.7,12],.18,'PL-601 proposed atomizer lifting beam');s.join(col.post,arm,[59.2,15.7,16.85],'Handling beam / mast');s.load(arm,'PL-601 lifting beam');const hoist=k.mark(b('PL-601 powered hoist concept','frame',[.3,.25,.38],[58.96,15.5,15.88],'blue'),'hoist','PL-601');s.join(arm,hoist,[58.96,15.62,15.88],'PL-601 hoist trolley / beam');s.load(hoist,'PL-601 hoist trolley');
   register.lifting.push({id:'LIFT-DR601',equipmentId:71,min:[57.6,12.4,11.6],max:[58.4,15.3,12.4],...ACCESS_DESIGN.lifting.atomizer},{id:'LIFT-F601',equipmentId:74,min:[62.25,9.4,11.05],max:[64.15,12.0,12.95],...ACCESS_DESIGN.lifting.filter});
   register.findings.push({id:'DR601-ATOMIZER-VENDOR',status:'open',note:'Handling access is provided; final atomizer connection access, load rating, lifting path after service disconnection and rescue are vendor/design HOLD.'});
  } else if(tag==='PL-801'){
   const d1=k.deck('PL-801 stair approach bridge',[89.9,16.84],[91.25,22.25],7.08,{supportZ:[16.68,21.9],supportX:[89.9,91.41],openings:[{side:'west',min:16.84,max:18.04},{side:'east',min:21.0,max:22.25}]});
   s.join(d1.part,t.landings.at(-1).part,[89.9,7.02,17.44],'PL-801 tower / approach bridge');const d2=k.deck('PL-801 platform entry bridge',[91.25,21.0],[92,22.25],7.08,{columns:false,openings:[{side:'west',min:21,max:22.25},{side:'east',min:21,max:22.25}]});s.join(d1.part,d2.part,[91.25,7.02,21.6],'PL-801 approach / entry bridge');const base=parts.find(p=>p.name==='PL-801 service deck');s.join(d2.part,base,[92,7.02,21.6],'PL-801 entry / existing platform');register.links.push([t.landings.at(-1).record.id,d1.record.id],[d1.record.id,d2.record.id],[d2.record.id,'PL-801 service platform']);
   const d={id:'PL-801 service platform',partId:base.id,min:[92,7.08,20.85],max:[96.2,7.08,22.35],guardParts:[],gates:[],openings:[{side:'west',min:21,max:22.25},{side:'north',min:93.6,max:94.8}]};register.decks.push(d);k.guardDeck(d,base);
   const walk=parts.find(p=>p.name==='PL-801 feeder service walkway'),wd={id:'PL-801 feeder walkway',partId:walk.id,min:[93.6,7.08,22.35],max:[94.8,7.08,30.45],guardParts:[],gates:[],openings:[{side:'south',min:93.6,max:94.8},{side:'west',min:24.4,max:25.6,kind:'service-gate'},{side:'west',min:28.9,max:30.1,kind:'service-gate'}]};register.decks.push(wd);k.guardDeck(wd,walk);register.links.push([d.id,wd.id]);
  } else if(tag==='PL-161'){
   // Bridge beside the tower from its south top landing to the gate in the deck's south guardrail.
   const deck=optionDeck,[gx0,gx1]=deck.gate,top=t.landings.at(-1),z0=cfg.z,z1=deck.min[2],y=cfg.levels.at(-1);
   const bridge=k.deck('PL-161 stair bridge',[gx0,z0],[gx1,z1],y,{supportX:[gx0-.16,gx1+.16],supportZ:[z0-.16,z1-1.2],openings:[{side:'west',min:z0,max:z0+ACCESS_DESIGN.criteria.landingDepth},{side:'north',min:gx0,max:gx1}]});
   s.join(bridge.part,top.part,[gx0,y-.06,z0+.6],'PL-161 bridge / top landing');const south=parts.find(p=>p.id===deck.southPanel);s.join(bridge.part,south,[(gx0+gx1)/2,y-.015,z1],'PL-161 bridge / operating deck');
   register.decks.push({id:'PL-161 operating deck',partId:deck.southPanel,min:deck.min,max:deck.max,guardParts:deck.guardIds,openings:[{side:'south',min:gx0,max:gx1}],routeScreen:false,qualification:'Deck +4.4 m over D-164 (Option E). Plate-shifting, cloth-change and lifting envelopes are vendor data (hold J9).'});
   register.links.push([top.record.id,bridge.record.id],[bridge.record.id,'PL-161 operating deck']);
  } else {
   const d1=k.deck('PL-166 stair return bridge',[-14.3,-30],[-13.05,-21.75],5.9,{supportX:[-14.32,-12.89],openings:[{side:'west',min:-30,max:-28.8},{side:'north',min:-14.3,max:-13.05}]});const link=k.deck('PL-166 top landing link',[-14.5,-30],[-14.3,-28.8],5.9,{columns:false,openings:[{side:'west',min:-30,max:-28.8},{side:'east',min:-30,max:-28.8}]});s.join(link.part,d1.part,[-14.3,5.84,-29.4],'PL-166 landing / return bridge');s.join(link.part,t.landings.at(-1).part,[-14.3,5.84,-29.4],'PL-166 stair / return bridge');register.links.push([t.landings.at(-1).record.id,d1.record.id]);const floor=parts.find(p=>p.name==='PL-166 grating strip'),girder=parts.find(p=>p.name==='PL-166 edge girder'&&Math.abs(p.position.z+21.75)<.01);s.join(d1.part,girder,[-13.675,5.84,-21.75],'PL-166 bridge / filter platform');register.decks.push({id:'PL-166 filter platform',partId:floor.id,min:[-16.25,5.9,-21.75],max:[-12.6,5.9,-18.25],guardParts:parts.filter(p=>/^PL-166 (perimeter guardrail|guardrail post|toe plate)$/.test(p.name)).map(p=>p.id),openings:[{side:'south',min:-14.3,max:-13.05}],routeScreen:false,qualification:'Stair entry is connected; task routes around the filter footprint require vendor working-envelope review.'});register.links.push([d1.record.id,'PL-166 filter platform']);
  }
  t.partIds=parts.filter(p=>p.reactor===cfg.owner&&p.system==='frame').map(p=>p.id);h.structure.access.push({tag,equipment:cfg.served[0],deckElevation:cfg.levels.at(-1),stairs:true,guardrails:true,taskBased:true,accessRevision:ACCESS_DESIGN.revision,limits:ACCESS_DESIGN.qualification});
 }
 return register;
}
