// A screening water balance, not a hydraulic solution. All rates require independent verification.
export function captureScreen({volumeM3,durationSeconds,drainLps,extraM3=0,bufferM3}){
 if(![volumeM3,durationSeconds,drainLps,extraM3,bufferM3].every(Number.isFinite)||volumeM3<0||durationSeconds<=0||drainLps<0||extraM3<0||bufferM3<0)return {valid:false,qualified:false};
 const inflowLps=volumeM3*1000/durationSeconds,accumulationM3=Math.max(0,volumeM3-drainLps*durationSeconds/1000)+extraM3,blockedM3=volumeM3+extraM3;
 return {valid:true,inflowLps,accumulationM3,blockedM3,normalFits:accumulationM3<=bufferM3,blockedFits:blockedM3<=bufferM3,normalDeficitM3:Math.max(0,accumulationM3-bufferM3),blockedDeficitM3:Math.max(0,blockedM3-bufferM3),qualified:false,scope:'Constant inflow / assumed immediate drainage only. No inlet, pipe, solids, backwater, surge, spray or chemical-reaction validation.'};
}
export function mountCaptureReview(card,select,model){
 const el=document.createElement('details');el.innerHTML='<summary>Raised perimeter, support islands and drainage</summary><div id="capture-summary"></div><label for="capture-patch">Local capture floor</label><select id="capture-patch"></select><div id="capture-patch-detail"></div><details><summary>Spill accumulation scenario</summary><p class="small-note">Illustrative constant-rate balance. Enter independently verified event and drainage inputs; this calculator does not establish pipe capacity or compliance. Results are session-only.</p><div class="capture-inputs"><label>Released volume [m³]<input id="capture-volume" type="number" min="0" step="any"></label><label>Release duration [seconds]<input id="capture-time" type="number" min="0.01" step="any" placeholder="Required"></label><label>Assumed available drain flow [L/s]<input id="capture-flow" type="number" min="0" step="any" placeholder="Required · not yet verified"></label><label>Additional local water / drainback [m³]<input id="capture-extra" type="number" min="0" step="any" placeholder="Required · enter 0 only if justified"></label></div><div id="capture-result" role="status" aria-live="polite"></div></details><p class="small-note">Detail intent: chemically compatible lining continues over the curb and up foundation protection collars; coved floor junctions and compatible waterstops seal the barrier. Dry foundation islands preserve existing support load paths and anchor access. Full elevated replacement pedestals, split splash boots, reinforcement, movement, anchor protection and supplier chemical resistance remain engineering decisions.</p>';
 card.append(el);const q=id=>el.querySelector('#capture-'+id),patch=q('patch');
 function calc(){const c=model.containment.cells.find(c=>c.tag===select.value),p=c.captureDesign[Number(patch.value)];if(!p)return;const values=['volume','time','flow','extra'].map(id=>q(id).value.trim()===''?NaN:Number(q(id).value));const r=captureScreen({volumeM3:values[0],durationSeconds:values[1],drainLps:values[2],extraM3:values[3],bufferM3:p.geometricBufferM3});q('result').textContent=r.valid?`Assumed inflow: ${r.inflowLps.toFixed(1)} L/s. With entered drainage: ${r.accumulationM3.toFixed(2)} m³ accumulates — ${r.normalFits?'within geometric buffer':'EXCEEDS buffer by '+r.normalDeficitM3.toFixed(2)+' m³'}. Fully blocked drain: ${r.blockedM3.toFixed(2)} m³ — ${r.blockedFits?'within geometric buffer':'EXCEEDS buffer by '+r.blockedDeficitM3.toFixed(2)+' m³'}. Hydraulic verification remains OPEN.`:'Enter all four event inputs to screen accumulation and a fully blocked drain. Hydraulic verification: OPEN.';}
 function detail(){const c=model.containment.cells.find(c=>c.tag===select.value),p=c.captureDesign[Number(patch.value)];if(!p)return;q('patch-detail').textContent=`Crest ${(p.crestY*1000).toFixed(0)} mm above grade; provisional freeboard ${(p.freeboardM*1000).toFixed(0)} mm. Conservative local buffer ${p.geometricBufferM3.toFixed(2)} m³, before other equipment displacement. ${p.supportIslands.length} protected support foundations (${p.supportIslands.filter(s=>s.atBoundary).length} at the edge). Inlet geometry: ${p.inletClear?'clear of foundation islands':'REVIEW obstruction'}. Local buffer is not credited toward remote retention. ${p.geometricBufferM3<c.inventoryM3?'This floor alone cannot retain the selected full inventory.':''}`;q('patch-detail').className='small-note';calc();}
 function refresh(){const c=model.containment.cells.find(c=>c.tag===select.value);q('summary').textContent=`${c.captureDesign.length} raised capture floors → dedicated branches → one segregated retention trunk. Geometry checks cover continuous boundaries, foundation exclusion, connections and descending paths. Chemical compatibility, actual drain capacity, safe access and structural design remain open.`;q('summary').className='small-note';patch.replaceChildren();for(const p of c.captureDesign)patch.add(new Option('Floor '+(p.patchIndex+1)+(c.patches[p.patchIndex].pumpTag?' · pump tray':''),String(p.patchIndex)));q('volume').value=c.inventoryM3;q('time').value='';q('flow').value='';q('extra').value='';detail();}
 for(const id of['volume','time','flow','extra'])q(id).oninput=calc;patch.onchange=detail;select.addEventListener('change',refresh);document.getElementById('containment-block').addEventListener('change',refresh);refresh();
}
