import {processKit} from './process-kit.js';
import {structuralKit} from './structural-kit.js';
import {ventMechanical} from './vent-mechanical.js';
import {alignPipeEnds} from './pipe-end-alignment.js';
import {A4000_BASIS,A4000_IDS,A4000_CONSUMERS,A4000_ACCESS_ZONES} from './a4000-basis.js';
import {airScenario} from './a4000-logic.js';
export function buildCompressedAir(h){
 const k=processKit(h,.04),s=structuralKit(h),vm=ventMechanical(h),{T,parts,edges,routes,ports,terminals,EQUIPMENT,setContext,b,c,band,nozzle,terminal}=k,V=p=>new T.Vector3(...p);
 const first=parts.length,firstRoute=routes.length,connections=[],interfaces=[],vessels=[],drains=[],valveTags=[],supports=[];
 function L(points,label,service='Compressed air',meta={}){const points2=alignPipeEnds(points,meta.r||.04,edges,T),r=k.line(points2,meta.r||.04,label,service,meta.from||'',meta.to||'');Object.assign(r,{areaId:'A-4000',toArea:'A-4000',designStatus:'proposed',...meta});return r;}
 function root(p,at){h.structure.roots.push({part:p.id,local:V(at).sub(p.position).applyQuaternion(p.quaternion.clone().invert()).divide(p.scale).toArray(),elevation:0});return p;}
 function valve(a,z,tag,open=true,kind='isolation',r=.04){const start=parts.length,axis=V(z).sub(V(a)).normalize(),mid=V(a).add(V(z)).multiplyScalar(.5).toArray(),body=band(tag+' body','valve',r*1.8,r*.78,V(a).distanceTo(V(z)),mid,'bright',axis.toArray());k.passage(body,[a,z],tag+' passage',kind==='relief'?'Air relief':tag.includes('CD4001')?'Compressor condensate':'Compressed air',{internalTo:tag,barrierTag:tag});const disc=c(tag+' closure','internal',r*.78,.014,mid,'dark',axis.toArray());disc.closedQuaternion=disc.quaternion.clone();disc.openQuaternion=new T.Quaternion().setFromAxisAngle(Math.abs(axis.y)>.9?V([1,0,0]):V([0,1,0]),Math.PI/2).multiply(disc.closedQuaternion);disc.quaternion.copy(open?disc.openQuaternion:disc.closedQuaternion);disc.valveTag=tag;
  if(kind==='isolation'){const handle=b(tag+' lockable lever','valve',[.16,.025,.03],[mid[0],mid[1]+r*1.8+.025,mid[2]],'blue');c(tag+' stem','valve',.012,r*2,[mid[0],mid[1]+r,mid[2]]);}else if(kind==='automatic')b(tag+' electric fail-close actuator','valve',[.15,.12,.13],[mid[0],mid[1]+r*1.8+.06,mid[2]],'blue');else c(tag+' spring bonnet','valve',.055,.16,[mid[0],mid[1]+.12,mid[2]]);
  const v={tag,label:tag+' '+kind,reactor:body.reactor,a,b:z,type:kind,normalState:open?'open':'closed',airSystem:true,partIds:parts.slice(start).map(p=>p.id),discId:disc.id};h.valves.push(v);valveTags.push(tag);for(const p of parts.slice(start)){p.componentAssembly='air-valve-'+body.id;p.exploreRole=EQUIPMENT[p.reactor].tag===tag?'equipment':'context';}return z;}
 function closeEnd(at,axis,tag,r=.04,why='Positive blind; unresolved external destination'){const p=c(tag+' positive blind','head',r*1.6,.035,at,'dark',axis);terminal(at,tag+' · '+why);interfaces.push({tag,point:at,disposition:'blinded',reason:why,partId:p.id});return at;}
 function vessel(id,x,z,r,lo,hi,tag=EQUIPMENT[id].tag,material='steel'){
  setContext(id,tag+' pressure package');const start=parts.length,foundation=root(b(tag+' foundation','frame',[r*2+.25,.16,r*2+.25],[x,.08,z]),[x,0,z]);
  const floor=c(tag+' lower closure','head',r,.06,[x,lo,z],material),body=band(tag+' shell','shell',r,r-.035,hi-lo,[x,(hi+lo)/2,z],material),roof=c(tag+' upper closure','head',r,.06,[x,hi+.03,z],material);body.cut=roof.cut=floor.cut=true;
  for(const dx of[-r*.65,r*.65]){const leg=b(tag+' support leg','frame',[.08,lo-.16,.12],[x+dx,(lo+.16)/2,z]);s.join(foundation,leg,[x+dx,.16,z],tag+' leg anchor');s.join(leg,floor,[x+dx,lo,z],tag+' vessel seat');}s.join(floor,body,[x+r-.015,lo,z],tag+' lower shell joint');s.join(body,roof,[x+r-.015,hi,z],tag+' upper shell joint');s.load(body,tag);
  const v={id,tag,x,z,r,lo,hi,floor,body,roof,holes:[],partStart:start};
  v.port=(label,at,axis,rr=.04,service='Compressed air')=>{setContext(id,tag+' nozzles');const name=tag+' '+label,out=nozzle(at,axis,.16,name,rr),inside=V(at).addScaledVector(V(axis),-.045).toArray();v.holes.push({p:at,axis,r:rr,name});k.passage(body,[inside,[x,(lo+hi)/2,z]],name+' internal passage',service,{internalTo:tag});interfaces.push({tag:name,point:out,axis,disposition:'connected'});return out;};v.finish=()=>{vm.finishVessel(v);for(const p of parts.slice(start))if(p.reactor===id&&!p.exploreRole){p.exploreRole='equipment';p.componentAssembly='air-equipment-'+id;}return v;};vessels.push(v);return v;
 }
 function filter(id,x,z,tag=EQUIPMENT[id].tag){const v=vessel(id,x,z,.15,.72,1.6,tag);const input=v.port('inlet',[x-.15,1.35,z],[-1,0,0]),out=v.port('outlet',[x+.15,1.35,z],[1,0,0]);c(tag+' replaceable element','internal',.075,.6,[x,1.13,z],'inner');v.finish();k.instrument('PDIT-'+tag,input,'filter differential pressure',[0,1,0]);return {input,out,v};}
 const sourceEnds=[];
 for(const [i,z]of[1.65,4.3].entries()){
  const id=700+i,tag=EQUIPMENT[id].tag,x=-27.5;setContext(id,tag+' skid');const skid=root(b(tag+' anchored isolation skid','frame',[2.0,.2,1.6],[x,.1,z]),[x,0,z]);
  const airend=vessel(id,x,z,.26,.65,1.25,tag+' air end','blue'),input=airend.port('intake',[x,1,z+.26],[0,0,1],.06),out=airend.port('discharge',[x+.26,1,z],[1,0,0]);
  const drive=c(tag+' motor','pump',.23,.44,[x,1.66,z],'blue');band(tag+' guarded coupling','head',.14,.10,.18,[x,1.35,z],'dark');c(tag+' drive shaft','internal',.045,.37,[x,1.4,z],'bright');const mount=band(tag+' motor mounting spacer','frame',.21,.08,.13,[x,1.375,z],'bright');s.join(airend.roof,mount,[x+.16,1.31,z],tag+' mount / air end');s.join(mount,drive,[x+.16,1.44,z],tag+' drive mounting');airend.holes.push({p:[x,1.31,z],axis:[0,1,0],r:.045/.78,name:tag+' sealed shaft penetration'});band(tag+' pressure shaft seal','head',.075,.045,.055,[x,1.32,z],'gasket');s.load(drive,tag);airend.finish();
  for(const side of[-1,1]){const wall=b(tag+' removable acoustic panel','head',[.03,1.85,1.5],[x+side*.985,1.125,z],'blue');wall.cut=true;s.join(skid,wall,[x+side*.985,.2,z],tag+' enclosure');}b(tag+' top enclosure','head',[2,.03,1.5],[x,2.06,z],'blue');
  setContext(708,'F-4001 intake elements');const intake=[x-.55,1.25,z+.6];const f=band('F-4001 '+i+' inlet filter','shell',.14,.0468,.24,intake,'bright',[0,0,1]);f.cut=true;f.exploreRole='equipment';const fa=[intake[0],intake[1],intake[2]+.12],fb=[intake[0],intake[1],intake[2]-.12];k.passage(f,[fa,fb],'F-4001 intake '+i,'Compressed air',{internalTo:'F-4001'});terminal(fa,'F-4001 filtered atmospheric intake candidate');interfaces.push({tag:'F-4001 intake '+i,point:fa,disposition:'intentional intake',reason:'Clean-air siting and intake ducting subject to A-3000 dispersion review'});L([fb,[x,1.25,fb[2]],input],tag+' filtered inlet','Compressed air',{r:.06});
  setContext(id,tag+' discharge');const cooler=vessel(702+i,-25.65,z,.2,.7,1.45,EQUIPMENT[702+i].tag,'bright'),ci=cooler.port('inlet',[-25.85,1,z],[-1,0,0]),co=cooler.port('outlet',[-25.45,1,z],[1,0,0]);for(let j=0;j<8;j++)band(cooler.tag+' cooling fin','head',.25,.2,.016,[-25.65,.75+j*.08,z],'bright');cooler.finish();setContext(id,tag+' aftercooler feed');L([out,ci],tag+' to '+cooler.tag);
  const sep=vessel(704+i,-24.3,z,.16,.55,1.55),si=sep.port('inlet',[-24.46,1,z],[-1,0,0]),so=sep.port('outlet',[-24.14,1,z],[1,0,0]),sd=sep.port('auto drain',[-24.3,.52,z],[0,-1,0],.018,'Compressor condensate');sep.finish();setContext(702+i,'Aftercooler to separator');L([co,si],cooler.tag+' to '+sep.tag);drains.push({point:sd,tag:sep.tag});
  setContext(704+i,'Compressor branch protection');const checkA=[-23.84,1,z],checkB=[-23.64,1,z];L([so,checkA],tag+' outlet');valve(checkA,checkB,'NRV-4001'+(i?'B':'A'),true,'check');const va=[-23.44,1,z],vb=[-23.24,1,z];L([checkB,va],tag+' check outlet');valve(va,vb,'XV-4001'+(i?'B':'A'),i===0);sourceEnds.push(vb);
 }
 const wet=vessel(706,-22.25,1.65,.56,.5,2.75),wi=wet.port('inlet',[-22.81,1,1.65],[-1,0,0]),wo=wet.port('outlet',[-22.25,1.4,2.21],[0,0,1]),wd=wet.port('drain',[-22.25,.47,1.65],[0,-1,0],.018,'Compressor condensate'),wr=wet.port('relief',[-22.25,2.81,1.65],[0,1,0],.04);wet.finish();drains.push({point:wd,tag:'T-4001'});
 setContext(706,'Wet receiver feed');const wetHub=[-23.02,1,1.65];for(const p of sourceEnds)L([p,[-23.02,1,p[2]],wetHub],'Wet receiver branch '+p[2]);L([wetHub,wi],'Wet receiver common inlet');k.instrument('PIT-4001',wo,'wet receiver pressure');
 const pre=filter(712,-22.25,3.25);setContext(712,'Dryer inlet isolation');const vin=[-22.25,1.4,2.55],vout=[-22.25,1.4,2.8];L([wo,vin],'Wet receiver to dryer protection');valve(vin,vout,'XV-AD4001-IN');L([vout,[-22.65,1.4,2.8],[-22.65,1.35,3.25],pre.input],'PF-4001 feed');
 const dryIn=[-23.7,1.1,4.65],dryOut=[-23.7,2.5,5.55];
 setContext(707,'AD-4001 adsorption towers');const towers=[];
 for(const [j,x]of[-23.15,-22.05].entries()){
  const tower=vessel(707,x,4.65,.28,.6,2.7,'AD-4001 tower '+(j+1),'blue'),i=tower.port('feed',[x,.95,4.37],[0,0,-1]),o=tower.port('dry outlet',[x,2.45,4.93],[0,0,1]),purge=tower.port('regeneration',[x,1.2,4.93],[0,0,1],.02);c(tower.tag+' desiccant bed','internal',.21,1.35,[x,1.6,4.65],'inner');tower.finish();setContext(707,'AD-4001 changeover valves');const a=[x,.95,4.02],z=[x,.95,4.17];L([dryIn,[-23.7,.95,4.02],a],tower.tag+' feed manifold');valve(a,z,'XV-AD-T'+j,j===0,'automatic');L([z,i],tower.tag+' feed neck');L([o,[x,2.45,5.3],[x,2.5,5.55],dryOut],tower.tag+' dry collection');const pa=[x,1.2,5.15],pb=[x,1.2,5.35];L([purge,pa],tower.tag+' regeneration takeoff','Compressed air',{r:.02});valve(pa,pb,'XV-AD-PURGE'+j,false,'automatic',.02);c(tower.tag+' purge silencer','head',.055,.20,[x,1.2,5.45],'dark',[0,0,1]);k.passage(parts.at(-1),[pb,[x,1.2,5.55]],tower.tag+' silencer passage','Compressed air',{internalTo:'AD-4001'});terminal([x,1.2,5.55],tower.tag+' intentional silenced regeneration discharge');interfaces.push({tag:tower.tag+' purge',point:[x,1.2,5.55],disposition:'intentional discharge',reason:'Vendor cycle / pressure relief / purge demand HOLD'});towers.push(tower.tag);
 }
 // Tower sequencing is an explicit vendor package boundary; regeneration consumes qualified dry air.
 setContext(707,'AD-4001 regeneration balance');const balance=band('AD-4001 internal regeneration restrictor','internal',.035,.012,.16,[-22.6,2.5,5.55],'bright',[1,0,0]);balance.exploreRole='equipment';
 L([pre.out,[-21.8,1.35,3.25],[-21.8,1.1,3.8],[-23.7,1.1,3.8],dryIn],'PF-4001 to AD-4001');
 const f2=filter(709,-24.55,6.4),f3=filter(710,-25.55,6.4);
 setContext(707,'AD-4001 outlet isolation');const doa=[-23.7,2.5,5.8],dob=[-23.7,2.5,6.05];L([dryOut,doa],'AD-4001 outlet');valve(doa,dob,'XV-AD4001-OUT');L([dob,[-24.95,2.5,6.05],[-24.95,1.35,6.4],f2.input],'AD-4001 to F-4002');setContext(709,'Dry particulate protection');L([f2.out,[-24.1,1.35,6.4],[-24.1,2,6.4],[-25.95,2,6.4],[-25.95,1.35,6.4],f3.input],'F-4002 to F-4003');
 const clean=[-25.05,2.5,7.5],qa=[-24.7,2.5,7.5],qb=[-24.45,2.5,7.5];setContext(710,'Quality release and protected reserve');L([f3.out,[-25.05,1.35,6.4],[-25.05,1.35,7.5],clean,qa],'F-4003 monitored outlet','Instrument air');k.instrument('AIT-PDP4001',clean,'pressure dew point');valve(qa,qb,'XV-QA4001',true,'automatic');const n1=[-24.2,2.5,7.5],n2=[-24,2.5,7.5];L([qb,n1],'Qualified air release','Instrument air');valve(n1,n2,'NRV-IA4001',true,'check');
 const dry=vessel(713,-22.1,7,.48,.5,2.5),di=dry.port('fill',[-22.58,1.7,7],[-1,0,0]),dout=dry.port('distribution',[-22.1,1.3,7.48],[0,0,1]),dd=dry.port('drain',[-22.1,.47,7],[0,-1,0],.018,'Compressor condensate'),dr=dry.port('relief',[-22.1,2.56,7],[0,1,0],.04);dry.finish();drains.push({point:dd,tag:'T-4002'});
 setContext(713,'Protected dry receiver fill');L([n2,[-23,2.5,7.5],[-23,2.5,7],[-23,1.7,7],di],'Protected dry receiver inlet','Instrument air');k.instrument('PIT-4002',dout,'dry reserve pressure');
 function relief(id,input,tag,z){setContext(id,tag+' non-isolable relief');const top=[input[0],input[1]+.25,input[2]];valve(input,top,tag,false,'relief');const end=[input[0]-.9,4.9,z];L([top,[top[0],4.9,top[2]],end],tag+' safe discharge candidate','Air relief');terminal(end,tag+' intentional relief discharge · noise / backpressure / location HOLD');interfaces.push({tag,point:end,disposition:'intentional discharge',reason:'No isolating valve between receiver and PSV; sizing and discharge acceptance pending'});}
 relief(711,wr,'PSV-4001',.8);relief(719,dr,'PSV-4002',7);
 setContext(714,'HD-4001 priority distribution');const hd=band('HD-4001 distribution manifold','pipe',.075,.031,.4,[-22.1,2,8.8],'bright');hd.exploreRole='equipment';hd.componentAssembly='air-header-4001';const iaA=[-22.1,1.3,7.9],iaB=[-22.1,1.3,8.15],hub=[-22.1,5.3,8.8];L([dout,iaA],'Dry reserve outlet','Instrument air');valve(iaA,iaB,'XV-IA4001');L([iaB,[-22.1,1.3,8.8],hub],'HD-4001 riser','Instrument air');k.instrument('FIT-4001',iaB,'instrument-air demand');
 // A loop has explicit sectional isolations. Every takeoff is a top takeoff.
 const ring=[[-30.4,11.8,-9.8],[6.8,11.8,-9.8],[6.8,11.8,-26.5],[-9.4,11.8,-26.5],[-9.4,11.8,-9.8],[-30.4,11.8,-9.8]];
 L([hub,[-30.4,5.3,8.8],[-30.4,11.8,8.8],ring[0]],'A-4000 overhead air supply','Instrument air');
 for(let j=0;j<ring.length-1;j++){const a=ring[j],z=ring[j+1],dir=V(z).sub(V(a)).normalize(),v1=V(a).addScaledVector(dir,.4).toArray(),v2=V(a).addScaledVector(dir,.65).toArray();L([a,v1],'HD-4001 loop lead '+j,'Instrument air');valve(v1,v2,'XV-IA-SEC'+j);L([v2,z],'HD-4001 loop section '+j,'Instrument air');}
 for(const [s,owner]of[['A',1],['B',2],['C',54],['D',55]]){const tag='BL-IA201-'+s,p=ports.find(p=>p.id===tag);if(!p)throw Error('Missing existing instrument-air interface '+tag);p.role='interunit';for(let j=terminals.length-1;j>=0;j--)if(terminals[j].label===tag+' external battery limit')terminals.splice(j,1);
  setContext(714,tag+' dedicated supply');const z=s==='A'||s==='B'?-9.8:-26.5,x=p.point[0],a=[x,12.15,z],v1=[x,12.15,z+.4],v2=[x,12.15,z+.6];L([[x,11.8,z],a,v1],tag+' top takeoff','Instrument air');valve(v1,v2,'XV-IA201-'+s);const reduced=[x,12.15,z+.75];h.reducer(v2,reduced,.04,.018,tag+' branch reducer');Object.assign(routes.at(-1),{areaId:'A-4000',toArea:'A-200',service:'Instrument air',designStatus:'proposed'});const route=L([reduced,[x,12.15,p.point[2]], [x+.4,12.15,p.point[2]],[x+.4,p.point[1],p.point[2]],p.point],'A-4000 to '+tag,'Instrument air',{toArea:'A-200',to:tag,r:.018});connections.push({tag,toArea:'A-200',owner,routeIds:[route.id],partIds:route.partIds,point:p.point});interfaces.push({tag,point:p.point,disposition:'connected',reason:'Existing reactor air manifold; vendor actuator tubing beyond boundary'});
 }
 function outlet(id,tag,x,isService){setContext(id,tag+' controlled branch');const start=[-22.1,5.3,8.8],a=[x,1.3,8.3],z=[x,1.3,8.55];L([start,[x,5.3,8.8],[x,5.3,8.3],a],tag+' supply',isService?'Service air':'Process air');valve(a,z,isService?'XV-PA4001':'XV-PC4001',isService,'automatic');L([z,[x,1.3,8.8]],tag+' closed outlet',isService?'Service air':'Process air');closeEnd([x,1.3,8.8],[0,0,1],tag,.04,isService?'Service hose disconnected; close branch and prove zero pressure before coupling':'Process-contact requirements and users unresolved');const post=s.column(x-.35,8.8,1.35,tag+' support',.06);s.beam([x-.35,1.2,8.8],[x,1.2,8.8],.06,tag+' manifold bracket');}
 outlet(717,'BL-PA4000',-27.4,true);outlet(718,'BL-PC4000',-24,false);
 // Pressure reduction and drain sequencing reside in a closed vendor collection package.
 const collect=vessel(715,-27.5,6.6,.38,.25,1.3,'TK-CD4001','dark');
 for(const [j,d]of drains.entries()){setContext(715,'Isolated condensate transfer');const x=-27.72+j*.14,inlet=collect.port('inlet '+j,[x,1.36,6.6],[0,1,0],.018,'Compressor condensate'),a=d.point.map((v,i)=>i===1?v-.07:v),z=a.map((v,i)=>i===1?v-.10:v);L([d.point,a],d.tag+' condensate drain','Compressor condensate',{r:.018});valve(a,z,'AD-CD4001-'+j,false,'automatic',.018);const check=z.map((v,i)=>i===1?v-.07:v);valve(z,check,'NRV-CD4001-'+j,true,'check',.018);const lane=5.9+j*.07;L([check,[d.point[0],check[1],lane],[x,check[1],lane],[x,1.8,lane],[x,1.8,6.6],inlet],d.tag+' closed drain transfer','Compressor condensate',{r:.018});}
 const pumpout=collect.port('pump-out',[-27.5,.6,6.98],[0,0,1],.025,'Compressor condensate');closeEnd(pumpout,[0,0,1],'BL-CD4001',.025,'Closed recovery; pump / pressure reduction, materials and waste acceptance HOLD');const cv=collect.port('pressure-managed vent',[-27.5,1.36,6.6],[0,1,0],.02,'Air relief');L([cv,[-27.5,2.8,6.6],[-28.4,2.8,6.6]],'Collection vent treatment interface','Air relief',{r:.02});closeEnd([-28.4,2.8,6.6],[-1,0,0],'BL-CD4001-VENT',.02,'Unresolved treated vent; drain admission inhibited until package qualified');collect.finish();k.instrument('LSHH-CD4001',pumpout,'condensate high level');
 setContext(716,'CP-4000 accessible controls');const post=s.column(-25.5,7.5,1.45,'CP-4000',.07),panel=b('CP-4000 operator panel','valve',[.7,.55,.2],[-25.5,1.45,7.5],'blue');s.join(post.post,panel,[-25.5,1.45,7.5],'CP-4000 mounting');s.load(panel,'CP-4000');panel.serviceAccess={standing:[-25.5,0,8.3],method:'Grade controls; no live control connection',withdrawalAxis:[0,0,1]};panel.accessTag='CP-4000';
 // All added local geometry keeps explicit ownership. Long service lines are context.
 for(const p of parts.slice(first))if(!p.exploreRole)p.exploreRole=p.routeId?'context':'equipment';
 return {basis:A4000_BASIS,equipment:A4000_IDS,partIds:parts.slice(first).map(p=>p.id),routeIds:routes.slice(firstRoute).map(r=>r.id),connections,interfaces,consumers:structuredClone(A4000_CONSUMERS),accessZones:A4000_ACCESS_ZONES,valveTags,inspectionState:airScenario(),streamReconciliation:Array.from({length:13},(_,i)=>({pfdStream:String(4001+i),modelRoute:null,status:'Exact mapping HOLD pending source-drawing verification'})),vesselEnvelopes:vessels.map(v=>({tag:v.tag,id:v.id,x:v.x,z:v.z,radius:v.r,lo:v.lo,hi:v.hi})),dryReceiverGeometricM3:Math.PI*(.48-.035)**2*2,approvedCapacity:null,regeneration:{status:'Vendor cycle unresolved; no removal performance credited',towers},condensateAdmissionQualified:false};
}
