import {mountCaptureReview} from './capture-review.js';
import {containmentMetrics} from './containment-metrics.js';
export function containmentStages(model){
 if(!model.containment)return [];
 return [...new Set(model.containment.cells.map(c=>c.areaId))].map(areaId=>{const cells=model.containment.cells.filter(c=>c.areaId===areaId),equipment=[...cells.map(c=>c.id),...model.containment.emergencyStations.filter(e=>e.areaId===areaId).map(e=>e.id)];return {id:'containment-'+areaId,areaId,containment:true,train:'feed',title:'Spill capture and off-line retention',tags:cells.map(c=>c.tag).join(' · '),color:'#91adb7',equipment,context:[...equipment,...new Set(cells.flatMap(c=>c.owners))],routes:cells.flatMap(c=>c.routeIds.map(id=>model.routes.find(r=>r.id===id).label)),description:'Local capture branches join one dedicated trunk per zone. Compact civil blocks share construction and access while liquid-tight partitions preserve chemical segregation. Each compartment retains independent venting and normally blinded recovery.',inputs:[['Accidental release','Assigned equipment capture floors; chemical segregation retained']],outputs:[['Held spill','Dedicated retention cell; no normal process-wastewater connection']],note:'Proposed safety-layout features. Storage calculations and descending route geometry do not establish hydraulic capacity, spill chemistry, reaction protection or civil suitability. Inspect individual capacities under the process overview.'};});
}
export function mountContainment(model,{inspect,toggleBelow,review}){
 if(!model.containment)return;
 const parent=document.getElementById('process-overview'),card=document.createElement('details');if(!parent)return;
 card.className='method-note a400-basis-card';card.id='containment-tools';
 const title=document.createElement('summary');title.textContent='Spill containment · A-100–A-400 / A-1000';card.append(title);
 const metrics=containmentMetrics(model.containment);
 const metricsNote=document.createElement('p');metricsNote.className='small-note';metricsNote.textContent=metrics.civilBlocks+' civil blocks · '+metrics.liquidCompartments+' liquid compartments · '+metrics.remoteTrunks+' remote trunks. Construction grouping does not mix incompatible spills.';card.append(metricsNote);
 const note=document.createElement('p');note.className='small-note';note.textContent='Local capture → one trunk per zone → compact divided retention. T-402 / VSEP share their existing process-loop capture; CIP remains separate. BC design review is open.';card.append(note);
 const blockLabel=document.createElement('label');blockLabel.className='field-label';blockLabel.htmlFor='containment-block';blockLabel.textContent='CIVIL BLOCK';card.append(blockLabel);
 const blockSelect=document.createElement('select');blockSelect.id='containment-block';blockSelect.add(new Option('All civil blocks','all'));for(const b of model.containment.civilBlocks)blockSelect.add(new Option(b.tag+' · '+b.label+' · '+b.keys.length+' compartments',b.tag));card.append(blockSelect);
 const label=document.createElement('label');label.className='field-label';label.htmlFor='containment-cell';label.textContent='LIQUID COMPARTMENT → EQUIPMENT';card.append(label);
 const select=document.createElement('select');select.id='containment-cell';for(const c of model.containment.cells)select.add(new Option(c.areaId+' · '+c.tag+' · '+c.owners.map(o=>model.equipment[o].tag).join(' / '),c.tag));card.append(select);
 const table=document.createElement('table');table.setAttribute('aria-label','Selected containment sizing');card.append(table);
 const detail=document.createElement('p');detail.className='small-note';card.append(detail);
 const button=document.createElement('button');button.className='wide';button.textContent='Inspect capture and retention';button.type='button';button.onclick=()=>inspect(model.containment.cells.find(c=>c.tag===select.value));card.append(button);
 const below=document.createElement('button');below.id='containment-below';below.className='wide';below.type='button';below.textContent='Show below-grade layout';below.setAttribute('aria-pressed','false');below.onclick=()=>toggleBelow();card.append(below);
 const result=document.createElement('p');result.className='small-note';result.textContent=review.geometryPass?review.cells+' storage and connection checks passed for the selected layout assumptions. Engineering qualification remains open.':review.geometricFindings.length+' layout findings require review. See the configuration register.';card.append(result);
 const holds=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Design basis and open decisions';holds.append(summary);for(const hold of model.containment.holds){const p=document.createElement('p');p.className='small-note';p.textContent=hold;holds.append(p);}card.append(holds);
 const comparison=document.createElement('details'),comparisonTitle=document.createElement('summary');comparisonTitle.textContent='Revision history · containment layout';comparison.append(comparisonTitle);const comp=document.createElement('p');comp.className='small-note';comp.textContent='Current update: raised capture perimeters, protected support foundations and clear local inlets. Curb heights and hydraulic capacity remain provisional. Earlier consolidation: 37 separate receiver foundations → 16 common civil foundation blocks. 37 liquid compartments → 36; BND-402 is incorporated in BND-401 with the connected inventory counted once. Deepest retention floor: '+Math.abs(metrics.deepestFloorM).toFixed(2)+' m below grade (previous 5.35 m); deepest proposed foundation: '+Math.abs(metrics.deepestFoundationM).toFixed(2)+' m. Modeled spill-drain length: '+metrics.drainLengthM.toFixed(0)+' m (previous baseline approximately 3,390 m). Net geometric storage: '+metrics.netStorageM3.toFixed(1)+' m³. No quantified construction-cost saving or hydraulic safety credit is claimed.';comparison.append(comp);card.append(comparison);
 const regulatory=document.createElement('details'),regTitle=document.createElement('summary');regTitle.textContent='BC requirements and qualification';regulatory.append(regTitle);const regStatus=document.createElement('p');regStatus.className='small-note';regStatus.textContent=model.containment.bcBasis.complianceStatus;regulatory.append(regStatus);for(const ref of model.containment.bcBasis.references){const p=document.createElement('p');p.className='small-note';const a=document.createElement('a');a.href=ref.url;a.textContent=ref.title;a.target='_blank';a.rel='noopener noreferrer';p.append(a,document.createTextNode(' — '+ref.scope));regulatory.append(p);}const eye=document.createElement('p');eye.className='small-note';eye.textContent=model.containment.emergencyStations.length+' proposed emergency stations in this configuration. Open Emergency stations for current access findings and the B.C. design basis; installed performance is unverified.';regulatory.append(eye);card.append(regulatory);
 const render=()=>{const c=model.containment.cells.find(v=>v.tag===select.value);table.replaceChildren();for(const [name,value]of [['Civil construction block',c.civilBlock],['Selected release inventory',c.inventoryM3.toFixed(1)+' m³'],['Required including allowances',c.requiredM3.toFixed(1)+' m³'],['Net storage provided',c.netM3.toFixed(1)+' m³'],['Conditional BC waste-storage screen',c.bcWasteStorageScreenM3.toFixed(1)+' m³ · applicability unconfirmed'],['Remote drain trunks','1 · hydraulic capacity unqualified'],['Receiver internal footprint',c.width+' × '+c.length+' m'],['Maximum liquid level',c.storage.maximumLiquidY.toFixed(2)+' m relative to grade'],['Retention bottom',c.storage.min[1].toFixed(2)+' m relative to grade'],['Treatment connection','None · recovery normally blinded']]){const row=document.createElement('tr');for(const text of[name,value]){const td=document.createElement('td');td.textContent=text;row.append(td);}table.append(row);}detail.textContent=c.chemistry+'. '+c.inventories.map(v=>v.tag+': '+v.basis).join('; ')+'. Covers are in a separate service yard. The blue level marker indicates the proposed maximum liquid level, not actual contents.';};select.onchange=render;blockSelect.onchange=()=>{const previous=select.value;select.replaceChildren();for(const c of model.containment.cells.filter(c=>blockSelect.value==='all'||c.civilBlock===blockSelect.value))select.add(new Option(c.areaId+' · '+c.tag+' · '+c.owners.map(o=>model.equipment[o].tag).join(' / '),c.tag));if([...select.options].some(o=>o.value===previous))select.value=previous;render();};render();parent.prepend(card);mountCaptureReview(card,select,model);
}
