import {processKit} from './process-kit.js';
import {structuralKit} from './structural-kit.js';
import {ventMechanical} from './vent-mechanical.js';
const eq=(tag,label,x,z,group,extra={})=>({tag,label,x,z,labelY:5,areaId:'A-3000',subArea:group,primaryOperation:'vgtreat',designStatus:'proposed',geometryBasis:'exhaust-42',geometryStatus:'Proposed package envelope; vendor internals, duties and ratings HOLD',reviewNote:'Independent service. No treatment performance or operating release is inferred. Source composition, pressure control, residual emissions and permit basis require engineering review.',...extra});
export const EXHAUST_EQUIPMENT={
 620:eq('AB-3701','A-700 thermal abatement candidate',98.5,46.4,'Thermal satellite'),621:eq('ST-3702','A-700 independent outlet · permit HOLD',102,46.4,'Thermal satellite',{labelY:9}),
 622:eq('CP-3700','A-700 treatment permissive station',95.7,46.4,'Thermal satellite',{labelY:2}),
 630:eq('AB-3801','A-800 specialist reactive-gas package',107.4,46.4,'Reactive satellite'),631:eq('ST-3802','A-800 independent outlet · permit HOLD',110.9,46.4,'Reactive satellite',{labelY:9}),
 632:eq('CP-3800','A-800 treatment permissive station',104.6,46.4,'Reactive satellite',{labelY:2}),
 640:eq('DC-3811','Dry inventory vent package · selection HOLD',113.1,46.4,'Dry inventory vents'),
 641:eq('DC-3812','KBH4 feeder vent package · selection HOLD',115.2,46.4,'Reactive feeder vent')
};
export const EXHAUST_GROUPS=[
 {id:'wet',name:'Compatible wet-acid vents',equipment:[600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616],sources:['Candidate wet source register'],chemistry:'Candidate acid gases / aerosols; qualify each source',combustion:'Exclude reactive / combustible sources pending assessment',pressure:'Controlled header draft within vessel vacuum limits',mechanism:'Bulk separation → alkaline absorption → candidate fine-mist polishing',status:'Proposed wet train; qualification HOLD'},
 {id:'dryer',name:'A-600 drying exhaust',equipment:[71,74,75,76],sources:['BL-EX601'],chemistry:'Moist drying gas and product fines',combustion:'Dust and drying-gas assessment required',pressure:'Existing FN-601 / SC-601 pressure budget',mechanism:'Retain existing powder recovery and SC-601 polishing',status:'Independent discharge; emission verification HOLD'},
 {id:'thermal',name:'A-700 thermal off-gas',equipment:[620,621,622],sources:['BL-OFF701'],chemistry:'CO / CO2 / moisture / particulate envelope to measure',combustion:'Combustible concentrations and batch peaks HOLD',pressure:'FN-701 coordination; furnace pressure sign remains unresolved',mechanism:'Existing E-701 / KO-701 → AB-3701 thermal-oxidation candidate → dedicated outlet',status:'Candidate package built for layout; technology and duty HOLD'},
 {id:'reactive',name:'A-800 reactive thermal off-gas',equipment:[630,631,632],sources:['BL-OFF801'],chemistry:'H2 and boron species / particulate to characterize',combustion:'Oxygen ingress, ignition and residual reactivity assessment',pressure:'Independent FN-801 / package pressure coordination',mechanism:'Existing E-801 → specialist AB-3801 envelope; destruction and polishing selection HOLD',status:'No wet treatment, catalyst or abatement performance assumed'},
 {id:'inventory',name:'A-800 dry inventory breathing',equipment:[640],sources:['BL-VENT801'],chemistry:'Feeder / mixer displacement and purge gas; qualify every branch',combustion:'Dry dust and reactive inventory compatibility HOLD',pressure:'Independent pressure / purge acceptance',mechanism:'Closed dry collection / abatement package envelope; media and final gas treatment HOLD',status:'Independent package; outlet destination unresolved'},
 {id:'feeder',name:'F-802 separate KBH4 feeder exhaust',equipment:[641],sources:['BL-EX802'],chemistry:'Potential reactive reagent dust and H2',combustion:'Water-reactive dust: no generic water washing or air pulse assumed',pressure:'Independent collection and backpressure qualification',mechanism:'Specialist dry containment / abatement package envelope',status:'Independent package; outlet destination unresolved'},
 {id:'relief',name:'Emergency relief',equipment:[83,109],sources:['BL-RV701','BL-REL801'],chemistry:'Credible emergency loads, not normal vent duty',combustion:'Relief-specific dispersion / reaction / ignition study',pressure:'No normal-treatment or isolation credit',mechanism:'Dedicated assessed relief destinations remain open',status:'No connection to wet train or proposed normal-treatment modules'}
];
export const EXHAUST_ACCESS=[{id:'WALK-EXHAUST-SAT',kind:'pedestrian',areas:['A-3000'],min:[94,.02,44.6],max:[118,2.32,45.5],note:'Front service approach to east spine; proposed clearance, vendor access HOLD'}];
export function buildExhaustGroups(h){const k=processKit(h),s=structuralKit(h),mech=ventMechanical(h),{T,parts,ports,terminals,setContext,b,c,band}=h,connections=[],interfaces=[],start=parts.length;
 function root(p,at){h.structure.roots.push({part:p.id,local:new T.Vector3(...at).sub(p.position).applyQuaternion(p.quaternion.clone().invert()).divide(p.scale).toArray(),elevation:0});return p;}
 function line(p,r,label,service,group){const q=k.line(p,r,label,service,'','');Object.assign(q,{areaId:'A-3000',toArea:'A-3000',exhaustGroup:group,designStatus:'proposed',qualification:'Independent proposed route; process release HOLD'});return q;}
 function source(tag,group){const p=ports.find(p=>p.id===tag);if(!p)throw Error('Missing source '+tag);p.role='interunit';for(let i=terminals.length-1;i>=0;i--)if(terminals[i].label===tag+' external battery limit')terminals.splice(i,1);for(const unit of[h.furnace,h.doping])for(const q of unit.boundaries||[])if(q.tag===tag){q.destination='Dedicated '+group+' package in A-3000 satellite; qualification HOLD';q.kind='interunit';}return p;}
 function module(id,stackId,controlId,group,sourceTag,lane){const e=h.EQUIPMENT[id],{x,z,tag}=e;setContext(id,tag+' isolated package');const base=root(b(tag+' foundation','frame',[4.1,.20,1.8],[x,.10,z]),[x,0,z]);const body=band(tag+' enclosed vendor package envelope','shell',.65,.615,3,[x,2.6,z],'steel',[1,0,0]);body.cut=true;s.load(body,tag+' package');for(const dx of[-.85,.85]){const foot=b(tag+' saddle pedestal','frame',[.45,1.75,.5],[x+dx,1.075,z]);s.join(base,foot,[x+dx,.2,z],tag+' pedestal / base');s.join(foot,body,[x+dx,1.95,z],tag+' saddle contact');}
  for(const side of[-1,1]){const end=band(tag+' sealed end plate','head',.65,.16,.04,[x+side*1.5,2.6,z],'steel',[1,0,0]);s.join(body,end,[x+side*1.49,2.6,z+.63],tag+' end plate / shell');}
  const inlet=mech.ductNozzle([x-1.5,2.6,z],[-1,0,0],.25,tag+' inlet',.16),outlet=mech.ductNozzle([x+1.5,2.6,z],[1,0,0],.25,tag+' outlet',.16);
  const pass=k.passage(body,[[x-1.455,2.6,z],[x+1.455,2.6,z]],tag+' unqualified treatment envelope','Thermal off-gas',{transport:'vendor treatment envelope — mechanism HOLD'});pass.exhaustGroup=group;pass.qualified=false;
  if(group==='thermal')band(tag+' insulation / refractory allowance','internal',.61,.51,2.9,[x,2.6,z],'lining',[1,0,0]);
  const src=source(sourceTag,group),r=src.radius,feedEnd=r===.16?inlet:[inlet[0]-.18,inlet[1],inlet[2]];const rr=line([src.point,[src.point[0]+.5,src.point[1],src.point[2]],[src.point[0]+.5,lane,src.point[2]],[src.point[0]+.5,lane,44.4],[x-2.2,lane,44.4],[x-2.2,3.1,44.4],[x-2.2,3.1,z],[x-2.2,2.6,z],feedEnd],r,sourceTag+' to '+tag,group==='thermal'?'Thermal off-gas':'Reactive thermal off-gas',group);if(r!==.16){h.reducer(feedEnd,inlet,r,.16,tag+' inlet size transition');Object.assign(h.routes.at(-1),{exhaustGroup:group,areaId:'A-3000',service:'Reactive thermal off-gas'});}
  connections.push({source:sourceTag,group,route:rr.id,destination:tag,qualified:false});interfaces.push({equipment:tag,name:'package inlet',status:'connected',point:inlet},{equipment:tag,name:'package outlet',status:'connected',point:outlet});
  setContext(stackId,'Independent '+group+' outlet');const st=h.EQUIPMENT[stackId],stack=band(st.tag+' outlet barrel','shell',.18,.16,8.5,[st.x,4.45,z],'steel');stack.cut=true;const pad=root(c(st.tag+' foundation','frame',.35,.2,[st.x,.1,z],'dark'),[st.x,0,z]);s.join(pad,stack,[st.x+.17,.2,z],st.tag+' stack base');s.load(stack,st.tag);const hole=mech.shell(st.tag+' actual inlet aperture',st.x,z,.18,.2,8.7,[{p:[st.x-.18,2.6,z],axis:[-1,0,0],r:.16}]);hole.geometry.applyMatrix4(new T.Matrix4().compose(stack.position,stack.quaternion,stack.scale).invert().multiply(new T.Matrix4().compose(hole.position,hole.quaternion,hole.scale)));stack.geometry=hole.geometry;parts.pop();const stIn=mech.ductNozzle([st.x-.18,2.6,z],[-1,0,0],.18,st.tag+' inlet',.16);line([outlet,stIn],.16,tag+' to '+st.tag,'Treated exhaust',group);k.passage(stack,[[st.x-.135,2.6,z],[st.x,2.6,z],[st.x,8.7,z]],st.tag+' proposed discharge','Treated exhaust');h.terminal([st.x,8.7,z],st.tag+' intentional outlet; permit, sampling and dispersion HOLD');interfaces.push({equipment:st.tag,name:'independent outlet',point:[st.x,8.7,z],status:'intentional discharge',note:'Emission performance, stack height and permit unqualified'});
  setContext(controlId,group+' permissive station');const cp=h.EQUIPMENT[controlId],col=s.column(cp.x,cp.z,1.4,cp.tag,.08),panel=b(cp.tag+' display','valve',[.65,.5,.12],[cp.x,1.4,cp.z],'blue');s.join(col.post,panel,[cp.x,1.4,cp.z],cp.tag+' mount');s.load(panel,cp.tag);panel.accessTag=cp.tag;panel.serviceAccess={standing:[cp.x,0,45.1],method:'Grade status indication; approved I/O and cause-and-effect HOLD',withdrawalAxis:[0,0,-1]};
 }
 const allocationStart=parts.length;setContext(620,'A-3000 satellite floor allocation');for(const z of[44.6,47.5])b('A-3000 satellite allocation edge','frame',[23,.018,.025],[105.5,.05,z],'blue');for(const x of[94,117])b('A-3000 satellite allocation edge','frame',[.025,.018,2.9],[x,.05,46.05],'blue');for(const p of parts.slice(allocationStart)){p.floorAllocationLegacy=true;p.exploreRole='context';}
 module(620,621,622,'thermal','BL-OFF701',12.2);module(630,631,632,'reactive','BL-OFF801',12.8);
 for(const [id,tag,group,lane] of [[640,'BL-VENT801','inventory',18.1],[641,'BL-EX802','feeder',18.7]]){const e=h.EQUIPMENT[id],{x,z}=e;setContext(id,e.tag+' independent dry package');const base=root(c(e.tag+' foundation','frame',.53,.2,[x,.1,z],'dark'),[x,0,z]),body=band(e.tag+' closed package envelope','shell',.40,.365,2.5,[x,1.7,z]);body.cut=true;const skirt=band(e.tag+' support skirt','frame',.4,.365,.25,[x,.325,z]);s.join(base,skirt,[x+.38,.2,z],e.tag+' base / skirt');s.join(skirt,body,[x+.38,.45,z],e.tag+' skirt / shell');s.load(body,e.tag);c(e.tag+' sealed bottom','head',.4,.04,[x,.45,z]);const top=mech.disk(e.tag+' sealed roof with nozzles',x,2.95,z,.4,.04,[{p:[x-.15,2.95,z],r:.07},{p:[x+.15,2.95,z],r:.07}]);const input=h.nozzle([x-.15,2.99,z],[0,1,0],.2,e.tag+' inlet',.07),output=h.nozzle([x+.15,2.99,z],[0,1,0],.2,e.tag+' outlet',.07);const src=source(tag,group),feedEnd=[input[0],input[1]+.18,input[2]],r=line([src.point,[116.5,src.point[1],src.point[2]],[116.5,lane,src.point[2]],[116.5,lane,group==='feeder'?46.9:46.4],[x-.15,lane,group==='feeder'?46.9:z],...[...(group==='feeder'?[[x-.15,4.3,46.9],[x-.15,4.3,z]]:[])],feedEnd],src.radius,tag+' to '+e.tag,'Dry reactive exhaust',group);h.reducer(feedEnd,input,src.radius,.07,e.tag+' inlet size transition');Object.assign(h.routes.at(-1),{exhaustGroup:group,areaId:'A-3000',service:'Dry reactive exhaust'});k.passage(body,[[x-.15,2.945,z],[x-.15,1.7,z],[x+.15,2.945,z]],e.tag+' unqualified dry treatment envelope','Dry reactive exhaust');k.boundary('BL-'+e.tag+'-OUT',output,[0,1,0],.07,'Dry reactive exhaust','Specialist gas abatement and safe disposal unresolved; no room discharge');h.capped([output[0],output[1]+.36,output[2]],[0,1,0],.07,e.tag+' unresolved outlet maintenance blind');interfaces.push({equipment:e.tag,name:'specialist outlet',point:[output[0],output[1]+.36,output[2]],status:'unresolved',closure:'positive blind',note:'Planning configuration only. Source operation prohibited until downstream abatement is designed and connected.'});connections.push({source:tag,group,route:r.id,destination:e.tag,qualified:false});}
 return {allocations:[{name:'A-3000 exhaust satellites',rect:[94,44.6,117,47.5],widthM:23,depthM:2.9,grossM2:66.7}],revision:'exhaust-42',equipment:Object.keys(EXHAUST_EQUIPMENT).map(Number),partIds:parts.slice(start).map(p=>p.id),groups:EXHAUST_GROUPS,connections,interfaces,processRelease:false,qualified:false,note:'Independent proposed treatment packages; no common wet/dry/reactive header. Geometry is a layout study, not permission to operate. BL-VENT801 is dry inventory breathing; BL-REL801 is emergency relief.'};
}
