import {createPathIndex} from './path-index.js';
import * as T from './vendor/three.module.js';
const V=a=>new T.Vector3(...a), EPS=1e-5;
export const AXES={x:new T.Vector3(1,0,0),y:new T.Vector3(0,1,0),z:new T.Vector3(0,0,1)};
export const VIEW_DIRECTIONS={iso:new T.Vector3(1,1,1).normalize(),front:new T.Vector3(0,0,1),side:new T.Vector3(1,0,0),top:new T.Vector3(0,1,0),perspective:new T.Vector3(.29,.18,1).normalize()};
export function fitOrthographic(bounds,direction,aspect,margin=1.2){const upHint=Math.abs(direction.y)>.999?new T.Vector3(0,0,-1):new T.Vector3(0,1,0),right=new T.Vector3().crossVectors(upHint,direction).normalize(),up=new T.Vector3().crossVectors(direction,right).normalize(),center=bounds.getCenter(new T.Vector3());let w=0,h=0,depth=0;for(const x of[bounds.min.x,bounds.max.x])for(const y of[bounds.min.y,bounds.max.y])for(const z of[bounds.min.z,bounds.max.z]){const p=new T.Vector3(x,y,z).sub(center);w=Math.max(w,Math.abs(p.dot(right)));h=Math.max(h,Math.abs(p.dot(up)));depth=Math.max(depth,Math.abs(p.dot(direction)))}const half=Math.max(h,w/aspect,.08)*margin;return{center,up:upHint,halfHeight:half,halfWidth:half*aspect,distance:Math.max(10,depth*2+5)}}
export function makeSectionPlane(bounds,axis,fraction,flip=false){const value=T.MathUtils.lerp(bounds.min[axis],bounds.max[axis],fraction),normal=AXES[axis].clone().multiplyScalar(flip?1:-1);return new T.Plane(normal,-normal[axis]*value)}
function pointPathDistance(point,path){let distance=Infinity;const v=V(point);for(let i=1;i<path.length;i++)distance=Math.min(distance,v.distanceTo(new T.Line3(V(path[i-1]),V(path[i])).closestPointToPoint(v,true,new T.Vector3())));return distance}
export function conduitsTouch(a,b,tolerance=EPS){return[a.a,a.b].some(p=>pointPathDistance(p,b.path||[b.a,b.b])<tolerance)||[b.a,b.b].some(p=>pointPathDistance(p,a.path||[a.a,a.b])<tolerance)}
export function buildConnectionGraph(edges){const adjacency=edges.map(()=>new Set()),index=createPathIndex(edges);for(let i=0;i<edges.length;i++)for(const p of[edges[i].a,edges[i].b])for(const j of index.at(p,EPS))if(i!==j){adjacency[i].add(j);adjacency[j].add(i);}return adjacency.map(neighbors=>new Set([...neighbors].sort((a,b)=>a-b)));}
export function traceRoute(model,routeId,connected=false,adjacency=buildConnectionGraph(model.edges)){const route=model.routes.find(r=>r.id===routeId);if(!route)return{partIds:new Set(),edges:[],routeCount:0};const indices=new Set(route.edgeIndices),queue=[...indices];if(connected)for(let q=0;q<queue.length;q++)for(const j of adjacency[queue[q]])if(!indices.has(j)){indices.add(j);queue.push(j)}const reached=new Set([...indices].map(i=>model.edges[i].routeId).filter(Boolean)),partIds=new Set(route.partIds);for(const i of indices)partIds.add(model.edges[i].part);for(const r of model.routes)if(reached.has(r.id))for(const id of r.partIds)partIds.add(id);return{partIds,edges:[...indices].map(i=>model.edges[i]),routeCount:reached.size}}
export function componentGroups(parts){const groups=new Map();for(const p of parts){const key=p.reactor+'|'+p.assembly;if(!groups.has(key))groups.set(key,{key,reactor:p.reactor,label:p.assembly,parts:[]});groups.get(key).parts.push(p)}return[...groups.values()]}
// Closest distance between two finite line segments, including parallel/degenerate cases.
export function segmentDistance(a0,a1,b0,b1){const p=V(a0),q=V(b0),u=V(a1).sub(p),v=V(b1).sub(q),w=p.clone().sub(q);const a=u.dot(u),b=u.dot(v),c=v.dot(v),d=u.dot(w),e=v.dot(w);if(a<1e-14)return pointPathDistance(a0,[b0,b1]);if(c<1e-14)return pointPathDistance(b0,[a0,a1]);const den=a*c-b*b;let sn,sd=den,tn,td=den;if(den<1e-14){sn=0;sd=1;tn=e;td=c}else{sn=b*e-c*d;tn=a*e-b*d;if(sn<0){sn=0;tn=e;td=c}else if(sn>sd){sn=sd;tn=e+b;td=c}}if(tn<0){tn=0;if(-d<0)sn=0;else if(-d>a)sn=sd;else{sn=-d;sd=a}}else if(tn>td){tn=td;if(-d+b<0)sn=0;else if(-d+b>a)sn=sd;else{sn=-d+b;sd=a}}const sc=Math.abs(sn)<1e-14?0:sn/sd,tc=Math.abs(tn)<1e-14?0:tn/td;return w.addScaledVector(u,sc).addScaledVector(v,-tc).length()}
function pathDistance(a,b){let d=Infinity;for(let i=1;i<a.length;i++)for(let j=1;j<b.length;j++)d=Math.min(d,segmentDistance(a[i-1],a[i],b[j-1],b[j]));return d}
function bodyPointDistance(point,body){if(body.kind==='deck-with-holes')return Math.min(...body.solids.map(r=>Math.hypot(...point.toArray().map((v,i)=>Math.max(r.min[i]-v,0,v-r.max[i])))));const p=point.clone().sub(V(body.position)).applyQuaternion(new T.Quaternion(...body.quaternion).invert());if(body.kind==='cylinder'){const radial=Math.max(0,Math.hypot(p.x,p.z)-body.radius),vertical=Math.max(0,Math.abs(p.y)-body.height/2);return Math.hypot(radial,vertical)}const h=V(body.size).multiplyScalar(.5);return new T.Vector3(Math.max(0,Math.abs(p.x)-h.x),Math.max(0,Math.abs(p.y)-h.y),Math.max(0,Math.abs(p.z)-h.z)).length()}
export function pathBodyDistance(path,body){let closest=Infinity;for(let i=1;i<path.length;i++){const a=V(path[i-1]),d=V(path[i]).sub(a);let lo=0,hi=1;for(let n=0;n<28;n++){const x=lo+(hi-lo)/3,y=hi-(hi-lo)/3;if(bodyPointDistance(a.clone().addScaledVector(d,x),body)<bodyPointDistance(a.clone().addScaledVector(d,y),body))hi=y;else lo=x}closest=Math.min(closest,bodyPointDistance(a,body),bodyPointDistance(V(path[i]),body),bodyPointDistance(a.addScaledVector(d,(lo+hi)/2),body))}return closest}
function boundsOfPath(path,r){const b=new T.Box3().setFromPoints(path.map(V));return b.expandByScalar(r)}
export function makeScreeningData(model){const partById=new Map(model.parts.map(p=>[p.id,p])),bodies=[];for(const p of model.parts){if(p.screenBody){p.geometry.computeBoundingBox();const bb=p.geometry.boundingBox.clone().applyMatrix4(new T.Matrix4().compose(p.position,p.quaternion,p.scale));bodies.push({id:p.id,label:p.name,reactor:p.reactor,assembly:p.assembly,system:p.system,...p.screenBody,bounds:[bb.min.toArray(),bb.max.toArray()]});continue;}if(!['frame','pump','valve'].includes(p.system))continue;if(p.system==='valve'&&!p.name.endsWith(' · body'))continue;if(p.system==='frame'&&/Pipe support|Pipe saddle|attachment/i.test(p.name))continue;if(!['CylinderGeometry','ExtrudeGeometry','BoxGeometry'].includes(p.geometry.type))continue;const body={supportFor:p.supportFor||[],id:p.id,label:p.name,reactor:p.reactor,assembly:p.assembly,system:p.system,position:p.position.toArray(),quaternion:p.quaternion.toArray(),kind:p.geometry.type==='CylinderGeometry'?'cylinder':'box',radius:p.scale.x,height:p.scale.y,size:p.scale.toArray()};p.geometry.computeBoundingBox();const bb=p.geometry.boundingBox.clone().applyMatrix4(new T.Matrix4().compose(p.position,p.quaternion,p.scale));body.bounds=[bb.min.toArray(),bb.max.toArray()];bodies.push(body)}const vessels=Object.entries(model.equipment).filter(([,e])=>e.radius).map(([key,e])=>{const reactor=Number(key),ids=model.parts.filter(p=>p.reactor===reactor&&p.system==='shell').map(p=>p.id);return{id:ids[0],relatedIds:ids,label:`${e.tag} vessel barrel envelope`,reactor,assembly:'Vessel pressure boundary',system:'shell',position:[e.x,(e.bottom+e.top)/2,e.z||0],quaternion:[0,0,0,1],kind:'cylinder',radius:e.radius,height:e.top-e.bottom,bounds:[[e.x-e.radius,e.bottom,(e.z||0)-e.radius],[e.x+e.radius,e.top,(e.z||0)+e.radius]]}});return{edges:model.edges.map(e=>{const p=partById.get(e.part);if(!p)return {...e};p.geometry.computeBoundingBox();const bb=p.geometry.boundingBox.clone().applyMatrix4(new T.Matrix4().compose(p.position,p.quaternion,p.scale));return {...e,meshBounds:[bb.min.toArray(),bb.max.toArray()]};}),terminals:model.terminals,bodies:[...bodies,...vessels]}}
export function screenInterferences(data,{scope='all',tolerance=.008}={}){const edges=data.edges,bodies=data.bodies,adjacency=buildConnectionGraph(data.edges),nearConnection=(i,j)=>adjacency[i].has(j)||[...adjacency[i]].some(k=>adjacency[k].has(j)),allBounds=edges.map(e=>boundsOfPath(e.path,e.radius)),candidates=[],pairs=new Set();let comparisons=0;const inScope=(a,b)=>scope==='all'||String(a.reactor)===String(scope)||String(b.reactor)===String(scope);
function record(a,b,kind,depth){const key=[a.part||a.id,b.part||b.id].sort((x,y)=>x-y).join(':');if(pairs.has(key))return;pairs.add(key);candidates.push({id:'CHECK-'+String(candidates.length+1).padStart(3,'0'),a:a.part||a.id,b:b.part||b.id,relatedB:b.relatedIds||[],labelA:a.name||a.label,labelB:b.name||b.label,reactorA:a.reactor,reactorB:b.reactor,kind,depth,reason:kind==='Pipe / pipe'?'Swept pipe volumes overlap away from a shared connection.':'Pipe volume enters an approximate equipment or support envelope.'})}
for(let i=0;i<edges.length;i++)for(let j=i+1;j<edges.length;j++){const a=edges[i],b=edges[j];if(a.transport==='bulk solids'||b.transport==='bulk solids'||a.screenAsPipe===false||b.screenAsPipe===false||!inScope(a,b)||a.part===b.part||!allBounds[i].intersectsBox(allBounds[j])||nearConnection(i,j))continue;comparisons++;const depth=a.radius+b.radius-pathDistance(a.path,b.path);if(depth>tolerance){const finiteOverlap=!a.meshBounds||!b.meshBounds||new T.Box3(V(a.meshBounds[0]),V(a.meshBounds[1])).intersectsBox(new T.Box3(V(b.meshBounds[0]),V(b.meshBounds[1])));if(finiteOverlap)record(a,b,'Pipe / pipe',depth);}}
const bodyBounds=bodies.map(b=>new T.Box3(V(b.bounds[0]),V(b.bounds[1])));
for(let i=0;i<edges.length;i++){const e=edges[i];if(e.transport==='bulk solids'||e.screenAsPipe===false)continue;for(let j=0;j<bodies.length;j++){const b=bodies[j];if(!inScope(e,b)||e.part===b.id||e.matesBody===b.id||b.supportFor?.includes(e.part)||!allBounds[i].intersectsBox(bodyBounds[j]))continue;
 // Known endpoint penetrations and connected valve bodies are intentional contacts.
 const expected=data.terminals.some(t=>t.reactor===b.reactor&&[e.a,e.b].some(p=>V(p).distanceTo(V(t.point))<EPS)&&((b.system==='shell'&&/vessel penetration/.test(t.label))||(b.assembly==='Recirculation pump'&&/Pump .* chamber/.test(t.label))||(b.system==='frame'&&/Skid cable entry|Handle attachment/.test(t.label))||(b.assembly==='Bottom drive'&&/Motor cable entry/.test(t.label))));
 if((b.system==='shell'&&e.internalTo===b.reactor)||expected||edges.some((other,k)=>other.part===b.id&&nearConnection(i,k)))continue;comparisons++;const depth=e.radius-pathBodyDistance(e.path,b);if(depth>tolerance)record(e,b,b.system==='shell'?'Pipe / vessel':'Pipe / equipment',depth);
}}
candidates.sort((a,b)=>b.depth-a.depth);return{candidates,comparisons,scope,pipeCount:edges.length,bodyCount:bodies.length,tolerance,method:'Swept pipe volumes with finite mesh bounds against pipe paths, oriented boxes and cylinders, including the screw casing. Bulk material trajectories are traced inside their equipment envelopes. Hardware, seals, designated pipe supports adjacent route segments and known mating connections excluded. Approximate screening; review each candidate.'}}
