import {drainComparison} from './drain-review.js';
export const register=[
{id:'L01',decision:'Keep',item:'Emergency equipment, containment and protected access',function:'Limit exposure and provide access to emergency response.',action:'Retain pending hazard-specific engineering assessment.',evidence:'Hazard inventory, exposure locations, access checks and qualified review.',status:'Required function retained'},
{id:'L02',decision:'Simplify',item:'Repeated Browse instructions',function:'Explain navigation without obscuring equipment.',action:'Move detailed walking instructions into expandable help.',evidence:'Navigation buttons and short context remain available.',status:'Implemented in v114'},
{id:'L03',decision:'Remove',item:'Repeated stationary map redraws',function:'Show current walking position and direction.',action:'Skip repaint when position, direction, level and map size are unchanged.',evidence:'Dynamic camera/movement and map reopening must still update.',status:'Implemented in v114'},
{id:'L04',decision:'Simplify',item:'Access to Lean review',function:'Inspect decisions and collect operating evidence.',action:'Provide this lightweight page without loading 3D geometry.',evidence:'No Three.js or prepared-model dependency in this page.',status:'Implemented in v114'},
{id:'L05',decision:'Investigate',item:'Full-model reconstruction',function:'Supply consistent geometry and engineering references.',action:'Separate overview display assets from complete engineering data before staged loading.',evidence:'Measured startup phases; stable IDs; identical measurements and safety checks.',status:'Independent overview prototype available in v115; main loader unchanged'},
{id:'L06',decision:'Investigate',item:'Long drain and pipe runs',function:'Move material to a specified destination.',action:'Compare shorter feasible routes, using the current P-402 / A-400 closed header as the baseline.',evidence:'P&ID, elevations, discharge destination, gravity fall, hydraulic duty and maintenance access.',status:'No piping removal authorized by evidence'},
{id:'L07',decision:'Investigate',item:'Rack and support variants',function:'Carry loads while accommodating movement.',action:'Compare repeated support designs and opportunities to standardize.',evidence:'Loads, spans, expansion, vibration, anchors and clearance envelopes.',status:'Structural review required'},
{id:'L08',decision:'Investigate',item:'A-400 to A-900 transfers and waiting',function:'Move and transform product through finishing.',action:'Observe one batch and identify repeated handling and queues.',evidence:'Timestamped batch log, cleaning records, trip counts and transfer losses.',status:'Observation sheet below; operating data missing'},
{id:'L09',decision:'Investigate',item:'Intermediate tanks and buffers',function:'Accommodate batch mismatch and operating interruptions.',action:'Document each vessel duty and required working inventory before consolidation.',evidence:'Batch sizes, cycle overlap, working volumes, cleaning and availability.',status:'No vessel removal justified yet'},
{id:'L10',decision:'Investigate',item:'Utility distribution branches',function:'Deliver service at required conditions.',action:'Review long branches and repeated local arrangements against demand.',evidence:'Simultaneous demand, pressure, temperature, compatibility and failure effects.',status:'Utility study required'},
{id:'L11',decision:'Keep',item:'Measurement and clearance geometry',function:'Support reliable dimensions and route checks.',action:'Preserve complete engineering geometry while optimizing display work.',evidence:'Geometry and route regression baseline.',status:'Unchanged'},
{id:'L12',decision:'Simplify',item:'Walkway visibility navigation',function:'Manage walking and traffic display settings.',action:'Use one named panel with independent traffic and barrier settings.',evidence:'Shared visibility checks and camera preservation.',status:'Completed in v113'}
];
export function summarize(rows){const fields=['process','wait','transfer','clean'];let known=0,total=0,complete=true,invalid=false;for(const row of rows)for(const k of fields){const raw=row[k];if(raw===''||raw==null){complete=false;continue;}const v=Number(raw);if(!Number.isFinite(v)||v<0){invalid=true;continue;}known++;total+=v;}return {known,total,complete,invalid};}
if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);let baseline=null;
$('drain-metrics').textContent='A-400 shared header centreline: '+drainComparison.modelledLength.toFixed(2)+' m; straight-line endpoint distance: '+drainComparison.straightLineLowerBound.toFixed(2)+' m. These exclude the P-402 casing branch and do not represent the full receiver connection. Maximum theoretical shortening between these fixed endpoints: '+(drainComparison.modelledLength-drainComparison.straightLineLowerBound).toFixed(2)+' m; achievable savings are unknown.';
function render(){const host=$('cards');host.replaceChildren();for(const row of register.filter(r=>$('decision').value==='all'||r.decision===$('decision').value)){const card=document.createElement('article');for(const [tag,text,cls]of [['span',row.id+' · '+row.decision,'decision'],['h3',row.item],['p','Function: '+row.function],['p','Action: '+row.action],['p','Evidence needed: '+row.evidence],['p',row.status]]){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;card.append(el);}host.append(card);}}
$('decision').onchange=render;render();
const areas=['A-400 · Washing','A-500 · Sonication','A-600 · Drying','A-700 · Thermal treatment','A-800 · Doping / pyrolysis','A-900 · Product interface'];
for(const area of areas){const tr=document.createElement('tr');tr.dataset.area=area;const name=document.createElement('th');name.scope='row';name.textContent=area;tr.append(name);for(const key of ['process','wait','transfer','clean','travel']){const td=document.createElement('td'),input=document.createElement('input');input.type='number';input.min='0';input.step='any';input.dataset.field=key;input.setAttribute('aria-label',area+' '+key+(key==='travel'?' metres':' minutes'));td.append(input);tr.append(td);}$('route-rows').append(tr);}
const values=()=>[...$('route-rows').children].map(tr=>({area:tr.dataset.area,...Object.fromEntries([...tr.querySelectorAll('input')].map(i=>[i.dataset.field,i.value]))}));
function update(){const r=summarize(values());$('route-result').textContent=r.invalid?'Correct invalid or negative durations.':r.complete?'Recorded sequential duration: '+r.total.toFixed(1)+' min. Confirm categories do not overlap.':'Assessment incomplete · '+r.known+'/24 duration fields recorded. No total cycle time or savings claimed.';}
$('route-rows').oninput=update;update();
fetch('./lean-baseline_v114_2026-09-14.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(b=>{baseline=b;$('inventory-status').textContent=b.parts.toLocaleString()+' model components · '+b.walkwaySegments+' walkway segments · '+b.walkwayDestinations+' destination records';const t=document.createElement('table');const functions={shell:'Containment — keep; verify service and material',head:'Closure / containment — keep',fastener:'Joining / fastening — simplify display; physical removal requires design evidence',internal:'Process internals — keep pending duty review',frame:'Structural support — standardization candidate; verify loads',pump:'Material movement — review duty and transfer steps',pipe:'Material / utility routing — investigate route length',valve:'Isolation / control — retain required functions'};for(const [k,v]of Object.entries(b.counts)){const tr=document.createElement('tr');for(const text of [k,String(v),functions[k]||'Function review required']){const td=document.createElement('td');td.textContent=text;tr.append(td);}t.append(tr);}$('inventory').append(t);$('performance').textContent='Local CPU baseline: '+(b.timing.totalMs/1000).toFixed(2)+' s total; '+(b.timing.inflateMs/1000).toFixed(2)+' s decompression; '+(b.timing.reconstructMs/1000).toFixed(2)+' s reconstruction. Largest heartbeat gap: '+Math.round(b.maxHeartbeatGapMs)+' ms. This excludes deployed network and browser GPU performance.';}).catch(()=>{$('inventory-status').textContent='Baseline unavailable.';$('performance').textContent='Baseline unavailable; no performance result claimed.';});
$('export').onclick=()=>{const rows=values();if(summarize(rows).invalid||rows.some(r=>r.travel!==''&&(!Number.isFinite(Number(r.travel))||Number(r.travel)<0))){$('save-status').textContent='Correct invalid values before exporting.';return;}const data={version:115,drainComparison,date:new Date().toISOString(),register,baseline,batch:$('batch').value,route:rows,summary:summarize(rows),notes:$('observations').value};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='rGO_Lean_Review_v115_'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('save-status').textContent='Review downloaded.';};
}
