import {createAreaMeasurement} from './area-measurement-ui.js';
import {tankDiameter} from './tank-diameter.js';
import {pipeDiameter,diameterPaths,formatDiameter} from './pipe-diameter.js';
import * as T from './vendor/three.module.js';
import {MODEL_UNITS,formatDimension,pointDimensions,localAnchor,resolveAnchor,routeDimension,closestOnPath,edgeCenterline,buildPipeMeasurementIndex,routesAreConnected} from './measurement-core.js';

export function createMeasuringTool({model,viewport,scene,getCamera,isVisible,assemble,onDirty,getExploded,connectionGraph,frameArea,getControls}){
 const ns='http://www.w3.org/2000/svg',byCode=new Map(model.parts.map(p=>[p.code,p])),byId=new Map(model.parts.map(p=>[p.id,p])),{routes,partRoutes}=buildPipeMeasurementIndex(model);
 const button=document.getElementById('measure'),panel=document.getElementById('measure-panel');panel.hidden=true;panel.setAttribute('aria-label','Measure model dimensions');
 panel.innerHTML=`<div class="inspector-top"><strong>Measure</strong><button id="measure-close" aria-label="Close measuring tool">×</button></div><label for="measure-mode">Measurement</label><select id="measure-mode"><option value="distance">Point to point</option><option value="components">Horizontal / vertical</option><option value="pipe">Pipe route</option><option value="diameter">Pipe diameter</option><option value="tank-diameter">Tank diameter</option><option value="polyline">Multiple points</option><option value="area">Area</option></select><label for="measure-snap">Pick reference</label><select id="measure-snap"><option value="surface">Equipment / pipe surface</option><option value="port">Nozzle / flange center</option><option value="centerline">Pipe centerline</option><option value="plane">Reference plane</option></select><div id="measure-plane-row" hidden><label for="measure-plane">Plane elevation [mm]</label><input id="measure-plane" type="number" value="0" step="100"></div><p id="measure-instruction" class="small-note"></p><div id="measure-result" role="status" aria-live="polite"></div><div class="tool-row"><button id="measure-undo">Undo</button><button id="measure-new">New</button><button id="measure-pin">Pin</button></div><details><summary>Enter a point / precision</summary><p class="small-note">Model coordinates in mm; Y is elevation.</p><div class="coordinate-inputs"><label>X<input id="measure-x" type="number" value="0"></label><label>Y<input id="measure-y" type="number" value="0"></label><label>Z<input id="measure-z" type="number" value="0"></label></div><button id="measure-add-point">Add point</button><label for="measure-fraction">Imperial rounding</label><select id="measure-fraction"><option value="8">Nearest 1/8 inch</option><option value="16">Nearest 1/16 inch</option><option value="1">Nearest inch</option></select></details><div id="measure-pins"></div><button id="measure-clear" class="wide">Clear all dimensions</button><p class="small-note">Model dimensions · assembled geometry. Surface picks are not an automatic minimum-clearance check. Missing insulation and vendor tolerances are not included.</p>`;
 const svg=document.createElementNS(ns,'svg');svg.id='measurement-overlay';svg.setAttribute('aria-hidden','true');viewport.append(svg);
 const $=id=>panel.querySelector('#measure-'+id),state={active:false,mode:'distance',anchors:[],routeIds:[],diameter:null,pins:[],message:'',revision:MODEL_UNITS.revision};let nextId=1,lastSignature='';
 const originalChildren=[...panel.children];
 const areaTool=createAreaMeasurement({model,panel,svg,getCamera,viewport,frameArea,onDirty,getControls});
 const isDiameter=mode=>mode==='diameter'||mode==='tank-diameter';
 const fmt=n=>formatDimension(n,{fraction:Number($('fraction').value)}),element=(tag,attrs)=>{const e=document.createElementNS(ns,tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);return e;};
 function resolved(anchors){return anchors.map(a=>resolveAnchor(a,byCode));}
 function routeSet(ids){const edgeIds=new Set(),paths=[],parts=new Set();let length=0;for(const id of ids){const r=routes.get(id);if(!r)return {valid:false,reason:'Route changed — select again.'};const result=routeDimension(model,r);if(!result.valid)return result;for(const ei of r.edgeIndices){if(edgeIds.has(ei))continue;edgeIds.add(ei);const e=model.edges[ei];const path=edgeCenterline(e,byId.get(e.part));paths.push(path);length+=pointDimensions(path)?.total||0;parts.add(e.part);}}return {valid:!!ids.length,length,paths,parts};}
 function info(item){if(isDiameter(item.mode)){if(!item.diameter)return {valid:false};const a=resolveAnchor(item.diameter,byCode);return a.valid?(item.mode==='tank-diameter'?tankDiameter:pipeDiameter)(a.part,a.point):a;}if(item.mode==='pipe')return routeSet(item.routeIds);const points=resolved(item.anchors);if(points.some(p=>!p.valid))return {valid:false,reason:'Geometry changed — select endpoints again.'};return {valid:points.length>1,points:points.map(p=>p.point),dimensions:pointDimensions(points.map(p=>p.point)),parts:new Set(points.filter(p=>p.part).map(p=>p.part.id))};}
 function refresh(){
  const area=state.mode==='area';for(const child of originalChildren){if(child.matches('.inspector-top,#measure-mode,label[for="measure-mode"]'))continue;child.hidden=area;const wrapper=child.closest('.controlled-select');if(wrapper)wrapper.hidden=area;}areaTool.setActive(state.active&&area);
  const pipe=state.mode==='pipe',diameter=isDiameter(state.mode),tank=state.mode==='tank-diameter';$('snap').disabled=pipe||diameter;$('add-point').disabled=pipe||diameter;$('plane-row').hidden=area||$('snap').value!=='plane'||pipe||diameter;
  $('instruction').textContent=tank?'Click the cylindrical shell or jacket wall. Tapered sections are measured at the selected position. Lids, nozzles and supports are excluded.':diameter?'Click a pipe wall to measure its circular cross-section. For a reducer, click the position you want to measure. Flanges and valve bodies are excluded.':pipe?'Click a pipe to add its complete named route. Add adjoining routes to follow a branch; click a selected route to remove it. Valves are measured in their assembled positions.':'Pick '+(state.mode==='polyline'?'successive points; Pin when finished.':'two points. New starts another dimension.')+' Drag to orbit; scroll to zoom.';
  const r=info(state);$('result').replaceChildren();
  const row=(text,cls='small-note')=>{const p=document.createElement('p');p.className=cls;p.textContent=text;$('result').append(p);};
  if(state.message)row(state.message,'review-note');
  if(r.valid){if(diameter){row(r.kind+' · '+r.name);row(r.diameterLabel||'Outside diameter (OD)');row('Ø '+formatDiameter(r.outer),'dimension-value');row(r.inner?(r.innerLabel||'Modeled bore (ID)')+': '+formatDiameter(r.inner):(tank?'Additional wall surface: not modeled':'Bore (ID): not modeled'));if(r.ends){r.ends.forEach((e,i)=>row('End '+(i+1)+' OD: '+formatDiameter(e.outer)+(e.inner?' · ID: '+formatDiameter(e.inner):'')));row('Selected position: '+(r.station*100).toFixed(1)+'% from End 1');}if(tank){row('Section elevation: '+(r.elevation*1000).toLocaleString('en-US',{maximumFractionDigits:1})+' mm');row(r.basis);}else row('Illustrative geometry. Nominal size (DN / NPS) and pipe schedule: not specified.');}else if(pipe){row('Modeled centerline length','small-note');row(fmt(r.length),'dimension-value');state.routeIds.forEach(id=>row(routes.get(id).label));row('Selected routes include their full lengths and modeled bends. Inline fittings are included; this is not a cut-length schedule.');}
   else{const d=r.dimensions;row(fmt(state.mode==='polyline'?d.total:d.straight),'dimension-value');if(state.mode==='polyline')row(`${state.anchors.length} points · straight endpoint distance ${fmt(d.straight)}`);row('Horizontal '+fmt(d.horizontal));row('Vertical '+fmt(d.vertical));}
  }
  if(!pipe&&!diameter)state.anchors.forEach((a,i)=>row(String.fromCharCode(65+i)+' · '+(a.label||[model.equipment[a.equipmentId]?.tag,a.partName,a.kind].filter(Boolean).join(' · '))));
  $('pin').disabled=!r.valid;$('undo').disabled=!(state.anchors.length||state.routeIds.length||state.diameter);
  $('pins').replaceChildren();for(const pin of state.pins){const p=document.createElement('div');p.className='pinned-dimension';const ri=info(pin),text=document.createElement('span');text.textContent=`M${pin.id} · `+(ri.valid?(isDiameter(pin.mode)?(ri.shortLabel||'OD')+' Ø '+formatDiameter(ri.outer):fmt(pin.mode==='pipe'?ri.length:pin.mode==='polyline'?ri.dimensions.total:ri.dimensions.straight)):ri.reason);const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','Remove measurement '+pin.id);remove.onclick=()=>{state.pins=state.pins.filter(p=>p!==pin);refresh();};p.append(text,remove);$('pins').append(p);}
  lastSignature='';onDirty();
 }
 function newMeasurement(){state.anchors=[];state.routeIds=[];state.diameter=null;state.message='';refresh();}
 const separationDisabled=new Map();
 function setActive(active){const wasActive=state.active;state.active=active;panel.hidden=!active;button.setAttribute('aria-pressed',String(active));button.setAttribute('aria-expanded',String(active));document.body.classList.toggle('measuring',active);for(const id of ['explore-view-exploded','explore-amount']){const control=document.getElementById(id);if(active&&!wasActive){separationDisabled.set(id,control.disabled);control.disabled=true;}else if(!active&&wasActive)control.disabled=separationDisabled.get(id);}if(active){assemble();refresh();$('mode').focus();}else areaTool.setActive(false);lastSignature='';onDirty();}
 button.onclick=()=>setActive(!state.active);$('close').onclick=()=>{setActive(false);button.focus();};$('mode').onchange=()=>{state.mode=$('mode').value;newMeasurement();};$('snap').onchange=refresh;$('fraction').onchange=refresh;$('plane').oninput=refresh;$('new').onclick=newMeasurement;
 $('undo').onclick=()=>{isDiameter(state.mode)?state.diameter=null:state.mode==='pipe'?state.routeIds.pop():state.anchors.pop();state.message='';refresh();};$('clear').onclick=()=>{state.pins=[];newMeasurement();};
 $('pin').onclick=()=>{if(!info(state).valid)return;state.pins.push({id:nextId++,mode:state.mode,anchors:structuredClone(state.anchors),routeIds:[...state.routeIds],diameter:structuredClone(state.diameter),revision:state.revision});newMeasurement();};
 const add=a=>{if(state.mode!=='polyline'&&state.anchors.length>=2)state.anchors=[];state.anchors.push(a);state.message='';refresh();};
 $('add-point').onclick=()=>{const raw=['x','y','z'].map(id=>$(id).value.trim()),values=raw.map(Number);if(raw.some(v=>v==='')||values.some(v=>!Number.isFinite(v))){state.message='Enter three valid model coordinates.';refresh();return;}add({fixed:values.map(v=>v/1000),label:'Entered coordinate ['+values.join(', ')+'] mm',revision:state.revision});};
 function pick(hit,ray){
  if(!state.active)return false;
  if(state.mode==='area')return areaTool.pick(hit,ray);
  if(isDiameter(state.mode)){const part=hit?.object.userData.parts[hit.instanceId],r=(state.mode==='tank-diameter'?tankDiameter:pipeDiameter)(part,hit?.point.toArray()||[0,0,0]);state.diameter=r.valid?localAnchor(part,hit.point.toArray(),'diameter'):null;state.message=r.valid?'':r.reason;refresh();return true;}
  if(state.mode==='pipe'){
   const part=hit?.object.userData.parts[hit.instanceId],r=routes.get(partRoutes.get(part?.id));
   if(!r||!routeDimension(model,r).valid){state.message='Select an external pipe route. Equipment internals are excluded.';refresh();return true;}
   if(state.routeIds.includes(r.id)){const remaining=state.routeIds.filter(id=>id!==r.id);if(!routesAreConnected(remaining,routes,connectionGraph)){state.message='Removing this route would split the measured path. Remove an end route first, or start New.';refresh();return true;}state.routeIds=remaining;}
   else{const existing=new Set(state.routeIds.flatMap(id=>routes.get(id).edgeIndices));if(existing.size&&!r.edgeIndices.some(i=>existing.has(i)||[...connectionGraph[i]].some(j=>existing.has(j)))){state.message='This route is not adjoining. Start New or add the intervening route first.';refresh();return true;}state.routeIds.push(r.id);}state.message='';refresh();return true;
  }
  if($('snap').value==='plane'){const height=Number($('plane').value)/1000,plane=new T.Plane(new T.Vector3(0,1,0),-height),p=new T.Vector3();if(!Number.isFinite(height)||!ray.intersectPlane(plane,p)){state.message='The view is parallel to this plane. Rotate the view or enter coordinates.';refresh();return true;}add({fixed:p.toArray(),label:'Reference plane at '+fmt(height>=0?height:Math.abs(height))+(height<0?' below datum':''),revision:state.revision});return true;}
  if(!hit){state.message='Pick visible geometry, or choose Reference plane for empty space.';refresh();return true;}
  const part=hit.object.userData.parts[hit.instanceId],kind=$('snap').value;let point=hit.point.toArray();
  if(kind==='port'){const candidates=[...(part.ports||[]).map(p=>({point:p,label:'Flange / pipe end center'})),...model.ports.filter(p=>p.reactor===part.reactor).map(p=>({point:p.point,label:p.label}))].sort((a,b)=>hit.point.distanceTo(new T.Vector3(...a.point))-hit.point.distanceTo(new T.Vector3(...b.point)));
   if(!candidates.length||hit.point.distanceTo(new T.Vector3(...candidates[0].point))>.8){state.message='No nearby nozzle or flange center. Zoom in and select the connection.';refresh();return true;}point=candidates[0].point;
  }else if(kind==='centerline'){const es=model.edges.filter(e=>e.part===part.id&&(!e.transport||e.transport==='pipe')),best=es.map(e=>closestOnPath(point,e.path)).filter(Boolean).sort((a,b)=>a.distance-b.distance)[0];if(!best){state.message='Select pipe geometry with a defined centerline.';refresh();return true;}point=best.point;}
  add(localAnchor(part,point,kind));return true;
 }
 function draw(){
  const camera=getCamera(),w=viewport.clientWidth,h=viewport.clientHeight,signature=[...camera.matrixWorld.elements,...camera.projectionMatrix.elements,w,h,getExploded(),state.active,state.anchors.length,state.routeIds.join(),state.pins.length,areaTool.revision].join();if(signature===lastSignature)return;lastSignature=signature;svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${w} ${h}`);if(getExploded())return;
  areaTool.draw();
  const project=p=>{const v=new T.Vector3(...p).project(camera);return v.z>=-1&&v.z<=1?[(v.x+1)*w/2,(1-v.y)*h/2]:null;};
  for(const item of[...state.pins,...(state.active?[state]:[])]){const r=info(item);if(r.parts?.size&&[...r.parts].some(id=>!isVisible(byId.get(id))))continue;
   const paths=isDiameter(item.mode)&&r.valid?diameterPaths(r,camera.getWorldDirection(new T.Vector3()).toArray()):item.mode==='pipe'?r.paths||[]:r.points?.length?[r.points]:[];for(const path of paths){const p=path.map(project);for(let i=1;i<p.length;i++)if(p[i-1]&&p[i])svg.append(element('line',{x1:p[i-1][0],y1:p[i-1][1],x2:p[i][0],y2:p[i][1],class:'measurement-line'}));if(item.mode!=='pipe'&&!isDiameter(item.mode))for(let i=0;i<p.length;i++)if(p[i]){svg.append(element('circle',{cx:p[i][0],cy:p[i][1],r:5,class:'measurement-point'}));const t=element('text',{x:p[i][0]+9,y:p[i][1]-9,class:'measurement-letter'});t.textContent=String.fromCharCode(65+i);svg.append(t);}}
   if(r.valid){const path=paths[Math.floor(paths.length/2)],mid=isDiameter(item.mode)?r.center:path?.[Math.floor(path.length/2)],at=mid&&project(mid);if(!at)continue;const label=(item.id?'M'+item.id+' · ':'')+(isDiameter(item.mode)?(r.shortLabel||'OD')+' Ø '+formatDiameter(r.outer):fmt(item.mode==='pipe'?r.length:item.mode==='polyline'?r.dimensions.total:r.dimensions.straight));let x=Math.max(12,Math.min(w-285,at[0]+14)),y=Math.max(70,Math.min(h-25,at[1]-18));if(state.active&&x>w-390&&y>70)x=Math.max(12,w-680);const t=element('text',{x,y,class:'measurement-caption'});t.textContent=label;svg.append(t);}
  }
 }
 document.addEventListener('keydown',e=>{if(e.target.closest?.('dialog[open]'))return;if(!state.active)return;if(e.key==='Escape'){e.stopImmediatePropagation();if(areaTool.cancelGesture())return;if(state.anchors.length||state.routeIds.length||state.diameter)newMeasurement();else setActive(false);}if(e.key==='Backspace'&&!/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)){e.preventDefault();$('undo').click();}},true);
 refresh();return {state,pick,draw,setActive,clear:()=>{state.pins=[];newMeasurement();},invalidate:()=>{lastSignature='';},get usesPlane(){return state.active&&(state.mode==='area'||(!['pipe','diameter','tank-diameter'].includes(state.mode)&&$('snap').value==='plane'));},get active(){return state.active;}};
}
