import * as T from './vendor/three.module.js';
import {addBrowseLevels} from './plant-browse-levels.js';
import {planBrowseRoute,createBrowseRouteTravel} from './plant-browse-route.js';
import {browseArrowTargets,createBrowseArrows} from './plant-browse-arrows.js';
import {inspectWalkwaysAsync} from './walkway-review.js';
import {createBrowseNetwork,createBrowseWalker,BROWSE_PERSON,angleDelta,edgeElevation} from './plant-browse-network.js';
import {browseGeometryKey,buildBrowseOcclusion} from './plant-browse-geometry.js';

export function mountPlantBrowse({model,scene,viewport,canvas,button,onEnter,onLeave,onCamera,getCamera,onEquipment=()=>{},onMode=()=>{},onCapture,onCleanPreview=()=>{}}){
 const root=document.createElement('aside');root.id='plant-browse-panel';root.hidden=true;root.setAttribute('aria-labelledby','plant-browse-heading');viewport.append(root);
 root.innerHTML=`<div class="browse-heading"><h3 id="plant-browse-heading">Plant map</h3><button id="browse-map-toggle" aria-expanded="true" aria-controls="browse-panel-content" aria-label="Minimize map" title="Minimize map">−</button><button id="browse-exit" aria-label="Return to overview">×</button></div>
 <div id="browse-photo-tools" hidden><button id="browse-photo">High-quality photo</button><button id="browse-clean" aria-pressed="false">Clean preview</button><p id="browse-photo-status" role="status" aria-live="polite" hidden></p></div><div id="browse-panel-content"><p id="browse-status" role="status" aria-live="polite"></p>
 <div id="browse-placement"><p>Drag the person onto a highlighted walkway, or click a walkway to enter.</p><label for="browse-entry">Choose a walking entry</label><select id="browse-entry" disabled><option value="">Preparing walkways…</option></select><button id="browse-enter" disabled>Enter walkway view</button><button id="browse-fit" disabled>See walkways from above</button></div>
 <div id="browse-walking" hidden><p id="browse-location"></p><canvas id="browse-map" width="520" height="240" role="img" aria-label="Plant walkway map showing your position and viewing direction"></canvas>
 <div class="browse-move"><button id="browse-forward" aria-label="Walk forward">↑ Forward</button><button id="browse-backward" aria-label="Walk backward">↓ Back</button></div>
 <div class="browse-look"><button data-look="left" aria-label="Look left">←</button><button data-look="up" aria-label="Look up">↑</button><span>Look</span><button data-look="down" aria-label="Look down">↓</button><button data-look="right" aria-label="Look right">→</button></div>
 <div id="browse-arrow-actions" role="group" aria-label="Walkway destinations"></div><button id="browse-stop" hidden>Stop moving</button><div id="browse-junction" role="group" aria-label="Choose walkway direction"></div><details class="browse-help"><summary>Walking controls</summary><p>Click a walkway to move · Drag to look · W/S to walk · A/D to look · Click equipment for details</p></details><button id="browse-reposition">Choose another position</button></div>
 <details><summary id="browse-access-summary">Stair and platform access</summary><p id="browse-access-findings"></p></details><button id="browse-return">Return to overview</button></div>`;
 const $=id=>root.querySelector('#'+id),map=$('browse-map'),ctx=map.getContext('2d'),group=new T.Group(),pointer=new T.Vector2(),ray=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),-.035),floorPoint=new T.Vector3();
 group.name='Browse plant placement';scene.add(group);group.visible=false;
 const marker=new T.Mesh(new T.RingGeometry(.22,.34,32),new T.MeshBasicMaterial({color:0xf5c66d,side:T.DoubleSide,depthTest:true}));marker.rotation.x=-Math.PI/2;marker.visible=false;scene.add(marker);
 const ghost=document.createElement('div');ghost.className='browse-drag-person';ghost.hidden=true;ghost.innerHTML=button.querySelector('svg')?.outerHTML||'●';document.body.append(ghost);
 const arrows=createBrowseArrows(scene);let travel=null,arrowTimer=0,arrowTargets=[],previewRoute=null,hoverTime=0,touchDestination=null,autoHeading=0,turnRemaining=0;
 const routeLine=new T.Line(new T.BufferGeometry(),new T.LineBasicMaterial({color:0xffce79,depthTest:true}));routeLine.name='Browse selected walking route';routeLine.visible=false;scene.add(routeLine);
 const camera=new T.PerspectiveCamera(66,1,.04,500);
 let mode='closed',generation=0,snapshot=null,placementCamera=null,placementAim=null,cache=null,network=null,walker=null,yaw=0,pitch=0,drag=null,look=null,pendingPoint=null,lastPick=0,held=0,heldTime=0,keyMove=0,mapTimer=0,placementWidth=0,placementHeight=0,choiceKey='',suppressClick=false,ready=false;
 const keys=new Set(),entries=[];let minimized=false,clean=false,photoBusy=false,mapBackground=null,mapNetwork=null,mapXY=null,photoStatusTimer=null,mapSignature='';
 function setClean(value){clean=value;clearTimeout(photoStatusTimer);$('browse-photo-status').hidden=true;viewport.closest?.('.stage')?.classList.toggle('browse-clean-stage',value);clearMovement();viewport.classList.toggle('browse-clean-preview',value);$('browse-clean').textContent=value?'Exit preview':'Clean preview';$('browse-clean').setAttribute('aria-pressed',String(value));onCleanPreview(value);if(value)arrows.hide();else if(mode==='walking')refreshArrows();}
 $('browse-clean').onclick=()=>setClean(!clean);
 $('browse-map-toggle').onclick=()=>{minimized=!minimized;root.classList.toggle('browse-minimized',minimized);$('browse-map-toggle').textContent=minimized?'Show map':'−';$('browse-map-toggle').setAttribute('aria-expanded',String(!minimized));$('browse-map-toggle').setAttribute('aria-label',minimized?'Show map':'Minimize map');$('browse-map-toggle').title=minimized?'Show map':'Minimize map';if(!minimized)drawMap();};
 $('browse-photo').onclick=async()=>{if(photoBusy||mode!=='walking'||!onCapture)return;photoBusy=true;clearTimeout(photoStatusTimer);clearMovement();updateCamera();const b=$('browse-photo'),status=$('browse-photo-status');b.disabled=true;b.setAttribute('aria-busy','true');status.hidden=false;status.textContent='Preparing image…';try{const r=await onCapture({camera:camera.clone(),helpers:[group,marker,routeLine,arrows.group]});status.textContent='PNG downloaded · '+r.width+' × '+r.height+' px'+(r.reduced?' · adjusted to device limits':'');}catch(e){status.textContent='Photo not saved. '+e.message;}finally{photoBusy=false;b.disabled=false;b.setAttribute('aria-busy','false');photoStatusTimer=setTimeout(()=>{status.hidden=true;},5000);if(mode==='walking'){keys.clear();held=keyMove=0;viewport.focus({preventScroll:true});}}};
 function message(text){if($('browse-status').textContent!==text)$('browse-status').textContent=text;}
 function showMode(next){if(next!=='walking'&&minimized){minimized=false;root.classList.remove('browse-minimized');$('browse-map-toggle').textContent='−';$('browse-map-toggle').setAttribute('aria-expanded','true');$('browse-map-toggle').setAttribute('aria-label','Minimize map');$('browse-map-toggle').title='Minimize map';}if(next!=='walking'&&clean)setClean(false);mode=next;$('browse-photo-tools').hidden=next!=='walking';if(next!=='walking'){arrows.hide();routeLine.visible=false;previewRoute=null;}onMode(next);viewport.classList.toggle('plant-browse-active',next!=='closed');viewport.classList.toggle('plant-browse-walking',next==='walking');button.setAttribute('aria-pressed',String(next!=='closed'));button.setAttribute('aria-expanded',String(next!=='closed'));$('browse-placement').hidden=next==='walking';$('browse-walking').hidden=next!=='walking';}
 function clearMovement(){keys.clear();held=keyMove=0;look=null;travel=null;previewRoute=null;touchDestination=null;routeLine.visible=false;$('browse-stop').hidden=true;}
 function clearOverlay(){while(group.children.length){const child=group.children[0];group.remove(child);child.geometry.dispose();child.material.dispose();}}
 function overlay(){clearOverlay();const vertices=[];for(const e of network.edges)vertices.push(e.a[0],(e.ya??0)+.065,e.a[1],e.b[0],(e.yb??0)+.065,e.b[1]);const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(vertices,3));group.add(new T.LineSegments(geo,new T.LineBasicMaterial({color:0x6de9ee})));group.visible=true;}
 async function open(){
  if(mode!=='closed')return;const token=++generation;root.hidden=false;ready=false;showMode('preparing');message('Preparing available walkways…');$('browse-entry').disabled=$('browse-enter').disabled=$('browse-fit').disabled=true;
  await new Promise(resolve=>requestAnimationFrame(resolve));if(token!==generation)return;
  try{
   snapshot=onEnter();placementWidth=viewport.clientWidth;placementHeight=viewport.clientHeight;placementCamera=getCamera().clone();placementAim=snapshot.controlTarget.clone();
   await new Promise(resolve=>setTimeout(resolve,0));if(token!==generation)return;
   const key=browseGeometryKey(model);
   if(!cache||cache.key!==key){cache?.occlusion.dispose();cache=null;
    const review=await inspectWalkwaysAsync(model,()=>token!==generation);if(!review||token!==generation)return;network=createBrowseNetwork(model.walkways,review);
    const occlusion=await buildBrowseOcclusion(model,p=>message('Preparing walkway placement · '+Math.round(p*100)+'%'),()=>token!==generation);
    if(!occlusion||token!==generation){occlusion?.dispose();return;}network=await addBrowseLevels(model,network,occlusion,()=>token!==generation);if(!network||token!==generation){occlusion.dispose();return;}cache={key,network,occlusion};
   }else network=cache.network;
   if(network.levelSummary){const s=network.levelSummary;$('browse-access-summary').textContent=s.availableFlights+'/'+s.flights+' stair flights · '+s.availableDecks+'/'+s.decks+' decks connected';$('browse-access-findings').textContent=(network.levelFindings||[]).join('; ')||'Connected routes screened for the browsing body envelope. Physical access remains subject to engineering review.';}
   if(!network.edges.length)throw new Error('No checked walkways are available. Review Walkway settings.');
   entries.length=0;const used=new Set();
   for(const d of model.walkways.destinations){const p=d.walkPoint;if(!p)continue;const hit=network.nearest(p,.02);if(!hit)continue;const id=hit.point.join(',');if(used.has(id))continue;used.add(id);entries.push({label:d.label,hit});}
   if(!entries.length)entries.push({label:'Walkway entry',hit:network.nearest(network.edges[0].a)});
   $('browse-entry').replaceChildren();for(const [i,e]of entries.entries()){const option=document.createElement('option');option.value=String(i);option.textContent=e.label;$('browse-entry').append(option);}
   $('browse-entry').value='0';$('browse-entry').disabled=$('browse-enter').disabled=$('browse-fit').disabled=false;ready=true;showMode('placing');overlay();message('Choose a highlighted walkway'+(network.blocked?' · blocked segments excluded.':'.'));
   if(pendingPoint){const p=pendingPoint;pendingPoint=null;placeAt(p);}
  }catch(error){if(token!==generation)return;ready=false;message(error.message||'Walkways could not be prepared. Return to overview and retry.');}
 }
 function close(){if(mode==='closed')return;++generation;clearMovement();pendingPoint=null;drag=null;ghost.hidden=true;marker.visible=group.visible=false;const saved=snapshot;snapshot=null;showMode('closed');root.hidden=true;canvas.style.cursor='';canvas.title='';onLeave(saved);button.focus({preventScroll:true});}
 function pick(event){
  if(!ready)return null;const r=canvas.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)return null;
  const top=document.elementFromPoint(event.clientX,event.clientY);if(top!==canvas)return null;
  pointer.set((event.clientX-r.left)/r.width*2-1,1-(event.clientY-r.top)/r.height*2);const view=getCamera();view.updateMatrixWorld();ray.setFromCamera(pointer,view);
  const level=network.pickLevel?.(ray.ray);const ground=ray.ray.intersectPlane(plane,floorPoint);if(level&&(!ground||level.distance<ray.ray.origin.distanceTo(floorPoint))){if(!level.hit||cache.occlusion.blocked(ray,level.point,level.exclude))return null;return level.hit;}if(!ground)return null;
  const hit=network.nearest([floorPoint.x,floorPoint.z]);if(!hit)return null;
  if(cache.occlusion.blocked(ray,floorPoint))return null;
  // A snap stays inside the same checked surface and never crosses a barrier.
  return hit;
 }
 function placeAt(event){const hit=pick(event);if(!hit){marker.visible=false;message('Place the person on an unobstructed highlighted walkway.');return false;}enter(hit);return true;}
 function enter(hit){if(!ready)return;clearMovement();walker=createBrowseWalker(network,hit);yaw=hit.edge.heading;pitch=-.18;marker.visible=group.visible=false;showMode('walking');message('Walkway view · model inspection');choiceKey='';updateCamera();drawMap();renderChoices();refreshArrows();viewport.focus({preventScroll:true});}
 function updateCamera(){const p=walker.state.point;camera.aspect=Math.max(1,viewport.clientWidth)/Math.max(1,viewport.clientHeight);camera.updateProjectionMatrix();camera.position.set(p[0],(walker.state.y??0)+.035+BROWSE_PERSON.eyeHeight,p[1]);camera.up.set(0,1,0);const aim=camera.position.clone().add(new T.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),Math.cos(yaw)*Math.cos(pitch)));camera.lookAt(aim);camera.updateMatrixWorld();onCamera(camera,aim);}
 function location(){const p=walker.state.point;const area=model.floorAllocation?.areas?.find(a=>p[0]>=a.bounds[0]&&p[0]<=a.bounds[2]&&p[1]>=a.bounds[1]&&p[1]<=a.bounds[3]);return (area?.id||'Shared walkway')+' · elevation '+(walker.state.y??0).toFixed(1)+' m';}
 function drawMap(){if(!ctx||!network||!walker||minimized||clean)return;const nextMapSignature=[...walker.state.point,walker.state.y,yaw,walker.state.distance,map.width,map.height].join('|');if(mapNetwork===network&&mapSignature===nextMapSignature)return;mapSignature=nextMapSignature;if(mapNetwork!==network){mapNetwork=network;mapBackground=document.createElement('canvas');mapBackground.width=map.width;mapBackground.height=map.height;const bg=mapBackground.getContext('2d');const points=network.edges.flatMap(e=>[e.a,e.b]),xs=points.map(p=>p[0]),zs=points.map(p=>p[1]),minX=Math.min(...xs),minZ=Math.min(...zs),scale=Math.min((map.width-28)/Math.max(1,Math.max(...xs)-minX),(map.height-28)/Math.max(1,Math.max(...zs)-minZ));mapXY=p=>[14+(p[0]-minX)*scale,14+(p[1]-minZ)*scale];bg.fillStyle='#101f2c';bg.fillRect(0,0,map.width,map.height);bg.strokeStyle='#57998d';bg.lineWidth=2;bg.beginPath();for(const e of network.edges){bg.moveTo(...mapXY(e.a));bg.lineTo(...mapXY(e.b));}bg.stroke();}ctx.drawImage(mapBackground,0,0);const xy=mapXY;
  const [x,y]=xy(walker.state.point);ctx.fillStyle='#ffd078';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#ffd078';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.sin(yaw)*20,y+Math.cos(yaw)*20);ctx.stroke();const text=location()+' · '+walker.state.distance.toFixed(1)+' m walked';$('browse-location').textContent=text;map.setAttribute('aria-label',text+'. The gold marker shows your position and viewing direction.');
 }
 function renderChoices(){const choices=walker.state.choices,key=choices.map(o=>o.edge.id).join(',')+(choices.length?'|'+Math.round(yaw*10):'');if(key===choiceKey)return;choiceKey=key;$('browse-junction').replaceChildren();for(const [i,c]of choices.entries()){const a=angleDelta(c.heading,yaw),name=Math.abs(a)<.55?'Continue':Math.abs(a)>2.6?'Turn back':a>0?'Turn left':'Turn right';const b=document.createElement('button');b.textContent=name+' · '+c.edge.length.toFixed(1)+'\u00a0m';b.onclick=()=>{if(walker.choose(i)){yaw=walker.state.heading;choiceKey='?';renderChoices();message('Walkway view · model inspection');updateCamera();clearMovement();viewport.focus({preventScroll:true});}};$('browse-junction').append(b);}}
 function refreshArrows(){
  if(mode!=='walking'||travel||previewRoute||clean||photoBusy)return;arrowTargets=browseArrowTargets(network,walker.state,yaw);arrows.set(arrowTargets);arrows.update(camera,cache.occlusion,true);
  const host=$('browse-arrow-actions');if(host.children.length!==arrowTargets.length)host.replaceChildren();
  for(const [i,target] of arrowTargets.entries()){const b=host.children[i]||document.createElement('button');b.disabled=false;b.textContent=target.label+' · '+target.distance.toFixed(1)+'\u00a0m';b.onclick=()=>startTravel(target);if(!b.parentNode)host.append(b);}
 }
 function showRoute(route){
  previewRoute=route;routeLine.geometry.dispose();routeLine.geometry=new T.BufferGeometry().setFromPoints(route.points.map((p,i)=>new T.Vector3(p[0],(route.elevations?.[i]??0)+.085,p[1])));routeLine.visible=true;
  const first=route.legs[0];arrows.set([{point:route.destination.point,y:edgeElevation(route.destination.edge,route.destination.t),stair:route.destination.edge.stair,exclude:route.destination.edge.visualExclude,endHeading:first?.heading||yaw,heading:first?.heading||yaw,hit:route.destination,label:'Move here · '+route.distance.toFixed(1)+' m',destination:true}]);arrows.update(camera,cache.occlusion,true);
 }
 function previewAt(event){const hit=pick(event);if(!hit){previewRoute=null;routeLine.visible=false;touchDestination=null;refreshArrows();canvas.style.cursor='';canvas.title='';return null;}
  const route=planBrowseRoute(network,walker.state,hit);if(!route){previewRoute=null;routeLine.visible=false;arrows.hide();canvas.style.cursor='not-allowed';canvas.title='No connected walkway route from this position.';return {hit,route:null};}
  showRoute(route);canvas.style.cursor='pointer';canvas.title='Move here · '+route.distance.toFixed(1)+' m';return {hit,route};
 }
 function startDestination(hit){const route=planBrowseRoute(network,walker.state,hit);if(!route){message('This walkway is disconnected from your current position.');return;}
  clearMovement();if(route.distance<.05){message('You are already at this position.');refreshArrows();return;}
  showRoute(route);travel=createBrowseRouteTravel(network,route,walker.state.distance);walker=travel.walker;autoHeading=travel.heading;turnRemaining=angleDelta(autoHeading,yaw);
  for(const b of $('browse-arrow-actions').children)b.disabled=true;
  $('browse-stop').hidden=false;message('Following walkway · '+route.distance.toFixed(1)+' m');arrows.hide();renderChoices();
  if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)stepTravel(route.distance,true);
 }
 function startTravel(target){const hit=target.destination?target.hit:network.nearest(target.point,.03,target.y??0);if(hit)startDestination(hit);}
 function stepTravel(distance,instant=false){if(!travel)return;const runner=travel;walker=runner.advance(distance)||walker;turnRemaining+=angleDelta(runner.heading,autoHeading);autoHeading=runner.heading;const turn=instant?turnRemaining:Math.max(-.08,Math.min(.08,turnRemaining));yaw+=turn;turnRemaining-=turn;
  if(runner.done){travel=null;previewRoute=null;routeLine.visible=false;$('browse-stop').hidden=true;message('Position reached. Choose another walkway destination.');renderChoices();updateCamera();refreshArrows();} }
 $('browse-stop').onclick=()=>{clearMovement();message('Movement paused.');refreshArrows();};
 function update(dt){if(mode==='placing'&&placementCamera){const w=viewport.clientWidth,h=viewport.clientHeight;if(w>0&&h>0&&(w!==placementWidth||h!==placementHeight)){if(placementCamera.isOrthographicCamera){const half=(placementCamera.top-placementCamera.bottom)*.5*h/Math.max(1,placementHeight);placementCamera.top=half;placementCamera.bottom=-half;placementCamera.right=half*w/h;placementCamera.left=-half*w/h;}else placementCamera.aspect=w/h;placementCamera.updateProjectionMatrix();placementWidth=w;placementHeight=h;onCamera(placementCamera,placementAim,true);}}if(mode!=='walking'||!walker||photoBusy)return;if(travel)stepTravel(Math.min(dt,.05)*(walker.state.edge.stair?.55:2));const direction=held||keyMove;if(keys.has('a')||keys.has('arrowleft'))yaw+=dt*1.2;if(keys.has('d')||keys.has('arrowright'))yaw-=dt*1.2;
  if(held)heldTime+=dt;if(direction){walker.advance(direction*Math.min(dt,.05)*(walker.state.edge.stair?.55:BROWSE_PERSON.speed),yaw);yaw+=walker.state.turnDelta||0;if(walker.state.blocked){message(walker.state.blocked);held=keyMove=0;}renderChoices();}
  if(walker.state.choices.length)renderChoices();updateCamera();arrowTimer+=dt;if(!travel&&arrowTimer>.2){refreshArrows();arrowTimer=0;}mapTimer+=dt;if(mapTimer>.12){drawMap();mapTimer=0;}
 }
 $('browse-exit').onclick=$('browse-return').onclick=close;
 $('browse-enter').onclick=()=>{const e=entries[Number($('browse-entry').value)];if(e)enter(e.hit);};
 $('browse-fit').onclick=()=>{const points=network.edges.flatMap(e=>[e.a,e.b]),xs=points.map(p=>p[0]),zs=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs),width=Math.max(1,viewport.clientWidth),height=Math.max(1,viewport.clientHeight),reserve=Math.min(root.getBoundingClientRect().width+28,width*.45),available=Math.max(1,width-reserve),halfH=Math.max((maxZ-minZ)*.6,(maxX-minX)*.6*height/available),halfW=halfH*width/height;placementAim=new T.Vector3((minX+maxX)/2-reserve/width*halfW,0,(minZ+maxZ)/2);placementCamera=new T.OrthographicCamera(-halfW,halfW,halfH,-halfH,.04,500);placementCamera.up.set(0,0,-1);placementCamera.position.copy(placementAim).add(new T.Vector3(0,200,0));placementCamera.lookAt(placementAim);placementCamera.updateProjectionMatrix();placementCamera.updateMatrixWorld();onCamera(placementCamera,placementAim,true);};
 $('browse-reposition').onclick=()=>{clearMovement();onCamera(placementCamera,placementAim,true);showMode('placing');overlay();message('Choose another highlighted walkway.');};
 for(const [id,sign]of [['browse-forward',1],['browse-backward',-1]]){const b=$(id);b.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();clearMovement();heldTime=0;held=sign;b.setPointerCapture?.(e.pointerId);};b.onpointerup=b.onpointercancel=()=>{held=0;};b.onclick=e=>{if(e.detail===0||heldTime<.18){clearMovement();walker.advance(sign*.6,yaw);yaw+=walker.state.turnDelta||0;if(walker.state.blocked)message(walker.state.blocked);renderChoices();updateCamera();drawMap();}};}
 for(const b of root.querySelectorAll('[data-look]'))b.onclick=()=>{const d=b.dataset.look;if(d==='left')yaw+=Math.PI/8;if(d==='right')yaw-=Math.PI/8;if(d==='up')pitch=Math.min(1.25,pitch+.2);if(d==='down')pitch=Math.max(-1.25,pitch-.2);updateCamera();drawMap();};
 button.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};if(mode==='closed')open();else if(mode==='walking')$('browse-reposition').click();button.setPointerCapture?.(e.pointerId);});
 button.onclick=()=>{if(suppressClick){suppressClick=false;return;}if(mode==='closed')open();else if(mode==='walking')$('browse-reposition').click();else root.querySelector('select')?.focus();};
 window.addEventListener('pointermove',e=>{
  if(drag&&e.pointerId===drag.id){drag.moved ||= Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5;if(!drag.moved)return;ghost.hidden=false;ghost.style.transform=`translate(${e.clientX-16}px,${e.clientY-36}px)`;e.preventDefault();if(performance.now()-lastPick>70){lastPick=performance.now();const hit=pick(e);marker.visible=!!hit;if(hit)marker.position.set(hit.point[0],edgeElevation(hit.edge,hit.t)+.08,hit.point[1]);ghost.classList.toggle('invalid',!hit);}return;}
  if(look&&e.pointerId===look.id&&mode==='walking'){const dx=e.clientX-look.x,dy=e.clientY-look.y;look.moved ||= Math.hypot(e.clientX-look.startX,e.clientY-look.startY)>4;look.x=e.clientX;look.y=e.clientY;yaw-=dx*.004;pitch=Math.max(-1.25,Math.min(1.25,pitch-dy*.004));e.preventDefault();}
 },{passive:false,capture:true});
 window.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const moved=drag.moved;drag=null;ghost.hidden=true;marker.visible=false;suppressClick=moved;if(moved){if(ready)placeAt(e);else pendingPoint={clientX:e.clientX,clientY:e.clientY};}},true);
 window.addEventListener('pointercancel',()=>{drag=null;ghost.hidden=true;marker.visible=false;clearMovement();});window.addEventListener('blur',()=>{clearMovement();drag=null;ghost.hidden=true;});document.addEventListener('visibilitychange',()=>{if(document.hidden)clearMovement();});
 canvas.addEventListener('pointerdown',e=>{if(mode==='closed')return;e.stopImmediatePropagation();if(e.button!==0)return;if(mode==='walking'){look={id:e.pointerId,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};canvas.setPointerCapture?.(e.pointerId);}else if(mode==='placing'){look={id:e.pointerId,startX:e.clientX,startY:e.clientY,moved:false};}},{capture:true});
 canvas.addEventListener('pointermove',e=>{if(mode==='walking'&&!clean&&!photoBusy&&!look&&!travel&&e.pointerType!=='touch'&&performance.now()-hoverTime>70){hoverTime=performance.now();previewAt(e);}if(mode!=='closed')e.stopImmediatePropagation();},{capture:true});
 canvas.addEventListener('pointerleave',()=>{if(mode==='walking'&&!travel&&!touchDestination){previewRoute=null;routeLine.visible=false;refreshArrows();}});
 canvas.addEventListener('pointerup',e=>{if(mode==='closed')return;e.stopImmediatePropagation();if(mode==='placing'&&look&&Math.hypot(e.clientX-look.startX,e.clientY-look.startY)<5)placeAt(e);else if(mode==='walking'&&!clean&&!photoBusy&&look&&!look.moved){
  arrows.update(camera,cache.occlusion,!travel);const arrow=arrows.pick(e,canvas,camera),hit=arrow?.destination?arrow.hit:pick(e);
  if(e.pointerType==='touch'&&hit){if(travel)clearMovement();if(touchDestination&&Math.hypot(hit.point[0]-touchDestination.point[0],hit.point[1]-touchDestination.point[1])<.6)startDestination(touchDestination);else{const result=previewAt(e);touchDestination=result?.route?result.hit:null;message(result?.route?'Tap the destination marker to move.':'No connected walkway route from this position.');}}
  else if(arrow)startTravel(arrow);else if(hit)startDestination(hit);else onEquipment(e);
 }look=null;},{capture:true});
 canvas.addEventListener('wheel',e=>{if(mode!=='closed'){e.preventDefault();e.stopImmediatePropagation();}},{capture:true,passive:false});
 window.addEventListener('keydown',e=>{if(mode==='closed')return;if(e.key==='Escape'&&root.querySelector('.select-trigger[aria-expanded="true"]'))return;if(e.key==='Escape'&&clean){e.preventDefault();e.stopImmediatePropagation();setClean(false);return;}if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(travel){clearMovement();message('Movement paused.');refreshArrows();}else close();return;}if(photoBusy||mode!=='walking'||e.target.closest('input,select,textarea,button,[role="combobox"]'))return;const key=e.key.toLowerCase();if(!['w','s','a','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key))return;e.preventDefault();e.stopImmediatePropagation();if(['w','s','arrowup','arrowdown'].includes(key)){travel=null;previewRoute=null;touchDestination=null;routeLine.visible=false;$('browse-stop').hidden=true;}keys.add(key);keyMove=keys.has('w')||keys.has('arrowup')?1:keys.has('s')||keys.has('arrowdown')?-1:0;},true);
 window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());keyMove=keys.has('w')||keys.has('arrowup')?1:keys.has('s')||keys.has('arrowdown')?-1:0;});
 return {open,close,update,get active(){return mode!=='closed';},get walking(){return mode==='walking';},getState:()=>({mode,ready,minimized,cleanPreview:clean,photoBusy,position:walker?[...walker.state.point]:null,eyeHeight:BROWSE_PERSON.eyeHeight,elevation:walker?.state.y??0,levelAccess:network?.levelSummary,eligibleEdges:network?.edges.length||0,blockedSegments:network?.blocked||0,qualified:false})};
}
