import {A5000_IDS} from './a5000-basis.js';
import {OPERATION_AREAS,formatAreaText} from './engineering-register.js';
import {BANK_BASIS} from './reactor-bank.js';
import {TFF_BASIS} from './tubular-tff.js';
import {buildConnectionGraph} from './inspection.js';
import {WORKSPACES,TOOL_WORKSPACE} from './workspace-model.js';
export {WORKSPACES};
export const PANEL_WORKSPACE=TOOL_WORKSPACE;
export const BATCH_STATES={
 transfer:{title:'Charging · equal pressure required',description:'Illustrative charging configuration: F-301 and DR-401 are depressurized / equalized, the receiving hopper has capacity and the feeder can run. These are required conditions, not measured permissives.',valves:{'XV-304':'open','SDV-401':'open','XV-402':'closed'}},
 drying:{title:'Drying · charging path isolated',description:'XV-304 and SDV-401 are closed. H-401, SC-401 and the filter vent header remain outside dryer vacuum. XV-402 keeps the product receiver isolated.',valves:{'XV-304':'closed','SDV-401':'closed','XV-402':'closed'}},
 discharge:{title:'Discharge · cool and equalize first',description:'Illustrative product discharge after the drying endpoint, product cooling and pressure equalization. The upstream cake route remains closed.',valves:{'XV-304':'closed','SDV-401':'closed','XV-402':'open'}}
};
const ORIGINAL_STAGES=[
 {id:'supply',title:'Chemical & solids feeds',tags:'T-201 / T-202 · H-201 / H-202',equipment:[3,19,20,21,22,23,26,27],context:[3,19,20,21,22,23,24,25,1,2,26,4,27,28,29],color:'#72d7e4',routes:['T-201 outlet to P-203','Phosphoric acid distribution header','Pre-G chute A','KMnO4 contained induction chute A','Peroxide dosing to T-303','HCl dosing to T-305'],description:'Separate acid tanks and enclosed solids feeders supply the oxidation bank. Peroxide and HCl have dedicated downstream destinations. Select a feed below to inspect its route and isolation.',inputs:[['H₂SO₄ / H₃PO₄','T-201 / T-202 dedicated liquid sources'],['Dried Pre-G / KMnO₄','A-160 source / separate oxidizer handling']],outputs:[['Oxidation feeds','R-201A / R-201B'],['Downstream reagents','H₂O₂ → T-303; HCl → T-305']],next:'GO oxidation',note:'Pre-G manufacture in A-100 / A-140 / A-160 remains upstream of this model. Branch-specific feeders are a proposed layout, not a verified FEED equipment duplication.',feed:'sulfuric'},
 {id:'reaction',title:'GO oxidation',tags:'R-201A / R-201B · parallel',equipment:[1,2],context:[1,2,3,19,20,21,22,23,24,25,4],color:'#eac07f',routes:['Supply header to both reactors','Phosphoric branch A','Phosphoric branch B','P-205A to induction package','M-201A static mixing spool','M-201A return to reactor','P-205B to induction package','M-201B return to reactor','Both reactor outlets to P-206'],description:'Two parallel oxidation branches receive independently isolated acid and Pre-G feeds. Each KMnO₄ feeder discharges into a defined powder-induction zone on its own circulating slurry loop.',inputs:[['Acids + Pre-G','Dedicated nozzles on the selected reactor'],['KMnO₄','SF-202 → SI-201 / M-201 recirculation package']],outputs:[['Oxidized slurry','Selected reactor → P-206 → T-303']],next:'Quench & fixing',note:'A/B illustrate two branches of the FEED R-201A/B/C/D bank. SI-201 is provisional: suction, backflow protection and chemical compatibility require vendor qualification and calorimetry.',feed:'oxidant'},
 {id:'receiving',title:'Quench & fixing',tags:'T-303 · T-301 / P-301',equipment:[4,26],context:[1,2,4,26,28,29],color:'#87d9b4',routes:['P-206 discharge to T-303','Peroxide dosing to T-303','RO dilution supply to T-303','Cooling supply to T-303','T-303 cooling return','T-303 quenched slurry to P-303'],description:'T-303 has a defined quench/fixing duty with agitation, a separate cooling coil, RO water and dedicated peroxide addition. Its material outlet is isolated until the quench endpoint is confirmed.',inputs:[['Oxidized slurry','R-201A / R-201B → P-206'],['H₂O₂ / dilution water','T-301 → P-301 / BL-RO-201']],outputs:[['Quenched slurry','XV-QOUT → P-303 → T-305']],next:'Acid washing',note:'The reagent routing view does not prescribe dilution or peroxide addition order. This sequence and the FEED draft’s conflicting trip limits require resolution before an operating procedure is defined.',feed:'peroxide'},
 {id:'acidwash',title:'Acid washing',tags:'T-305 · T-302 / P-302',equipment:[28,27],context:[4,27,28,5],color:'#e6be7d',routes:['P-303 to T-305 acid wash','HCl dosing to T-305','T-305 outlet to P-F301'],description:'The dedicated HCl circuit enters agitated T-305 after verified quenching. Acid-washed slurry then feeds the retained filtration and drying concept.',inputs:[['Quenched slurry','T-303 → P-303'],['HCl','T-302 → P-302']],outputs:[['Acid-washed slurry','P-F301 → F-301 finishing concept']],next:'Filtration & washing',note:'Scope boundary: the FEED C-301 decanter before T-305 is not modeled. Direct slurry transfer is an explorer simplification. F-301/DR-401 also do not represent the FEED TFF-401 train.',feed:'hcl'},
 {id:'filtration',title:'Filtration & washing',tags:'F-301 · TK-302 / TK-301',equipment:[5,6,7],context:[28,5,6,7,8,18],color:'#efa56e',routes:['P-F301 slurry feed to F-301','P-W301 wash feed to F-301','F-301 filtrate to TK-301','F-301 wet cake to H-401'],description:'In this separate finishing concept, slurry enters above the medium. Washing removes soluble material; the lower plenum collects filtrate. The elevated filter discharges washed cake through XV-304 into H-401.',inputs:[['Acid-washed slurry','T-305 → P-F301'],['Wash liquid','TK-302 → P-W301']],outputs:[['Filtrate / wash liquor','TK-301'],['Washed wet cake','XV-304 → H-401']],next:'Cake transfer',note:'Filtration and washing must finish before cake discharge. F-301 remains a nonthermal filter.'},
 {id:'transfer',title:'Cake transfer',tags:'H-401 → SC-401 → SDV-401',equipment:[8,16],context:[5,8,16,10,18],color:'#dda4ee',routes:['F-301 wet cake to H-401','H-401 gravity cake passage','SC-401 mechanical cake transfer','SC-401 gravity chute to DR-401','DR-401 contained charge neck'],description:'A fixed hopper receives cake from F-301. The enclosed screw meters it horizontally; a short downward chute feeds the dryer through SDV-401.',inputs:[['Washed wet cake','F-301 / XV-304']],outputs:[['Metered wet cake','SDV-401 → DR-401']],next:'Drying',note:'The screw supplies transport, not vacuum sealing. Hopper capacity and feeder rate must use wet-cake mass and bulk density.',state:'transfer'},
 {id:'drying',title:'Drying',tags:'DR-401 · F-401 / E-401 / VP-401',equipment:[10,11,12,13,14],context:[8,16,10,11,12,13,14,15,17],color:'#b9b6f2',routes:['DR-401 vapor to F-401','F-401 clean vapor to E-401','E-401 gravity drain to TK-401','TK-401 separated vapor to VP-401','VP-401 exhaust to closed treatment','TK-401 closed condensate collection'],description:'After charging isolation is verified, heat and agitation remove residual liquid under vacuum. Dust filtration, condensation and separation protect the vacuum pump.',inputs:[['Wet cake','H-401 → SC-401 → SDV-401']],outputs:[['Dry solids','Retained for cooling and discharge'],['Vapors / condensate','F-401 → E-401 → TK-401 / VP-401']],next:'Product collection',note:'Heating, condenser cooling, vacuum capacity, final moisture and product temperature require a defined process basis.',state:'drying'},
 {id:'product',title:'Product collection',tags:'XV-402 → BIN-401',equipment:[15],context:[10,15],color:'#e4ce91',routes:['DR-401 dry product to BIN-401','BIN-401 separate displacement vent'],description:'Cooled product leaves the dryer through XV-402 into the contained product receiver. Receiver breathing follows its own closed connection.',inputs:[['Cooled dry solids','DR-401 / XV-402']],outputs:[['Contained product','BIN-401 for the next defined operation']],next:null,note:'Discharge requires product readiness, equalized pressure and receiver capacity. Packaging is outside this model.',state:'discharge'}
];
const stage=(id,title,tags,equipment,routes,description,inputs,outputs,unit,unitState,note='FEED topology; dimensions, materials and operating limits remain design inputs.')=>({id,title,tags,equipment,context:equipment,routes,description,inputs,outputs,unit,unitState,note,color:'#85cfc4',train:'feed'});
const original=id=>({...ORIGINAL_STAGES.find(s=>s.id===id),train:'feed'});
const supply=original('supply');supply.note='Manufactured Pre-G reaches H-201A/B through the contained EL-164 / SC-164 distribution system. Branch-specific feeders remain a provisional layout.';
const receiving=original('receiving');receiving.outputs=[['Quenched slurry','XV-QOUT → P-303 → C-301']];receiving.next='Primary decanting';
const washing=original('acidwash');Object.assign(washing,{feed:null,unit:'wash',unitState:'wash',context:[28,27,30,31,32],routes:['C-301 concentrate chute to T-305','HCl dosing to T-305','P-305 decant to wastewater','P-304 to T-402 diafiltration'],description:'T-305 receives concentrate from C-301 and dedicated HCl. Mixing, settling, supernatant decanting and slurry transfer are separate batch states.',inputs:[['Concentrated material','C-301 solids discharge'],['HCl','T-302 / P-302']],outputs:[['Decanted liquor','P-305 → A-1000 wastewater interface'],['Washed slurry','P-304 → T-402']],note:'Decanting depends on demonstrated settling behavior. Retain solids during supernatant removal and verify the wash endpoint before transfer.'});
export const STAGES=[
 stage('premix','Graphite premixing','T-102 / H-101 → R-101',[37,38,36],['P-101 sulfuric delivery','H101 contained drop','A140 premix distribution header'],'Dedicated sulfuric and contained graphite feeds meet in R-101. Agitated premix feeds the synthesis bank.',[['Graphite','H-101 contained charging'],['Sulfuric acid','T-102 / P-101']],[['Premix','Selected R-141 branch']],'preg','premix'),
 stage('synthesis','Pre-G synthesis','R-141A / B / C / D',[39,40,41,42,43],['A140 premix distribution header','R-141A premix branch','CH141A contained drop','CH142A contained drop','A140 collection header to pump'],'Four synthesis vessels have isolated premix branches, dedicated K₂S₂O₈ and P₂O₅ charging, and separate thermal services.',[['Premix','R-101'],['K₂S₂O₈ / P₂O₅','Separate contained charging interfaces']],[['Synthesis slurry','Selected outlet → fixing tanks']],'preg','synthesis','Charging routes are illustrated; reagent addition order, heat-up/hold/cool schedule and limits require the approved process basis.'),
 stage('fixing','Fixing, recycle & holding','T-161 → P-162 → T-162',[44,45,51],['P-PG141 to fixing header','P-162 recycle to T-161','P-162 transfer to T-162','T-161 decant to wastewater','P-163 fixing waste to wastewater'],'T-161 provides fixing, dilution and recycle through P-162. A separate transfer state fills T-162, the holding tank upstream of P-164 and F-161. Supernatant and bottom waste leave through dedicated wastewater paths.',[['Synthesis slurry','A-140 R-141 bank'],['RO water','A-2000 dedicated makeup']],[['Retained slurry','T-162 holding → P-164 → F-161'],['Wastewater','A-1000 segregated interfaces']],'preg','fix'),
 stage('pregpress','Pre-G filtration & tray loading','F-161 → TR-164',[46,48,51],['P-164 filter press feed','F-161 filtrate to T-163','F-161 cake release','TR-164 wet cake tray transfer'],'F-161 separates filtrate from cake. Released cake is loaded into contained trays and moved mechanically to D-164.',[['Held slurry','T-162 / P-164']],[['Filtrate','T-163'],['Wet cake in trays','TR-164 → D-164']],'preg','press'),
 stage('pregdry','Pre-G drying & distribution','D-164 → H-164 → EL-164 / SC-164',[47,48,49,50,53,20,21],['TR-164 wet cake tray transfer','D-164 tray loading and unloading','D-164 vapor to KO-164','H-164 contained dry tray unloading','EL-164 powered dry solids lift','H-201A manufactured Pre-G inlet','H-201B manufactured Pre-G inlet'],'Tray drying, cooling and unloading occur as separate operations. An enclosed unloading station, powered lift and distribution screws supply the oxidation feeders.',[['Wet cake trays','F-161 / TR-164']],[['Dried Pre-G','H-201A / H-201B'],['Vapor / condensate','KO-164 / VP-164 closed interfaces']],'preg','dry','The contained handling system is a proposed layout. Verify powder behavior, tray logistics, moisture, thermal stability and pressure equalization; it is not a liquid pipeline.'),
 supply,original('reaction'),receiving,
 stage('decanter','Primary decanting','C-301 → T-304 / T-305',[30,31,4,28],['P-303 to C-301 feed','C-301 scroll solids passage','C-301 concentrate chute to T-305','C-301 centrate to T-304'],'The powered bowl and scroll split quenched slurry into centrate and concentrated solids. Each fraction has its own permanent outlet.',[['Quenched slurry','T-303 / P-303']],[['Centrate','T-304'],['Concentrated solids','Contained downward chute → T-305']],'decanter','separate'),
 washing,
 stage('tff','Diafiltration & concentration','T-402 / P-402 / TFF-401',[32,33,34,35,124,28],['P-304 to T-402 diafiltration','T-402 to P-402','P-402 to TFF-401','TFF-401 retentate return','TFF-401 permeate to T-403','A400 RO makeup to T-402','TFF CIP supply','TFF CIP return to package'],'P-402 circulates the suspension through TFF-401. Retentate returns to T-402; permeate carries dissolved contaminants to T-403. RO makeup supports diafiltration.',[['Acid-washed slurry','T-305 / P-304'],['RO makeup','BL-RO400']],[['Retentate','Return to T-402'],['Permeate','T-403 / P-403 → treatment']],'tff','wash','Membrane chemistry, retention, fouling, allowable pressure and wash endpoint need trials. Permeate may contain product losses; no separation yield is assumed.'),
 stage('a500','Conditioning & inline sonication','T-501 → P-501 → US-501 → E-501',[63,64,65,66,67,68],['A500 receiving transfer','T-501 bottom suction','P-501 to US-501','US-501A to next cell','US-501B to next cell','US-501 outlet to cooler','E-501 cooled return','A500 accepted product to A600'],'Accepted washed suspension enters agitated T-501. P-501 circulates it through three series flow cells and E-501 cooling. P-502 releases qualified suspension to the T-601 dryer-feed buffer.',[['Washed suspension','T-402 / P-402 after the wash endpoint'],['Cooling / qualified cleaning','Separate A500 utility connections']],[['Cooled recirculation','Return to T-501'],['Accepted suspension','P-502 → T-601']],'sonication','sonicate','US-501 is the FEED duty. Auxiliary tags and three-cell capacity are provisional. Aqueous GO basis. Optional DR-401 remains an independent cake-fed concept.'),
 stage('a600','Spray drying & powder recovery','T-601 / P-601 → DR-601 → T-602',[69,70,71,72,73,74,75,76,77,78,123],['A600 accepted suspension reception','P-601 metered atomizer feed','P-601 recycle to T-601','HX-601 hot gas to DR-601','DR-601 exhaust to F-601','F-601 to FN-601','FN-601 exhaust to SC-601','DR-601 gravity powder chute to T-602','F-601 gravity powder chute to T-602'],'T-601 buffers accepted aqueous GO suspension. P-601 meters atomizer feed or recycles to the tank. DR-601 evaporates water; F-601 captures fines, and SC-601 polishes exhaust. T-602 contains recovered powder for A700.',[['Accepted aqueous suspension','T-501 / P-502'],['Drying gas / indirect heat','BL-601 / HX-601']],[['Recovered GO powder','T-602 → contained A700 interface'],['Treated exhaust / wash effluent','Separate controlled destinations']],'spray','receive','Water is the process carrier. Atomizer, evaporation duty, thermal limits, dust protection, drying-gas choice and cleaning compatibility remain FEED design inputs.'),
 stage('a700','Continuous furnace & argon atmosphere','C-701 → PY-701 → E-702 → T-702',[79,80,81,82,83,84,85,86,87,88,89,90,91],['T-602 to TR-701 pickup','TR-701 solids passage','LK-701 to H-701 buffer','C-701 solids passage','PY-701 argon process volume','PY-701 to E-702 enclosed drop','E-702 solids passage','A700 argon supply','Ar distribution header','LK-701 purge exhaust to treatment','PY-701 off-gas to E-701','KO-701 to FN-701','E702 cooling supply','PT-701 protected impulse line'],'A purgeable transfer lock separates the dryer air circuit from H-701. C-701 feeds a continuous three-zone furnace. Proposed E-702 adds indirect cooling before T-702; reconcile this duty with PY-701 internal cooling. Ar supply, oxygen sampling and exhaust-pressure control protect the defined enclosure.',[['Accepted dry GO','T-602 through proposed TR-701 / LK-701'],['Argon and cooling','Separate qualified utility interfaces']],[['Cooled product','T-702 → TR-801 → H-801'],['Off-gas / condensate','E-701 → KO-701 → FN-701 → treatment']],'furnace','purge','Ar is the atmosphere gas. Oxygen thresholds, purge/process flows, pressure sign and setpoint, thermal limits and internal conveying mechanism remain HOLD. This is a conceptual inspection model.'),
 stage('a800feed','Contained receiving, ratio dosing & mixing','H-801 / F-801 + H-802 / F-802 → MX-801 → H-803',[101,102,103,104,105,106,107,108,114,115],['T-702 accepted rGO transfer','TR-801 powered lift','H-801 to F-801 refill','H-802 to F-802 refill','F-801 metered solids passage','F-802 metered solids passage','MX-801 process passage','MX-801 to H-803 mixed solids'],'TR-801 raises accepted rGO from T-702 into H-801. Dry contained charging fills H-802 through proposed LK-802. The independently weighed F-801 / F-802 feeds join in the inerted MX-801 mixer; H-803 buffers its discharge.',[['Accepted rGO','A-700 T-702'],['Dry KBH₄','Contained reagent docking → LK-802 / H-802']],[['Mixed solids','H-803 → RV-801 → PY-801'],['Feeder and mixer vents','Separate compatible treatment interfaces']],'doping','mix','Draft 1:1 reagent ratio is an unqualified source reference. Flexible feeder connections, controlled refill, powder flowability, mixing quality and surge capacity require testing. No process-water cleaning connection is provided.'),
 stage('a800thermal','Doping pyrolysis, cooling & product release','H-803 → RV-801 → PY-801 → A-900',[107,108,109,110,111,112,113,114,116],['RV-801 rotating pocket transfer','PY-801 process passage','PY-801 cooling annulus','A-800 qualified product to A-900','PY-801 off-gas to E-801'],'Mixed feed enters PY-801 through the illustrated isolation valves and RV-801. Heating, reaction hold and indirect cooling are separate furnace zones. Cooled, qualified material is released to the A-900 boundary under a verified receiving atmosphere.',[['Mixed solids','MX-801 / H-803'],['Argon and cooling','A-6000 / A-5000']],[['Accepted doped product','Stream 808 → A-900 contained pelletization interface'],['Off-gas','E-801 → FN-801 → separate AB-3801 candidate']],'doping','process','PFD arrows 806 / 807 show RV-801 feeding PY-801; General Note 2 names F-801. The illustrated route follows the arrows pending confirmation. Draft thermal, pressure and oxygen values are not approved setpoints. RV-801 alone is not positive gas isolation.'),
 stage('a800atmosphere','Dry argon, verification & off-gas control','AR-801 / AIT-801 · E-801 → FN-801 · PSV-801',[112,113,110,111,109,115,116,114],['A800 argon supply','AR-801 distribution header','A800 dry vent header','F-802 separate EX802 off-gas','PY-801 off-gas to E-801','FN-801 to A-3000 treatment','PSV-801 to dedicated relief treatment'],'Monitored dry Ar branches supply inventories and seals. O₂, moisture, H₂, pressure and cooling verification govern illustrative feed and heat permissions. Furnace off-gas cooling / draft, feeder vent treatment and pressure relief have explicit destinations.',[['Dry Ar / cooling','Qualified A-6000 / A-5000 interfaces'],['Off-gas and displacement gas','A-800 process inventories']],[['Controlled off-gas','Independent AB-3801 envelope · duty HOLD'],['Utility drain / process residue','Separate closed collection boundaries']],'doping','purge','No live instrument data. Probe technology, limits, purge acceptance, pressure coordination, relief sizing, leak detection and treatment compatibility remain open. A-800 dry solids have no generic floor drain.'),
stage('a900receive','Contained product receipt','A-800 → TR-901 → H-901',[200,201],['A-900 short contained product transfer','TR-901 to H-901 receipt'],'A short sealed transfer receives accepted A-800 product directly into the adjacent inerted surge and weighing hopper.',[['Accepted doped rGO','A-800 product boundary']],[['Buffered product','H-901']],'pelletizing','receive','Transfer technology, acceptance criteria, capacity and selected argon branch remain HOLD.'),
stage('a900pelletize','Metering and pellet formation','H-901 → F-901 → PG-901',[201,202,203],['H-901 to F-901 feed','F-901 metered product passage','F-901 to PG-901 contained feed','PG-901 pellet-formation passage'],'A controlled feeder supplies a contained pellet-formation envelope.',[['Buffered product','H-901']],[['Formed product','PG-901']],'pelletizing','form','Dry compaction, binder agglomeration and polymer compounding remain alternatives; no melt-extrusion duty is inferred.'),
stage('a900finish','Cooling, classification and collection','SC-901 → PK-901 / CP-901',[204,205,208],['PG-901 formed product to SC-901','SC-901 cooling and classification passage','SC-901 accepted pellets to PK-901','PK-901 accepted product passage','PK-901 accepted product release'],'Proposed cooling, size classification, collection, release and traceability functions separate accepted product from rejects.',[['Formed product','PG-901']],[['Accepted packaged pellets','BL-A900-PRODUCT']],'pelletizing','finish','Cooling duty, size limits, pellet strength, package format and release criteria remain open.'),
stage('a900reject','Reject recovery','SC-901 → RB-901',[206],['SC-901 reject to RB-901'],'A sealed receiver represents off-size quarantine and recoverable-product handling.',[['Off-size product','SC-901']],[['Quarantined reject','BL-A900-REJECT']],'pelletizing','reject','Disposition, recovery method and cleaning remain unresolved.'),
stage('a900dust','Local dust boundary','PG-901 → DC-901',[207],['PG-901 local dust capture to DC-901'],'A local capture and filtration envelope terminates at an independent unresolved treatment boundary.',[['Powder-laden displacement gas','PG-901']],[['Filtered dust exhaust','BL-A900-DUST']],'pelletizing','contain','No treatment destination, emission performance or operating release is asserted.'),
 stage('wwcollect','Wastewater collection and equalization','T-1006 / P-1005 · proposed T-1007 / P-1011',[125,141,148,150,151],['Combined wastewater to T-1006','Pre-G decant downhill to T-1007'],'A-160 and A-300 wash liquors and A-400 permeate connect to T-1006. A low receiver and lift pump preserve gravity decant before joining the overhead collection header.',[['Wash wastewater','A-160 / A-300'],['VSEP permeate','A-400 T-403 / P-403']],[['Equalized wastewater','P-1005 → R-1001']],null,null,'100 m³/h is a layout allowance, not verified total flow. T-1006 is a 200 m³ screening envelope. Residual oxidants, temperature, compatibility and batch surges require qualification.'),
 stage('wwtreat','Staged chemical treatment','R-1001 → R-1002 → R-1003 → R-1004',[126,127,128,129,142,143,144,152],['P-1006 transfer overhead','P-1007 transfer overhead','P-1008 transfer overhead'],'PFD-listed neutralization, lime precipitation, conditional sulfate polishing and final conditioning are arranged in sequence. Mixing, a separate cooling jacket and process-mounted pH probes have grade indication.',[['Equalized wastewater','T-1006 / P-1005'],['Metered reagents','Dedicated chemical storage and dosing']],[['Conditioned slurry','P-1009 → DC-1001']],null,null,'35 / 65 / 45 / 45 m³ envelopes use provisional 15 / 30 / 20 / 20 minute residence times at 100 m³/h. No operating pH, reagent dose or protective setpoint is approved. R-1002 source pH conflict remains open.'),
 stage('wwchem','Segregated chemical storage and dosing','T-1001–T-1005 / P-1001–P-1004 / M-1001',[131,132,133,134,135,136,137,138,139,140,148],['P-1004 to R-1001','P-1003 to R-1002','P-1002 to R-1003','P-1001 to R-1004','M-1001 to R-1004'],'Separate containment cells and closed fill points serve NaOH, lime, conditional BaCl₂, HCl and floc aid. Dedicated vents remain segregated for future treatment review.',[['Reagents','Closed unloading at the upper service frontage']],[['Metered feeds','Assigned reactor injection ports']],null,null,'Storage quantities are geometric allowances. BaCl₂ and HCl trim remain isolated by default pending chemistry review, including dissolved barium, scaling and metals redissolution.'),
 stage('wwseparate','Centrifuge, centrate and sludge handling','DC-1001 / P-1009 / proposed T-1008 / P-1012',[130,145,146,149,153,154],['P-1009 to DC-1001','DC-1001 gravity centrate to T-1008','Lifted centrate to A-2000','DC-1001 dewatered sludge outlet'],'DC-1001 separates conditioned solids into covered collection. Gravity centrate enters a low receiver before pumped transfer or controlled recycle. The PFD bypass is normally isolated.',[['Conditioned slurry','R-1004 / P-1009']],[['Centrate','Connected T-2001 feed equalization'],['Dewatered sludge','BIN-1001 · classification pending']],null,null,'No treatment flow can be assumed to continue until an accepted centrate destination is connected. Centrate lift, surge capacity, low-level pump protection and recycle duty require qualification. Centrifugation does not remove dissolved salts.'),
 stage('ropretreat','Reclaimed-water equalization and pretreatment','T-2001 → MMF / GF / CF → UF-2001',[500,501,502,503,504,505,517,518],['A-1000 centrate to T-2001','T-2001 to P-2001','P-2001 to MMF-2001','MMF-2001 to GF-2001','GF-2001 to CF-2001','CF-2001 to UF-2001','UF-2001 filtrate to TK-UF2001'],'Agitated equalization buffers centrate. Media filters remove solids, iron/manganese and oxidants before dead-end UF. A proposed filtrate buffer supports controlled RO feeding and UF backwash.',[['Centrate','A-1000 DC-1001 via T-1008 / P-1012']],[['UF filtrate','Antiscalant → RO high-pressure pump'],['Backwash','Separate receiver and lift → T-1006']],'reclaimed','start','The 8-hour PFD minimum implies 800 m³ working / 1,000 m³ nominal at the 100 m³/h screening flow. UF protects against particles; dissolved salts remain.'),
 stage('rorecover','Single-pass RO and quality diversion','P-2002 / RO-2001 · A/B duty, C standby',[506,507,516],['P-2002A to RO-2001A','RO-2001A permeate collection','RO-2001A concentrate collection','Accepted RO permeate to T-2002','RO off-spec recycle to T-2001'],'Two duty trains plus one standby implement the PFD N+1 requirement. Single-pass 8:4 staging is a proposed arrangement. Startup and off-spec permeate recycle; qualified water enters T-2002.',[['UF filtrate','Qualified scaling / oxidant acceptance']],[['Permeate','T-2002'],['Concentrate','T-2003']],'reclaimed','produce','60% base RO recovery. Draft 12–16 bar pump basis, membrane area, pressure ratings and rejection need vendor projection. Capacity is an allowance, not a performance guarantee.'),
 stage('rodistribute','Qualified process-water storage and distribution','T-2002 → P-2005 → CF-2002',[508,509,510],['T-2002 to P-2005','P-2005 to CF-2002','CF-2002 reclaimed water header'],'Product storage feeds final cartridge polishing and the existing Pre-G, fixing and A-400 water interfaces. Stored off-spec water can return to equalization with user supply isolated.',[['Accepted permeate','RO quality diversion']],[['Qualified water','Pre-G / TLGO washing and fixing']],'reclaimed','produce','The base case provides 54.39 m³/h versus A-400 demand of 71 m³/h alone. Supplemental supply and the complete batch water balance remain open. Emergency eyewash stays on independent potable water.'),
 stage('rowaste','Backwash return and concentrate management','TK-BW2001 / P-BW2001 · T-2003 / P-2003',[519,520,511,512],['A-2000 backwash to T-1006','RO concentrate to T-2003','T-2003 to P-2003','P-2003 concentrate discharge'],'Media and non-chemical UF backwash return to A-1000 through a receiver and lift pump. Concentrate has a separate tank, pump and positively blinded disposal boundary.',[['Backwash / reject','Media and UF'],['Brine','RO-2001']],[['Backwash','T-1006 equalization'],['Brine','Authorized destination to be assigned']],'reclaimed','backwash','No normal brine recycle or unapproved sewer connection. Holding capacity and authorized removal determine allowable runtime.'),
 stage('roclean','Contained antiscalant and isolated RO cleaning','T-2004 / P-2004 · CIP-2001',[513,514,515,521],['P-2004 antiscalant injection','CIP-2001 cleaning supply','RO cleaning return to CIP-2001','CIP spent liquor to TK-CIP2001-W'],'Antiscalant enters the UF filtrate before the RO skid. One isolated RO train is cleaned at a time, using sequential compatible acid and alkaline batches with separate spent-liquor holding.',[['Antiscalant / qualified CIP chemicals','Contained delivery and cleaning package']],[['Cleaning return','CIP-2001'],['Spent chemicals','Separate EHS disposal boundary']],'reclaimed','cip','Chemical doses, sequential cleaning, rinse verification, bund capacity, waste compatibility and membrane cleaning limits require vendor qualification.'),
 stage('vgcollect','Compatible wet vent collection','HD-3100 / V-3110 / CP-3000',[614,600,613],['HD-3100 sloped wet collection trunk','Compatible wet vent inlet','V-3110 to T-3140'],'Candidate wet acid vents collect under controlled draft. Bulk droplets separate in V-3110. Dry/reactive sources and emergency relief remain independent.',[['Candidate wet vents','Source compatibility register']],[['De-entrained gas','T-3140'],['Acid condensate','TK-3111']],'ventgas','start','No source emission permission until chemistry, draft, liquid circulation and receiving capacity are qualified.'),
 stage('vgtreat','Acid absorption, mist polishing and stack','T-3140 / proposed ME-3150 / FN-3160 / ST-3170',[601,609,605,606],['T-3140 counter-current gas passage','T-3140 to ME-3150','ME-3150 to FN-3160','FN-3160 to ST-3170'],'Packed absorption and fine-mist capture address different contaminants. Fan draft follows both treatment stages; the model has no operating untreated bypass.',[['Wet acid gas','V-3110'],['Scrubbing liquor','P-3181A/B']],[['Treated gas','ST-3170 permit point'],['Collected pollutants','Controlled liquid waste']],'ventgas','run','Removal efficiency, stack dispersion, gas composition and all operating settings remain unqualified.'),
 stage('vgliquor','Liquor circulation and chemical control','T-3180 / P-3181A/B / T-3182 / P-3182',[602,603,604,607,608,615,616],['T-3180 liquid inventory','P-3181 recirculation to T-3140','T-3140 sealed gravity liquor return','P-3182 pH-controlled NaOH injection'],'One recirculation pump runs while the other remains available. NaOH neutralizes absorbed acids; protected makeup replaces losses and monitored blowdown limits salt accumulation.',[['Water and NaOH','Protected separate supplies']],[['Distributed liquor','T-3140'],['High-salt blowdown','Qualified A-1000 acceptance']],'ventgas','standby','Liquid return elevations, maintained seals, wetting rate, pH/temperature limits and pump duty require vendor design.'),
 stage('vgwaste','Segregated condensate and scrubber blowdown','TK-3111 / P-3111 / P-3183',[610,611,612],['V-3110 condensate sealed drain','P-3111 qualified return to T-1006','P-3183 qualified return to T-1006'],'Acidic condensate and alkaline high-salt liquor use separate pumped returns. Export remains isolated until receiving chemistry and capacity are accepted.',[['KO condensate','V-3110'],['Scrubber blowdown','T-3180']],[['Conditional wastewater return','A-1000 T-1006']],'ventgas','blowdown','Neutralization transfers contaminants to water. Assess chloride/sulfate effects on A-2000 RO; do not credit wastewater treatment with dissolved-salt removal.'),
 stage('a5000','Central heating and cooling','A-5100 / A-5200 / A-5300',A5000_IDS,['Hot water generator outlet','Cooling water generator outlet','Chilled water generator outlet'],'Independent hot-water, cooling-water and chilled-water loops serve explicitly mapped utility passages. Proposed secondary loops keep reactor and wastewater media separate from central water. Inspect heating and cooling in Route tracing.',[['Energy / heat rejection','Generation source and vendor capacity HOLD']],[['HWS / HWR','90 / 70 °C illustration'],['CWS / CWR','27 / 37 °C illustration'],['CHWS / CHWR','6 / 12 °C illustration']],null,null,'FEED-PFD-5000 page 19 is draft. Temperatures are illustrative, not operating setpoints. Thermal duties, water chemistry, controls, materials, expansion, pressure protection and emergency cooling remain unqualified.'),
 stage('a6000','Argon source, regulation and distribution','A-6100 → AR-6001 → A-6200 → area manifolds',[118,119,120,121,122,117,89,112],['AR-6001 regulated supply to A-6200','A-6200 common Ar header'],'One selected primary source and an independently checked reserve supply feed the common header. Compact grade and platform manifolds preserve independent consumer control. Reserved A-900 and other purge branches remain positively blinded.',[['Primary and reserve Ar','Selected A-6100 source concept']],[['Regulated Ar','A-700 and A-800 local stations'],['Reserved branches','AR-901 / AR-902 / AR-903 / AR-X · isolated and blinded']],'argon','primary','Source and distribution geometry are proposed. Gas demand, regulator selection, vaporizer duty, pressure protection, reserve duration and gas-quality limits remain unqualified.'),
 ...ORIGINAL_STAGES.filter(s=>['filtration','transfer','drying','product'].includes(s.id)).map(s=>({...s,train:'finishing',...(s.id==='filtration'?{context:[5,6,7,8,18],inputs:[['Slurry','BL-FIN-SLURRY → P-F301'],['Wash liquid','TK-302 → P-W301']],note:'Separate finishing concept with an independent slurry feed boundary. TFF-401 suspension is not routed directly into this cake-fed dryer.'}:{})}))
];
// The same stage records drive the overview, equipment framing and route cards.
for(const s of STAGES){
 s.areaId=OPERATION_AREAS[s.id];
 if(['supply','reaction','receiving','pregdry'].includes(s.id)){
  const map={1:54,2:55,20:56,21:57,22:58,23:59,24:60,25:61};for(const key of ['equipment','context']){s[key]=[...new Set([...s[key],...s[key].filter(i=>map[i]).map(i=>map[i]),...(['reaction','receiving'].includes(s.id)?[62]:[])])];}
  s.outputs=s.outputs.map(row=>row.map(v=>v.replace('R-201A / R-201B','R-201A/B/C/D').replace('H-201A / H-201B','H-201A/B/C/D')));s.inputs=s.inputs.map(row=>row.map(v=>v.replace('R-201A / R-201B → P-206','R-201A/B/C/D → selected P-206A/B')));
 }
 if(s.id==='reaction'){s.tags='R-201A / B / C / D · parallel';s.description='Four oxidation reactors have separate feed selection, jacket control, recirculation and product isolation. Inspect one branch and transfer pump at a time. Dedicated recirculation and metering packages are a proposed arrangement pending FEED quantity reconciliation.';s.note=BANK_BASIS;s.routes.push('Phosphoric branch C','Phosphoric branch D','P-205C to induction package','M-201C return to reactor','P-205D to induction package','M-201D return to reactor','Rear reactor outlets to transfer manifold','P-206B discharge to common transfer','BL-CWS201 connected front bank header','BL-CWR201 connected front bank header');}
 if(s.id==='supply')s.note='Manufactured Pre-G reaches H-201A/B/C/D through enclosed SC-164 distribution. Each branch has separate metering and isolation in the proposed arrangement. Acid streams and oxidizer/carbon handling remain segregated.';
 if(s.id==='pregdry')s.routes.push('H-201C manufactured Pre-G inlet','H-201D manufactured Pre-G inlet');
 if(s.id==='tff'){s.tags='T-402 / P-402 / TFF-401 · 8 VSEP units';s.description='Eight independent VSEP units follow the supplier package envelope. P-402 circulates GO suspension; retentate returns to T-402 and permeate goes to T-403. Branch isolation, wash makeup, product discharge, CIP and closed drains have separate configurations.';s.note=TFF_BASIS;s.routes.push('TFF-401 feed manifold passage','TFF-401 retentate header','TFF-401 permeate header','TFF-401 closed module drain');}
}
for(const stage of STAGES){for(const key of ['title','tags','description','note'])stage[key]=formatAreaText(stage[key]);for(const key of ['inputs','outputs'])stage[key]=stage[key].map(row=>row.map(formatAreaText));}
export const TRAINS={feed:'FEED process',finishing:'Finishing concept'};
export function stagesForTrain(train='feed'){return STAGES.filter(s=>s.train===train);}
for(const train of Object.keys(TRAINS)){const ss=stagesForTrain(train);ss.forEach((s,i)=>s.next=ss[i+1]?.title||null);}
export function adjacentStage(id,delta,train='feed'){const s=STAGES.find(s=>s.id===id),ss=stagesForTrain(s?.train||train),i=ss.findIndex(s=>s.id===id);if(i<0)return delta>0?ss[0]?.id:null;return ss[i+delta]?.id??null;}
export function resolveWorkspace(panel){return PANEL_WORKSPACE[panel]||'process';}
export function traceMaterialFromPort(model,label,state='transfer',graph=buildConnectionGraph(model.edges)){
 const stateInfo=BATCH_STATES[state];if(!stateInfo)throw Error('Unknown batch configuration '+state);const port=model.ports.find(p=>p.label===label);if(!port)throw Error('Unknown material port '+label);const seed=model.edges.findIndex(e=>e.name===label+' neck');if(seed<0)throw Error('Material port has no physical neck '+label);
 const visited=new Set(),blocked=new Set(),queue=[seed];for(let i=0;i<queue.length;i++){const at=queue[i];if(visited.has(at))continue;const e=model.edges[at];if(e.barrierTag&&stateInfo.valves[e.barrierTag]==='closed'){blocked.add(e.barrierTag);continue;}visited.add(at);for(const next of graph[at])if(!visited.has(next))queue.push(next);}
 const partIds=new Set([...visited].map(i=>model.edges[i].part));for(const r of model.routes)if(r.edgeIndices.length&&r.edgeIndices.every(i=>visited.has(i)))for(const id of r.partIds)partIds.add(id);for(const valve of model.valves)if(valve.tag&&[...visited].some(i=>model.edges[i].barrierTag===valve.tag))for(const id of valve.partIds||[])partIds.add(id);
 return {edges:[...visited].map(i=>model.edges[i]),edgeIndices:visited,partIds,blocked:[...blocked],state};
}
export function traceReachesPort(trace,model,label){const port=model.ports.find(p=>p.label===label);return !!port&&trace.edges.some(e=>[e.a,e.b].some(p=>p.every((v,i)=>Math.abs(v-port.point[i])<1e-6)));}
