import {processKit} from './process-kit.js';
import {structuralKit} from './structural-kit.js';
import {REACTOR_AIR_ROUTES} from './reactor-air-routes.js';
import {cutVerticalBore} from './reactor-service.js';

export const REACTOR_AIR_BASIS={revision:'R201-air-65',status:'Connected concept; operating qualification HOLD',
 arrangement:'Four anchored local air panels supply eight tagged valve packages each. Each package has a mounted actuator, local 5/2 solenoid, separate A/B working connections, exhaust silencers and a sealed electrical interface.',
 selection:'Two working ports and a 5/2 distributor reserve a proposed double-acting arrangement. Vendor selection may require spring-return actuation and a different distributor. No safe failure position is assigned by this model.',
 holds:['P&ID valve operating method and process-specific safe action on loss of air, power or control signal','Vendor torque / thrust at minimum delivered pressure, stroke time, air consumption and simultaneous demand','Air quality, materials, enclosure protection and hazardous-area suitability','Tubing size, pressure loss, clamp pitch, valve/nozzle loads and supporting structure strength','Electrical I/O, feedback proof, lockout, residual pressure and stored mechanical energy','Qualified head-service disconnects and elevated maintenance access'],
 sources:[['WorkSafeBC energy isolation and verification','https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-10-de-energization-and-lockout'],['Emerson integrated actuator package','https://videos.emerson.com/detail/video/6245118412001/actuator-control']]};
export const REACTOR_AIR_CASES=[['normal','Air available'],['airLoss','Instrument air lost'],['powerLoss','Solenoid power lost'],['signalLoss','Control signal lost'],['lineLeak','Selected branch leak'],['solenoidFault','Selected solenoid stuck'],['isolation','Local panel isolated / vented'],['restoration','Supply restored — restart inhibited']];
export function reactorAirState(key='normal',faultTag=null){
 if(!REACTOR_AIR_CASES.some(([k])=>k===key))throw Error('Unknown reactor air state');
 return{key,faultTag,supplyAvailable:!['airLoss','isolation'].includes(key),panelIsolationOpen:key!=='isolation',ventOpen:key==='isolation',
 motionCredited:false,position:'Unverified — no safe valve position credited',
 reason:{normal:'Air paths exist. Pressure, torque/thrust, command and position feedback must be proved before operation.',airLoss:'Actuator chamber pressure and valve position cannot be inferred from supply loss. No spring action or fail-in-place guarantee is assumed.',powerLoss:'Dry air may remain available. Solenoid de-energized routing and final valve position require vendor and process approval.',signalLoss:'Power and pressure can remain present. Loss-of-command behavior requires an approved cause-and-effect.',lineLeak:'Isolate the affected branch and assess common-header pressure. Delivered pressure and reserve endurance are unqualified.',solenoidFault:'A stuck distributor may prevent the commanded stroke despite available pressure. Independent position proof is required.',isolation:'Local supply is blocked and the panel header vents through a silencer. Actuator chambers can retain pressure; verify and control all stored energy.',restoration:'Restored pressure is not an automatic restart permission. Require deliberate reset and verified process readiness.'}[key]};
}
export function applyReactorAirState(model,owner,state){
 const byId=new Map(model.parts.map(p=>[p.id,p]));
 for(const v of model.valves.filter(v=>v.reactor===owner&&v.pneumaticIsolation)){
  v.inspectionOpen=v.tag.startsWith('XV-AP201-')?state.panelIsolationOpen:v.tag.startsWith('DV-AP201-')?state.ventOpen:!(state.key==='lineLeak'&&v.tag==='XV-AIR-'+state.faultTag);
  const p=byId.get(v.discId);if(p)p.quaternion.copy(v.inspectionOpen?p.openQuaternion:p.closedQuaternion);
 }
 model.reactorAir.inspectionState={...state,owner};return model.reactorAir.inspectionState;
}

export function buildReactorAir(h,compressedAir){
 const k=processKit(h,.006),s=structuralKit(h),{T,parts,edges,routes,ports,terminals,valves,EQUIPMENT,setContext,b,c,band,tube,terminal,bolt,add}=h,V=p=>new T.Vector3(...p);
 const first=parts.length,panels=[],consumers=[],interfaces=[],mounts=[],accessZones=[];
 const byId=new Map(parts.map(p=>[p.id,p]));
 const plus=(p,d,n)=>V(p).addScaledVector(V(d),n).toArray();
 function mark(start,owner,assembly){for(const p of parts.slice(start)){p.reactor=owner;p.exploreRole='equipment';p.componentAssembly=assembly;p.pneumaticPackage=true;p.designBasis=REACTOR_AIR_BASIS.status;}}
 function path(points,tag,service='Instrument air',meta={}){const start=parts.length,r=k.line(points,.006,tag,service,null,null,{bendRadius:.035,bendFactor:.25});Object.assign(r,{pneumatic:true,areaId:'A-200',...meta});for(const e of edges.slice(-r.edgeIndices.length))e.pneumatic=true;for(const p of parts.slice(start)){p.exploreRole='equipment';p.pneumaticPackage=true;p.componentAssembly=meta.assembly||tag;}return r;}
 function borePlate(name,size,at,holes=[]){const[w,hh,d]=size,sh=new T.Shape();sh.moveTo(-w/2,-hh/2);sh.lineTo(w/2,-hh/2);sh.lineTo(w/2,hh/2);sh.lineTo(-w/2,hh/2);sh.closePath();for(const[x,y,r]of holes){const hole=new T.Path();hole.absarc(x,y,r,0,Math.PI*2,true);sh.holes.push(hole);}const g=new T.ExtrudeGeometry(sh,{depth:d,bevelEnabled:false,curveSegments:16});g.translate(0,0,-d/2);return add(name,'head',g,at,'blue');}
 function fitting(at,axis,tag,r=.006,length=.055){const end=plus(at,axis,length),p=tube(at,end,r,tag+' bore');band(tag+' compression nut','valve',r*1.9,r*.78,.021,plus(at,axis,length*.6),'bright',axis);ports.push({id:tag,label:tag,reactor:p.reactor,point:end,axis,radius:r,role:'pneumatic'});return{at,end,partId:p.id};}
 function silencer(at,axis,tag){const end=plus(at,axis,.075),body=band(tag+' porous silencer','valve',.014,.004,.075,plus(at,axis,.0375),'bright',axis);k.passage(body,[at,end],tag+' exhaust','Pneumatic exhaust',{internalTo:tag});terminal(end,tag+' intentional pneumatic exhaust through silencer');interfaces.push({tag,point:end,disposition:'intentional pneumatic exhaust',processConnection:false});return end;}
 function block(a,z,tag,{open=true,host=null,service='Instrument air'}={}){const mid=V(a).add(V(z)).multiplyScalar(.5).toArray(),axis=V(z).sub(V(a)).normalize().toArray(),body=band(tag+' isolation body','valve',.027,.0047,V(a).distanceTo(V(z)),mid,'bright',axis);k.passage(body,[a,z],tag+' isolated passage',service,{internalTo:tag,barrierTag:tag});const lever=b(tag+' lockable lever','valve',[.08,.025,.025],plus(mid,[0,1,0],.038),'blue'),disc=c(tag+' air isolation disc','internal',.0046,.002,mid,'dark',axis);disc.closedQuaternion=disc.quaternion.clone();disc.openQuaternion=new T.Quaternion().setFromAxisAngle(V(Math.abs(axis[1])>.9?[1,0,0]:[0,1,0]),Math.PI/2).multiply(disc.closedQuaternion);disc.quaternion.copy(open?disc.openQuaternion:disc.closedQuaternion);const valve={tag,label:tag+' local isolation',reactor:body.reactor,type:'pneumatic-isolation',a,b:z,normalState:open?'open':'closed',partIds:[body.id,lever.id,disc.id],discId:disc.id,pneumaticIsolation:true};valves.push(valve);if(host)s.join(host,body,mid,tag+' panel bearing');return{body,tag};}

 for(const[suffix,owner]of[['A',1],['B',2],['C',54],['D',55]]){
  const e=EQUIPMENT[owner],x=e.x,z=e.z||0,tag='AP-201'+suffix,px=x+2.00,pz=z-2.1,start=parts.length;setContext(owner,tag+' supported local air panel');
  const post=s.column(px,pz+.17,1.88,tag,.08),back=b(tag+' mounting backplate','frame',[.78,.84,.04],[px,1.45,pz+.12]);s.join(post.post,back,[px,1.45,pz+.135],tag+' post / backplate');s.load(back,tag+' panel');
  const front=borePlate(tag+' removable cover',[.78,.84,.022],[px,1.45,pz-.13]);front.cut=true;s.join(back,front,[px-.37,1.04,pz-.13],tag+' cover / enclosure');
  // Side walls bridge the backplate to the removable cover; all are mounted.
  const walls=[];for(const dx of[-.38,.38]){const p=b(tag+' enclosure side','head',[.02,.84,.24],[px+dx,1.45,pz]);p.cut=true;walls.push(p);s.join(back,p,[px+dx,1.45,pz+.10],tag+' side / back');s.join(p,front,[px+dx,1.45,pz-.12],tag+' cover fixing');}
  // Drop the obsolete direct back/cover contact: real sidewalls carry the cover.
  h.structure.contacts.splice(h.structure.contacts.findIndex(j=>j.label===tag+' cover / enclosure'),1);
  const bottom=b(tag+' enclosure floor','head',[.78,.022,.24],[px,1.04,pz]);s.join(back,bottom,[px,1.04,pz+.10],tag+' floor joint');
  for(const dx of[-.34,.34])for(const yy of[1.09,1.81])bolt([px+dx,yy,pz-.14],[0,0,1],.3,tag+' cover screw');
  const header=b(tag+' distribution manifold','valve',[.60,.07,.06],[px,1.67,pz-.03]);s.join(back,header,[px,1.67,pz+.10],tag+' manifold support');
  // A physical standoff carries the manifold from its back face to the backplate.
  h.structure.contacts.splice(h.structure.contacts.findIndex(j=>j.label===tag+' manifold support'),1);
  const standoff=b(tag+' manifold standoff','frame',[.32,.04,.11],[px,1.67,pz+.055]);s.join(back,standoff,[px,1.67,pz+.10],tag+' standoff / back');s.join(standoff,header,[px,1.67,pz],tag+' manifold / standoff');s.load(header,tag+' manifold');
  const inlet=[px-.48,1.45,pz-.03],isolOut=[px-.48,1.57,pz-.03],iso=block(inlet,isolOut,'XV-AP201-'+suffix);
  const reg=b(tag+' filter regulator body','valve',[.09,.24,.08],[px-.48,1.69,pz-.03],'bright');c(tag+' replaceable filter bowl','valve',.031,.11,[px-.48,1.60,pz-.03]);b(tag+' regulator adjustment','valve',[.06,.025,.06],[px-.48,1.825,pz-.03],'dark');const ri=isolOut,ro=[px-.435,1.69,pz-.03];k.passage(reg,[ri,[px-.48,1.69,pz-.03],ro],tag+' regulated supply','Instrument air',{internalTo:tag+' regulator'});
  const arm=b(tag+' regulator bracket','frame',[.14,.035,.15],[px-.43,1.65,pz+.045]);s.join(back,arm,[px-.38,1.65,pz+.10],tag+' regulator bracket / panel');s.join(arm,reg,[px-.48,1.65,pz-.005],tag+' regulator mounting');s.load(reg,tag+' regulator');s.join(reg,iso.body,isolOut,tag+' inlet isolation mounting');s.load(iso.body,tag+' inlet isolation');
  const input=[px-.30,1.67,pz-.03];path([ro,[px-.34,1.69,pz-.03],[px-.34,1.67,pz-.03],input],tag+' regulated manifold inlet');
  const gauge=c(tag+' pressure indicator','valve',.045,.035,[px-.48,1.69,pz-.09],'bright',[0,0,1]);c(tag+' pressure dial','valve',.039,.003,[px-.48,1.69,pz-.109],'dial',[0,0,1]);terminal([px-.48,1.69,pz-.07],tag+' sealed pressure indication');
  const supply=[x+1.6,2.4,z-1.9];path([supply,[x+1.6,2.19,z-1.9],[px-.55,2.19,z-1.9],[px-.55,1.45,z-1.9],[px-.55,1.45,pz-.03],inlet],tag+' supply to reachable isolation');
  const ventIn=[px+.30,1.67,pz-.03],ventOut=[px+.43,1.67,pz-.03];k.passage(header,[input,ventIn],tag+' common manifold','Instrument air',{internalTo:tag});block(ventIn,ventOut,'DV-AP201-'+suffix,{open:false});silencer(ventOut,[1,0,0],tag+' maintenance bleed');
  const list=valves.filter(v=>v.reactor===owner&&v.type==='bulk-isolation'&&v.partIds.some(id=>/pneumatic actuator$/.test(byId.get(id)?.name||'')));
  const outlets=[];for(let i=0;i<list.length;i++){const xx=px-.245+i*.07,at=[xx,1.705,pz-.03],up=[xx,1.82,pz-.03];k.passage(header,[input,[xx,1.67,pz-.03],at],tag+' outlet '+(i+1),'Instrument air',{internalTo:tag});const bv=block(at,up,'XV-AIR-'+list[i].tag);outlets.push(fitting(up,[0,1,0],tag+' outlet '+(i+1)).end);}
  const roof=borePlate(tag+' roof with eight gland bores',[.78,.24,.022],[px,1.87,pz],list.map((_,i)=>[-.245+i*.07,-.03,.006]));roof.quaternion.setFromAxisAngle(V([1,0,0]),Math.PI/2);s.join(back,roof,[px,1.87,pz+.11],tag+' roof / back');for(let i=0;i<list.length;i++)band(tag+' outlet gland seal '+(i+1),'valve',.013,.006,.024,[px-.245+i*.07,1.87,pz-.03],'gasket');
  c(tag+' sealed unused rear manifold plug','valve',.012,.014,[px+.20,1.67,pz+.005],'dark',[0,0,1]);
  const bay={id:'SERVICE-'+tag,kind:'service',areaIds:['A-200'],min:[px-.55,0,pz-1.0],max:[px+.55,2.0,pz-.20],note:'Local isolation, pressure verification and removable panel cover. Reach and task clearance are conceptual.'};accessZones.push(bay);
  mark(start,owner,tag);const panel={tag,owner,suffix,partIds:parts.slice(start).map(p=>p.id),backplateId:back.id,foundationId:post.foot.id,headerId:header.id,inlet,supply,isolator:'XV-AP201-'+suffix,vent:'DV-AP201-'+suffix,operatorHeightM:1.45,outlets,pressureSetpointBar:null};panels.push(panel);
  for(let index=0;index<list.length;index++){
   const v=list[index],act=byId.get(v.partIds.find(id=>/pneumatic actuator$/.test(byId.get(id)?.name||''))),oldIds=[...v.partIds],startValve=parts.length;setContext(owner,v.tag+' pneumatic actuator service');
   const isBottom=v.tag.startsWith('XV-BOT201'),body=byId.get(v.partIds.find(id=>/ · body$/.test(byId.get(id)?.name||'')))||byId.get(v.partIds.find(id=>byId.get(id)?.name==='Flush-bottom chamber bonnet'));
   const a=act.position.toArray(),bb=act.geometry.boundingBox||(act.geometry.computeBoundingBox(),act.geometry.boundingBox),half=bb.getSize(new T.Vector3()).multiply(act.scale).multiplyScalar(.5);
   // Keep the central poppet actuator and lantern. Relocate generic boxes off
   // valve bodies and connect a real yoke and stem coupling along their axis.
   let axis=isBottom?[0,-1,0]:act.position.clone().sub(body.position).normalize().toArray();
   if(!isBottom){const spindle=byId.get(v.partIds.find(id=>/ · spindle$/.test(byId.get(id)?.name||''))),switchPart=byId.get(v.partIds.find(id=>/ · position switch$/.test(byId.get(id)?.name||''))),rad=body.conduitRadius||.055,extent=Math.abs(axis[0])*half.x+Math.abs(axis[2])*half.z,newCenter=plus(body.position.toArray(),axis,rad+.08+extent),delta=V(newCenter).sub(act.position);act.position.add(delta);act.center.add(delta);if(switchPart){switchPart.position.add(delta);switchPart.center.add(delta);}if(spindle){spindle.scale.y=rad+.08;spindle.position.copy(body.position).addScaledVector(V(axis),(rad+.08)/2);spindle.center.copy(spindle.position);}a.splice(0,3,...newCenter);
    const near=plus(a,axis,-extent),base=plus(body.position.toArray(),axis,rad-.008),mount=band(v.tag+' actuator mounting yoke','frame',.044,.021,V(near).distanceTo(V(base)),V(near).add(V(base)).multiplyScalar(.5).toArray(),'bright',axis);s.join(body,mount,base,v.tag+' yoke / valve');s.join(mount,act,near,v.tag+' actuator / yoke');mounts.push({tag:v.tag,actuatorId:act.id,bodyId:body.id,joinPartId:mount.id,axis});
   }else{const lantern=byId.get(v.partIds.find(id=>byId.get(id)?.name==='Flush-bottom actuator lantern'));s.join(act,lantern,[a[0],a[1]+half.y,a[2]],v.tag+' actuator / lantern');const capY=body.position.y-.0075,adapter=band(v.tag+' lantern bonnet adapter','frame',.09,.018,.055,[a[0],capY-.0275,a[2]],'bright');s.join(lantern,adapter,[a[0],capY-.055,a[2]],v.tag+' lantern / adapter');s.join(adapter,body,[a[0],capY,a[2]],v.tag+' adapter / bonnet');mounts.push({tag:v.tag,actuatorId:act.id,bodyId:body.id,joinPartId:lantern.id,axis});}
   const cy=a[1],faceZ=a[2]+half.z,workA=[a[0]-.032,cy-.025,faceZ],workB=[a[0]+.032,cy+.025,faceZ];
   // Cut only the front surface, with blind working bores ending inside the
   // actuator housing. The external mounting geometry remains unchanged.
   for(const at of[workA,workB])cutVerticalBore(T,act,at[0],at[1],.0047,'z',faceZ-.055);
   for(const at of[workA,workB])band(v.tag+' blind working bore','internal',.008,.0047,.035,plus(at,[0,0,-1],.0175),'bright',[0,0,1]);
   act.cut=true;
   const chamberA=plus(workA,[0,0,-1],.022),chamberB=plus(workB,[0,0,-1],.022),wa=fitting(workA,[0,0,1],v.tag+' port A'),wb=fitting(workB,[0,0,1],v.tag+' port B');k.passage(act,[workA,chamberA],v.tag+' chamber A','Instrument air',{internalTo:v.tag+' chamber A'});k.passage(act,[workB,chamberB],v.tag+' chamber B','Instrument air',{internalTo:v.tag+' chamber B'});terminal(chamberA,v.tag+' sealed working chamber A');terminal(chamberB,v.tag+' sealed working chamber B');
   const sol=[a[0],cy,faceZ+.19],solbody=b(v.tag+' 5/2 solenoid manifold','valve',[.11,.11,.07],sol,'bright'),mount=b(v.tag+' solenoid standoff','frame',[.04,.03,.17],[a[0],cy,faceZ+.077]);s.join(act,mount,[a[0],cy,faceZ-.003],v.tag+' solenoid bracket / actuator');s.join(mount,solbody,[sol[0],sol[1],sol[2]-.035],v.tag+' solenoid mount');
   const sa=[sol[0]-.032,sol[1]-.025,sol[2]-.035],sb=[sol[0]+.032,sol[1]+.025,sol[2]-.035],feed=[sol[0]+.055,sol[1],sol[2]],inPort=fitting(feed,[1,0,0],v.tag+' solenoid P').end;
   path([sa,wa.end],v.tag+' working tube A','Instrument air',{consumer:v.tag});path([sb,wb.end],v.tag+' working tube B','Instrument air',{consumer:v.tag});
   k.passage(solbody,[feed,sa],v.tag+' solenoid P to A','Instrument air',{internalTo:v.tag+' solenoid',barrierTag:'SOL-'+v.tag+'-A'});k.passage(solbody,[feed,sb],v.tag+' solenoid P to B','Instrument air',{internalTo:v.tag+' solenoid',barrierTag:'SOL-'+v.tag+'-B'});
   const exa=[sol[0]-.025,sol[1]-.055,sol[2]],exb=[sol[0]+.025,sol[1]-.055,sol[2]];for(const[work,out,letter]of[[sa,exa,'A'],[sb,exb,'B']]){k.passage(solbody,[work,out],v.tag+' solenoid '+letter+' exhaust','Pneumatic exhaust',{internalTo:v.tag+' solenoid',barrierTag:'EXH-'+v.tag+'-'+letter});silencer(out,[0,-1,0],v.tag+' exhaust '+letter);}
   const coil=b(v.tag+' solenoid coil','valve',[.055,.07,.055],[sol[0]-.079,sol[1],sol[2]],'blue'),elec=[sol[0]-.11,sol[1],sol[2]];band(v.tag+' sealed electrical connector','valve',.013,.006,.018,elec,'dark',[1,0,0]);terminal(elec,v.tag+' sealed control connector; I/O qualification HOLD');interfaces.push({tag:'IO-'+v.tag,point:elec,disposition:'sealed electrical interface',status:'I/O wiring and feedback qualification HOLD'});
   const fallback=[outlets[index],[outlets[index][0],7.2,z-2.6],[x+2.3,7.2,z-2.6],[x+2.3,7.2,inPort[2]],[x+2.3,inPort[1],inPort[2]],inPort],points=REACTOR_AIR_ROUTES[v.tag]||fallback;
   const r=path(points,v.tag+' tagged actuator supply','Instrument air',{consumer:v.tag,assembly:tag+' tubing',from:tag,to:v.tag});
   mark(startValve,owner,'pneumatic-'+v.tag);v.partIds.push(...parts.slice(startValve).map(p=>p.id));for(const id of oldIds){const p=byId.get(id);if(p)p.pneumaticConsumer=v.tag;}
   const row={tag:v.tag,reactor:e.tag,owner,panel:tag,branchIsolation:'XV-AIR-'+v.tag,actuatorId:act.id,bodyId:body.id,solenoidId:solbody.id,source:outlets[index],destination:inPort,workingPorts:{A:wa.end,B:wb.end},routeId:r.id,valvePartIds:oldIds,fieldPartIds:parts.slice(startValve).filter(p=>!r.partIds.includes(p.id)).map(p=>p.id),partIds:parts.slice(startValve).map(p=>p.id),geometry:'Two-port actuator with local 5/2 distributor — proposed',connectionStatus:'Connected in model',pressureBar:null,airDemandNm3H:null,failAction:null,qualification:'HOLD — vendor and process approval',headService:cy>4.93&&Math.abs(a[0]-x)<1.3};consumers.push(row);v.pneumatic=row;
  }
 }
 // Remove only the obsolete endpoint declarations now replaced by actual tubing.
 for(let i=terminals.length-1;i>=0;i--)if(/^R-201[A-D] internal actuator tubing boundary$/.test(terminals[i].label))terminals.splice(i,1);
 for(const i of compressedAir.interfaces.filter(i=>/^BL-IA201-/.test(i.tag)))i.reason='Connected to supported reactor air panel and eight actuator packages; operating qualification HOLD';
 for(const c of compressedAir.consumers.filter(c=>/^BL-IA201-/.test(c.tag)))c.status='Panel and eight actuator packages connected; duty and fail actions HOLD';
 const known=new Set(consumers.map(c=>c.actuatorId)),audit=parts.filter(p=>/pneumatic actuator$/.test(p.name)).map(p=>({partId:p.id,equipment:EQUIPMENT[p.reactor]?.tag,owner:p.reactor,name:p.name,status:known.has(p.id)?'R-201 working ports connected':'HOLD — individual air supply / mounting not qualified',consumer:consumers.find(c=>c.actuatorId===p.id)?.tag||null}));
 for(const a of audit)if(!known.has(a.partId)){const p=byId.get(a.partId);p.designBasis='Pneumatic actuator representation; individual air supply, mounting and fail action require completion.';}
 const valveSchedule=valves.filter(v=>[1,2,54,55].includes(v.reactor)).map(v=>({tag:v.tag||v.label,reactor:EQUIPMENT[v.reactor].tag,modeledType:v.type,disposition:v.pneumatic?'Pneumatic package connected; vendor selection HOLD':v.pneumaticIsolation?'Manual air-service isolation':/^(TCV|FCV|PCV)-/.test(v.tag||'')&&['lever','wheel'].includes(v.type)?'HOLD — control-valve tag has manual geometry; actuator type and loop duty require reconciliation':['check','regulator'].includes(v.type)?'Passive / self-operated representation; duty review required':'Manual representation; operating method requires P&ID confirmation'}));
 return{basis:REACTOR_AIR_BASIS,panels,consumers,interfaces,mounts,accessZones,audit,valveSchedule,partIds:parts.slice(first).map(p=>p.id),inspectionState:reactorAirState(),limits:'Geometry and connectivity are separate from approved duty, safe failure action, structural capacity and commissioning.'};
}
