import {REACTOR_AIR_CASES,REACTOR_AIR_BASIS,reactorAirState} from './reactor-air.js';
export function mountReactorAirReview(model){
 if(model.scope==='future'||!model.reactorAir)return;
 const data=model.reactorAir,el=(tag,text)=>{const e=document.createElement(tag);if(text)e.textContent=text;return e;},card=el('details');card.className='method-note';card.id='reactor-air-review';card.append(el('summary','R-201 · Local air panels and valve actuators'));
 card.append(el('p',REACTOR_AIR_BASIS.arrangement),el('p','Select a reactor to inspect its mounted panel, tubing and valve packages. Pressure, operating duty and safe failure actions remain unqualified.'));
 const choose=(label,rows,id)=>{const lab=el('label',label),sel=el('select');lab.htmlFor=sel.id=id;for(const[value,text]of rows){const o=el('option',text);o.value=value;sel.append(o);}card.append(lab,sel);return sel;};
 const branch=choose('Reactor',data.panels.map(p=>[p.owner,'R-201'+p.suffix]),'reactor-air-owner'),scenario=choose('Air / control condition',REACTOR_AIR_CASES,'reactor-air-condition'),valve=choose('Valve package',[],'reactor-air-valve');
 const result=el('p');result.setAttribute('role','status');const tableHost=el('div');tableHost.className='air-table-scroll';card.append(result,tableHost);
 const table=(host,heads,rows)=>{const t=el('table');t.className='a3000-table';const head=el('thead'),tr=el('tr');heads.forEach(h=>tr.append(el('th',h)));head.append(tr);t.append(head);const body=el('tbody');for(const row of rows){const r=el('tr');row.forEach(v=>r.append(el('td',String(v))));body.append(r);}t.append(body);host.append(t);};
 function updateOptions(){valve.replaceChildren();for(const c of data.consumers.filter(c=>c.owner===+branch.value)){const o=el('option',c.tag);o.value=c.tag;valve.append(o);}update();}
 function update(){const state=reactorAirState(scenario.value,valve.value);data.inspectionState=state;result.textContent=state.reason+' '+state.position;tableHost.replaceChildren();table(tableHost,['Valve','Air / working ports','Failure action'],data.consumers.filter(c=>c.owner===+branch.value).map(c=>[c.tag,c.connectionStatus+' · P, A, B; two silenced exhausts',c.failAction||'HOLD — unassigned']));document.dispatchEvent(new CustomEvent('reactor-air-state',{detail:{owner:+branch.value,state}}));}
 branch.onchange=updateOptions;scenario.onchange=valve.onchange=update;updateOptions();
 const inspect=el('button','Inspect reactor air assembly');inspect.type='button';inspect.onclick=()=>document.dispatchEvent(new CustomEvent('inspect-reactor-air',{detail:{owner:+branch.value}}));card.append(inspect);
 const focus=el('button','Fit selected valve package');focus.type='button';focus.onclick=()=>document.dispatchEvent(new CustomEvent('inspect-reactor-air',{detail:{owner:+branch.value,tag:valve.value}}));card.append(focus);
 const notes=el('details');notes.append(el('summary','Selection and maintenance basis'),el('p',REACTOR_AIR_BASIS.selection),el('p','Local isolation and a silenced bleed are modeled. A depressurized header does not prove that actuator chambers are depressurized or that the process is isolated. Solenoid power and feedback connectors are sealed interfaces; field wiring and I/O approval remain open. Head-service tubing must be disconnected and reinstated under the approved removal procedure.'));
 for(const hold of REACTOR_AIR_BASIS.holds)notes.append(el('p',hold));for(const row of data.valveSchedule.filter(v=>v.disposition.startsWith('HOLD')))notes.append(el('p',row.reactor+' · '+row.tag+' — '+row.disposition));card.append(notes);
 const audit=el('details');audit.append(el('summary','Other areas · pneumatic completion survey'));const counts=new Map();for(const row of data.audit){const area=model.equipment[row.owner]?.areaId||'Unassigned',r=counts.get(area)||{total:0,connected:0};r.total++;if(row.consumer)r.connected++;counts.set(area,r);}const wrap=el('div');wrap.className='air-table-scroll';table(wrap,['Area','Actuator representations','Working ports completed','Review outstanding'],[...counts].map(([area,r])=>[area,r.total,r.connected,r.total-r.connected]));audit.append(wrap,el('p','Outstanding means the individual air path and mounting have not been qualified by this audit. It does not establish that the physical plant has a missing connection. Manual, electric and passive devices are excluded from pneumatic connection claims.'));card.append(audit);
 const dl=el('button','Download actuator and connection schedule');dl.type='button';dl.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=el('a');a.href=url;a.download='R201-air-and-plant-actuator-audit.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};card.append(dl);
 for(const[title,url]of REACTOR_AIR_BASIS.sources){const p=el('p'),a=el('a',title);a.href=url;a.target='_blank';a.rel='noopener';p.append(a);card.append(p);}document.getElementById('process-overview').append(card);
}
