// Proposed logistics reservations, metres, Y up. Vehicle dimensions are editable
// screening assumptions, never a selected truck or a jurisdictional aisle rule.
import {PLANT_DESIGN_BASIS} from './plant-design-basis.js';
export const TRANSPORT_PROFILE={width:1.6,front:2.2,rear:2.5,height:3.2,margin:.5,headMargin:.5,turnRadius:3.5};
export const TRANSPORT_BASIS={revision:'bc-corridors-85',jurisdiction:PLANT_DESIGN_BASIS.jurisdiction,designBasis:PLANT_DESIGN_BASIS,status:'Proposed — vehicle and load unqualified',reference:'Front axle centre; front includes forks and load, rear includes counterweight',direction:'One-way preview: approach, tangent right turn, continue and stop. Return manoeuvres and handling operations require separate planning.',qualification:'Geometry screening only. Confirm truck/load dimensions, manufacturer manoeuvring data, visibility, pedestrian controls, slab/cover axle loads, impact protection and structural capacity before use.',sources:[['CCOHS · truck control and clearances','https://www.ccohs.ca/oshanswers/safety_haz/forklift/control.html'],...PLANT_DESIGN_BASIS.sources]};
export const TRANSPORT_ROUTES=[
 {id:'perimeter',label:'Plant perimeter logistics circuit',areas:['all'],loop:true,points:[[125,23],[125,55],[-49,55],[-49,-51],[76,-51],[76,-40],[125,-40],[125,-30],[142,-30],[142,1.5],[125,1.5],[125,23]],note:'Proposed receiving/dispatch circulation outside process bays and remote retention tanks, routed around the A-5400 thermal-oil pad (V317); the south leg steps in to z -40 east of the retention bunds (x 76) and the circuit starts at the A-800 east frontage (V320). Requires site-boundary and new slab qualification; it is not an existing approved roadway.'},
 {id:'west-delivery',label:'A-100 / A-140 / A-160 delivery frontage',areas:['A-100','A-140','A-160','A-3000','A-4000'],points:[[-49,3],[-49,-6.8],[-17,-6.8]],note:'Frontage staging only. Individual unloading interfaces and pedestrian crossings require an operating plan.'},
 {id:'thermal-delivery',label:'A-5000 east service approach',areas:['A-5000','A-4000'],points:[[-25,-6.8],[-17,-6.8],[-17,8],[-8,8],[-8,27.9]],note:'Connects west delivery frontage to the north logistics corridor. Controlled reversing at delivery stops; no lifting beneath utilities.'},
 {id:'argon-delivery',label:'A-6000 perimeter road → south strip → argon yard bay',areas:['A-6000'],points:[[33,55],[33,46],[58.7,46]],note:'Forklift route (V338): leaves the perimeter road at X33 (shared with the door route argon-door), turns left at X33 / Z46 with the 3.5 m planning radius, runs east along the strip between the south wall and the north walkway, crosses the pass-door link PW-174 at X40 (crossing X-SPUR) and stops at X58.7, about 3 m short of the argon yard (the front of the forks stays west of the SOURCE-6100 zone at X62). Cylinders go the last metres to the reserve bank MN-6102 on a cylinder trolley. It no longer uses the tanker gap (X52.9 to 57.8). The bulk liquid-argon tanker uses the gap and parks in the bay west of the fill coupling BL-LAR6101-FILL (X64.95); the tanker crosses the north walkway PW-003 at the gap under delivery-supervisor control (no marked crossing); its swept path, turning room and return manoeuvre are separate studies.'},
 {id:'argon-door',label:'A-6000 perimeter road → south-wall vehicle door',areas:['A-6000'],points:[[33,55],[33,38.7]],note:'Forklift route (V336): leaves the perimeter road at X33, passes the open vehicle barrier west of VB-018, crosses the south wall through the 6 m vehicle door (X30 to 36) and stops 3 m inside at Z38.7, clear of the A-100 aisle walkway PW-147 (Z33.25). Straight in and out; no turn inside. The pass door for people is separate (PW-174 at X40, X39 to 41 in the wall).'},
 {id:'wash-wastewater',label:'A-300 → A-1000 under-rack aisle',areas:['A-300','A-1000','A-5000','A-2000'],points:[[16.3,13],[16.3,2.6],[52,2.6]],note:'Approach from the open space east of A-300, turn right and continue beneath the shared services along the A-1000 frontage. Stop at X52 / Z2.6. The entrance is offset from the existing wash-service columns and low filtration piping. The complete truck/load envelope is reserved before rack placement; pipe endpoints, gravity slopes and equipment legs remain fixed. One-way access preview; loading and return movements remain unqualified.'},
 {id:'receiving-delivery',label:'Receiving → A-100 delivery frontage',areas:['A-100','A-140','A-160'],reservationIds:['perimeter','west-delivery'],points:[[-49,24],[-49,-6.8],[-17,-6.8]],note:'Proposed receiving transfer via the reserved west corridor to raw-material staging. Stops at the frontage; dock interfaces, unloading and the return manoeuvre are not modeled.'},
 {id:'product-dispatch',label:'A-800 east frontage → north dispatch',areas:['A-800'],reservationIds:['perimeter'],points:[[125,23],[125,55],[95,55]],note:'Proposed outward transfer along the reserved east and north perimeter. Starts outside A-800; equipment pickup, dispatch bays, site boundary and slab capacity still require confirmation.'},
 {id:'drum-bay-approach',hidden:true,label:'Drum staging bay SB-1 approach',areas:['A-100'],points:[[-27,-6.8],[-19,-6.8],[-19,-2.6]],note:'Reservation for the left turn from the west aisle into drum staging bay SB-1 (V321). Not shown in the route list.'},
 {id:'receiving-unload',label:'Receiving → A-100 drum staging bay SB-1 (unload and return)',areas:['A-100','A-140','A-160'],reservationIds:['perimeter','west-delivery','drum-bay-approach'],points:[[-49,24],[-49,-6.8],[-19,-6.8],[-19,-2.6]],
  unload:{bay:{id:'SB-1',x:-19,z:-1.6,size:1.2,pad:1.6},loadCentre:1,lowerBy:.1,withdraw:1.4,reverseTo:-45.5},
  note:'Electric reference truck carries one pallet of four 205 L chemical drums in through the west vehicle door, turns left from the aisle into drum staging bay SB-1, lowers and places the pallet, withdraws the forks, raises them and reverses back along the same path to the door. The chemical, its hazard class, drum mass, truck selection, delivery dock and truck, charging and the traffic plan are not selected. The bay edge is about 0.3 m from the thermal-delivery lane envelope (x -17).'}
];
export function validateTransportProfile(p){for(const k of Object.keys(TRANSPORT_PROFILE))if(!Number.isFinite(p[k])||p[k]<=0||p[k]>20)throw Error('Enter positive dimensions up to 20 m.');if(p.margin<.1||p.headMargin<.1)throw Error('Screening allowances must be at least 0.1 m.');return p;}
// Filleted front-axle path, with tangent headings and bounded pose spacing.
// A leg shared by two turns needs two radii and an end leg one (V321).
export function transportPoses(route,profile=TRANSPORT_PROFILE,step=.5){
 validateTransportProfile(profile);if(route.points.slice(1).reduce((s,p,i)=>s+Math.hypot(p[0]-route.points[i][0],p[1]-route.points[i][1]),0)/step>20000)throw Error("This vehicle and route require too many screening positions. Check dimensions or select a shorter route.");const pts=route.points,poses=[],corners=new Map(),dist=(a,b)=>Math.hypot(b[0]-a[0],b[1]-a[1]);
 for(let i=1;i<pts.length-1;i++){const a=pts[i-1],b=pts[i],c=pts[i+1],la=dist(a,b),lb=dist(b,c),u=[(b[0]-a[0])/la,(b[1]-a[1])/la],v=[(c[0]-b[0])/lb,(c[1]-b[1])/lb],cross=u[0]*v[1]-u[1]*v[0];if(Math.abs(cross)<.99)continue;const r=profile.turnRadius;if(la<(i>1?2*r:r)+.05||lb<(i<pts.length-2?2*r:r)+.05)throw Error('Turning radius does not fit this route; revise the corridor geometry.');const start=[b[0]-u[0]*r,b[1]-u[1]*r],end=[b[0]+v[0]*r,b[1]+v[1]*r],centre=[start[0]+v[0]*r,start[1]+v[1]*r];corners.set(i,{start,end,centre,r,cross});}
 const add=(x,z,yaw)=>poses.push({x,z,yaw});
 for(let i=0;i<pts.length-1;i++){const a=corners.get(i)?.end||pts[i],b=corners.get(i+1)?.start||pts[i+1],length=dist(a,b),yaw=Math.atan2(b[1]-a[1],b[0]-a[0]),n=Math.max(1,Math.ceil(length/step));for(let j=0;j<n;j++)add(a[0]+(b[0]-a[0])*j/n,a[1]+(b[1]-a[1])*j/n,yaw);const c=corners.get(i+1);if(c){const angle=Math.atan2(c.start[1]-c.centre[1],c.start[0]-c.centre[0]),n=Math.ceil(c.r*Math.PI/2/step);for(let j=0;j<n;j++){const theta=angle+c.cross*Math.PI/2*j/n;add(c.centre[0]+c.r*Math.cos(theta),c.centre[1]+c.r*Math.sin(theta),theta+c.cross*Math.PI/2);}}}
 const last=pts.at(-1),prev=pts.at(-2);add(...last,Math.atan2(last[1]-prev[1],last[0]-prev[0]));return route.unload?unloadSequence(poses,route.unload):poses;
}
// Unloading manoeuvre appended to a route (V321): lower and place the pallet, withdraw the forks, raise them, reverse back along the approach to the door.
// Fields on each pose: phase, loaded (pallet on the forks), lift (fork carriage height change, m), reverse, hold (seconds at one position).
export function unloadSequence(base,u){
 const out=base.map(p=>({...p,phase:'Carry the pallet to the bay',loaded:true,lift:0})),last=base.at(-1),drop=u.lowerBy??.1,dist=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
 const rev=[...base].reverse(),withdraw=[],back=[];let acc=0;
 for(let i=1;i<rev.length;i++){acc+=dist(rev[i],rev[i-1]);(acc<=u.withdraw?withdraw:back).push(rev[i]);}
 for(let k=1;k<=6;k++)out.push({x:last.x,z:last.z,yaw:last.yaw,phase:'Lower and place the pallet',loaded:k<6,lift:-drop*k/6,hold:1});
 for(const p of withdraw)out.push({x:p.x,z:p.z,yaw:p.yaw,phase:'Withdraw the forks',loaded:false,lift:-drop,reverse:true});
 const at=withdraw.at(-1)||last;
 for(let k=1;k<=3;k++)out.push({x:at.x,z:at.z,yaw:at.yaw,phase:'Raise the forks',loaded:false,lift:-drop*(1-k/3),hold:1});
 for(const p of back){if(p.x<u.reverseTo)break;out.push({x:p.x,z:p.z,yaw:p.yaw,phase:'Reverse out to the door',loaded:false,lift:0,reverse:true});}
 return out;
}
export function transportFootprint(pose,p=TRANSPORT_PROFILE,extra=0){const c=Math.cos(pose.yaw),s=Math.sin(pose.yaw),m=p.margin+extra;return [[-p.rear-m,-p.width/2-m],[p.front+m,-p.width/2-m],[p.front+m,p.width/2+m],[-p.rear-m,p.width/2+m]].map(([x,z])=>[pose.x+x*c-z*s,pose.z+x*s+z*c]);}
// Conservative rectangular reservations cover every continuous turn, including
// the swing between poses. Merged only along straight travel to keep placement fast.
export function transportReservations(profile=TRANSPORT_PROFILE){return TRANSPORT_ROUTES.filter(route=>!route.reservationIds).flatMap(route=>{const poses=transportPoses(route,profile,.4),zones=[];for(let i=0;i<poses.length;i++){const p=poses[i],f=transportFootprint(p,profile,.45),min=[Math.min(...f.map(v=>v[0])),.02,Math.min(...f.map(v=>v[1]))],max=[Math.max(...f.map(v=>v[0])),profile.height+profile.headMargin,Math.max(...f.map(v=>v[1]))],prior=zones.at(-1);if(prior&&Math.abs(prior.yaw-p.yaw)<1e-8){for(const k of[0,2]){prior.min[k]=Math.min(prior.min[k],min[k]);prior.max[k]=Math.max(prior.max[k],max[k]);}}else zones.push({id:'TR-'+route.id+'-'+zones.length,kind:'vehicle',areaIds:route.areas,min,max,yaw:p.yaw,note:route.note,designStatus:'proposed'});}return zones;});}
export const TRANSPORT_ZONES=transportReservations();
