import * as T from './vendor/three.module.js';
import {componentEnvelope,componentIntersectsBox} from './access-review.js';
import {ACCESS_ZONES} from './access-layout.js';
import {TRANSPORT_PROFILE,TRANSPORT_ROUTES,transportPoses,transportFootprint,TRANSPORT_BASIS,validateTransportProfile} from './transport-layout.js';
const indexCache=new WeakMap();
function index(model){if(indexCache.has(model))return indexCache.get(model);const cells=new Map(),items=[],size=5;for(const p of model.parts){if(p.system==='internal'||p.exploreRole==='annotation')continue;const allowance=p.system==='pipe'?(p.insulationThickness??.05):0,bounds=componentEnvelope(p,allowance);const item={p,bounds,allowance};items.push(item);for(let x=Math.floor(bounds.min.x/size);x<=Math.floor(bounds.max.x/size);x++)for(let z=Math.floor(bounds.min.z/size);z<=Math.floor(bounds.max.z/size);z++){const k=x+','+z;if(!cells.has(k))cells.set(k,[]);cells.get(k).push(item);}}const result={items,hits:b=>{const found=new Set();for(let x=Math.floor(b.min.x/size);x<=Math.floor(b.max.x/size);x++)for(let z=Math.floor(b.min.z/size);z<=Math.floor(b.max.z/size);z++)for(const i of cells.get(x+','+z)||[])if(i.bounds.intersectsBox(b))found.add(i);return [...found];}};indexCache.set(model,result);return result;}
export function inspectTransport(model,{routeId='all',profile=TRANSPORT_PROFILE}={}){
 validateTransportProfile(profile);indexCache.delete(model);const ix=index(model),routes=TRANSPORT_ROUTES.filter(r=>routeId==='all'||r.id===routeId);if(!routes.length)throw Error('Unknown transport route');
 const pedestrians=(model.walkways?.accessZones||ACCESS_ZONES).filter(z=>z.kind==='pedestrian').map(z=>({id:z.id,box:new T.Box3(new T.Vector3(...z.min),new T.Vector3(...z.max))}));
 const results=routes.map(route=>{const sharedPedestrianZones=new Set(),lever=Math.hypot(Math.max(profile.front,profile.rear)+profile.margin,profile.width/2+profile.margin),step=Math.min(.4,.4/(1+lever/profile.turnRadius)),poses=transportPoses(route,profile,step),hits=new Map(),blockedPoses=[];
  // Continuous-sweep allowance exceeds half the pose step plus rotational corner
  // travel. SAT uses oriented component boxes; curved mesh voids remain conservative.
  const sweep=.21,local=new T.Box3(new T.Vector3(-profile.rear-profile.margin-sweep,.02,-profile.width/2-profile.margin-sweep),new T.Vector3(profile.front+profile.margin+sweep,profile.height+profile.headMargin,profile.width/2+profile.margin+sweep));
  for(const [at,pose]of poses.entries()){const footprint=transportFootprint(pose,profile,sweep),broad=new T.Box3(new T.Vector3(Math.min(...footprint.map(p=>p[0])),.02,Math.min(...footprint.map(p=>p[1]))),new T.Vector3(Math.max(...footprint.map(p=>p[0])),profile.height+profile.headMargin,Math.max(...footprint.map(p=>p[1])))),q=new T.Quaternion().setFromAxisAngle(new T.Vector3(0,1,0),pose.yaw),origin=new T.Vector3(pose.x,0,pose.z);let blocked=false;
   for(const z of pedestrians)if(broad.intersectsBox(z.box))sharedPedestrianZones.add(z.id);
   for(const {p,bounds,allowance}of ix.hits(broad)){if(bounds.max.y<=.02)continue;const relative={...p,position:p.position.clone().sub(origin).applyQuaternion(q),quaternion:q.clone().multiply(p.quaternion)};if(!componentIntersectsBox(relative,local,allowance))continue;blocked=true;if(!hits.has(p.id))hits.set(p.id,{partId:p.id,name:p.name,equipment:model.equipment[p.reactor]?.tag||String(p.reactor),area:model.equipment[p.reactor]?.areaId||'SHARED',kind:p.pipeSupportTag?'Pipe support':p.system,firstPose:at,position:p.position.toArray(),underside:bounds.min.y});}
   if(blocked)blockedPoses.push(at);
  }
  const trafficControl={mode:sharedPedestrianZones.size?'exclusive-access-preview':'separated-preview',pedestrianZones:[...sharedPedestrianZones],qualified:false,operatingRelease:'HOLD',requirement:sharedPedestrianZones.size?'Preview assumes pedestrian access is closed and the engineer animation is stopped. Real use requires a separated pedestrian route where practicable, or an engineered closure/control arrangement under WorkSafeBC 16.6. This preview does not operate physical gates.':'Confirm the site traffic plan, crossings and actual truck/load before use.'};
  return {id:route.id,label:route.label,note:route.note,poses,blockedPoses,findings:[...hits.values()],trafficControl,status:hits.size?'Obstructions require coordination':'No modeled obstruction in screened envelope',qualified:false};
 });
 return {basis:TRANSPORT_BASIS,profile:{...profile},routes:results,qualified:false,method:'Continuous sweep bounded by adaptive poses and added allowance; oriented component envelopes. Full assembled geometry is screened regardless of display filters. No dynamic stability, braking, slab capacity or operating approval.'};
}
export function supportMetrics(model){const p=model.pipeSupportSystem,pm=new Map(model.parts.map(p=>[p.id,p])),racks=p.racks.filter(r=>r.areaId==='A-5000'),parts=[...new Set(racks.flatMap(r=>r.partIds))].map(id=>pm.get(id)).filter(Boolean),columns=parts.filter(p=>p.name.endsWith(' column'));return {all:p.summary,memberLengthM:p.optimization.memberLengthM,a5000:{racks:racks.length,columns:columns.length,localColumns:columns.filter(p=>p.position.x>=-31.3&&p.position.x<=-13&&p.position.z>=12.4&&p.position.z<=28.5).length,localBoundsM:[-31.3,12.4,-13,28.5],bearings:p.supports.filter(p=>p.areaId==='A-5000').length,placementElements:p.inventory.filter(i=>i.areaId==='A-5000'&&i.status==='placement review').length,memberLengthM:parts.filter(p=>p.system==='frame'&&!/bearing collar|baseplate/.test(p.name)).reduce((v,p)=>v+p.scale.y,0),coordinatedRacks:racks.filter(r=>r.coordinated).length},parts:model.parts.length};}
export function inspectReservedZones(model,zones){const ix=index(model);return zones.map(z=>{const box=new T.Box3(new T.Vector3(...z.min),new T.Vector3(...z.max)),findings=ix.hits(box).filter(i=>componentIntersectsBox(i.p,box,i.allowance,i.bounds)).map(i=>({partId:i.p.id,name:i.p.name,kind:i.p.pipeSupportTag?'Pipe support':i.p.system,area:model.equipment[i.p.reactor]?.areaId}));return {id:z.id,kind:z.kind,findings};});}
