import {A3000_UNIT,ventGasConfiguration,traceVentGas} from './a3000-logic.js';
import {A2000_UNIT} from './a2000-logic.js';
import {connectArgonSupply,ARGON_UNIT,argonDefinition,argonConfiguration} from './argon-distribution.js';
import {DOPING_UNIT,DOPING_CONDITIONS,dopingConfiguration} from './doping-logic.js';
import {formatAreaText} from './engineering-register.js';
import {FURNACE_UNIT,FURNACE_CONDITIONS,furnaceConfiguration} from './furnace-logic.js';
import {buildConnectionGraph} from './inspection.js';
const LOOP=['XV-501-SUC','XV-501-DIS','XV-501-RET','XV-501-CWS','XV-501-CWR'];
const A500_DRAINS=['XV-DR-P-501-SUC','XV-DR-P-501-CASE','XV-DR-P-502-SUC','XV-DR-P-502-CASE','XV-DR-US-501A','XV-DR-US-501B','XV-DR-US-501C','XV-DR-E501'];
const SPRAY_GAS=['BLD-601-HOT','BLD-601-DUST','BLD-602-VENT','DV-601-AIR','DV-601-EXH','XV-SC601-SUC','XV-SC601-REC'];
const SPRAY_DRIVES=['BL-601','FN-601','P-SC601'];
export const UNITS={ventgas:A3000_UNIT,
 reclaimed:A2000_UNIT,
 argon:ARGON_UNIT,
 furnace:FURNACE_UNIT,
 doping:DOPING_UNIT,
 spray:{title:'A600 aqueous spray drying',states:{
 receive:{label:'Receive accepted sonication batch',open:['XV-502-SUC','XV-502-DIS','XV-501-PROD','XV-601-IN'],seed:'T-501 bottom suction',requires:['endpoint','capacity','level','drive'],drives:['P-502','T-601 agitator']},
 hold:{label:'Hold buffer · dryer feed isolated',open:[],seed:'T-601 bottom suction',requires:[],drives:[]},
 circulate:{label:'Circulate buffer through P-601 recycle',open:['XV-601-SUC','XV-601-DIS','XV-601-REC'],seed:'T-601 bottom suction',requires:['level','drive','pressure'],drives:['T-601 agitator','P-601']},
 ready:{label:'Dryer readiness inspection · feed closed',open:SPRAY_GAS,seed:'BL-601 to HX-601',extra:['SC-601 sump suction'],requires:['gasflow','exhaust','collector','scrubber','design'],drives:SPRAY_DRIVES},
 dry:{label:'Dry aqueous suspension · feed enabled',open:[...SPRAY_GAS,'XV-601-SUC','XV-601-DIS','XV-601-FEED','XV-601-HEAT','RV-DR601','RV-F601'],seed:'T-601 bottom suction',extra:['BL-601 to HX-601','SC-601 sump suction','HX-601 heating supply route'],requires:['level','drive','flow','gasflow','exhaust','collector','scrubber','temperature','pressure','capacity','design'],drives:['T-601 agitator','P-601',...SPRAY_DRIVES],heater:true},
 shutdown:{label:'Controlled shutdown inspection · heat/feed off',open:[...SPRAY_GAS,'RV-DR601','RV-F601'],seed:'BL-601 to HX-601',extra:['SC-601 sump suction'],requires:['gasflow','exhaust','collector','scrubber'],drives:SPRAY_DRIVES},
 product:{label:'Release qualified powder to A700',open:['XV-602-OUT'],seed:'T-602 product outlet',requires:['endpoint','capacity','temperature','pressure'],drives:[]},
 clean:{label:'Clean buffer / feed pump · dryer isolated',open:['XV-601-CIP','XV-601-SUC','XV-601-DIS','XV-601-CIPRET'],seed:'A600 CIP supply interface',extra:['T-601 bottom suction'],requires:['capacity','pressure','level','drive'],drives:['P-601']},
 chamberwash:{label:'Offline chamber wash · powder isolated',open:['XV-DR601-CIP','XV-DR601-WASH','XV-VTDR601'],seed:'DR-601 chamber wash interface',requires:['temperature','pressure','capacity','cleaning'],drives:[]},
 filterwash:{label:'Offline collector wash · media qualified/removed',open:['XV-F601-CIP','XV-F601-WASH','XV-VTF601'],seed:'F-601 service wash interface',requires:['temperature','pressure','capacity','cleaning','media'],drives:[]},
 drain:{label:'Drain buffer / pump · drives off',open:['XV-601-SUC','XV-601-DIS','XV-601-REC','XV-DR601-SUC','XV-DR-P-601'],seed:'T-601 bottom suction',requires:['pressure','capacity'],drives:[]},
 scrubber:{label:'Scrubber makeup / controlled blowdown',open:['XV-SC601-SUC','XV-SC601-REC','XV-SC601-MAKEUP','XV-SC601-BD'],seed:'SC-601 sump suction',extra:['SC-601 makeup interface'],requires:['level','capacity','drive'],drives:['P-SC601']},
 scrubberdrain:{label:'Drain scrubber · gas system isolated',open:['XV-SC601-SUC','XV-SC601-REC','XV-DRSC601-SUC','XV-DR-P-SC601'],seed:'SC-601 sump suction',requires:['pressure','capacity'],drives:[]}
 },requires:[],note:'Aqueous GO basis. These are inspection configurations, not an executable startup or emergency-trip sequence. Drying requires verified gas flow, exhaust, powder collection, scrubber readiness, temperature and approved design limits. Feed and heat are off during the illustrated controlled shutdown.'},
 sonication:{title:'A500 conditioning / US-501 sonication',states:{
 receive:{label:'Receive accepted TFF suspension',open:['XV-OUT400','XV-501-IN'],seed:'T-402 to P-402',requires:['endpoint','capacity','drive'],drives:['P-402']},
 circulate:{label:'Circulate and cool · ultrasound off',open:LOOP,seed:'T-501 bottom suction',requires:['level','drive','cooling','temperature','pressure'],drives:['T-501 agitator','P-501']},
 sonicate:{label:'Sonicate · cooled three-cell circulation',open:LOOP,seed:'T-501 bottom suction',requires:['level','flow','drive','cooling','temperature','pressure'],drives:['T-501 agitator','P-501'],ultrasound:true},
 hold:{label:'Hold · pumps and ultrasound off',open:[],seed:'T-501 bottom suction',requires:[],drives:[]},
 sample:{label:'Closed quality sampling',open:['XV-501-SAMPLE'],seed:'T-501 closed sample pickup',requires:['pressure'],drives:[]},
 product:{label:'Release accepted suspension to A600',open:['XV-502-SUC','XV-502-DIS','XV-501-PROD','XV-601-IN'],seed:'T-501 bottom suction',requires:['endpoint','capacity','drive','level'],drives:['P-502']},
 cip:{label:'Clean tank / sonication loop · product isolated',open:['XV-501-CIP','XV-501-SUC','XV-501-DIS','XV-501-CIPRET'],seed:'A500 CIP supply interface',extra:['T-501 bottom suction'],requires:['level','drive','capacity','pressure'],drives:['P-501']},
 drain:{label:'Drain loop / suctions · drives off',open:[...A500_DRAINS,'XV-501-SUC','XV-502-SUC','XV-501-DIS','XV-501-RET'],seed:'T-501 bottom suction',extra:['A500 sloped process drain header'],requires:['pressure','capacity'],drives:[]},
 utilitydrain:{label:'Drain cooler utility · process isolated',open:['XV-DR-E501-UTIL','XV-VT-E501-UTIL'],seed:'E-501 utility drain takeoff',requires:['pressure','capacity'],drives:[]}
 },requires:[],note:'Inspect connected batch operations and blocked-start conditions. Ultrasound requires circulation, level, cooling, temperature and pressure readiness. These are proposed permissives, not a PLC trip sequence. Capacity, energy dose and acceptance limits require trials.'},
 decanter:{title:'Primary separation',states:{hold:{label:'Hold · quench verification required',open:[],seed:'P-303 to C-301 feed'},separate:{label:'Separate · concentrate + centrate',open:['XV-QOUT','XV-C301'],seed:'T-303 quenched slurry to P-303'}},requires:['quench','capacity','drive'],note:'C-301 feed requires verified quench completion, an available decanter and capacity in both discharge destinations. Separation efficiency is not assumed.'},
 wash:{title:'T-305 wash / settle / decant',states:{waste:{label:'T-304 wastewater discharge · P-306',open:['XV-P306'],seed:'T-304 to P-306',requires:['capacity','drive'],drives:['P-306']},wash:{label:'Mix and wash',open:['XV-W302'],seed:'HCl dosing to T-305'},settle:{label:'Settle · agitation stopped',open:[],seed:'T-305 decant pickup'},decant:{label:'Decant supernatant',open:['XV-DEC305','XV-P305'],seed:'T-305 decant pickup',drives:['P-305']},transfer:{label:'Transfer washed slurry',open:['XV-PROD305'],seed:'T-305 product suction',drives:['P-304']}},requires:['quench','capacity','endpoint','drive'],note:'Decant and product outlets are mutually exclusive. Settling suitability and product loss require trials; the side pickup is an adjustable decant concept.'},
 tff:{title:'A400 diafiltration',states:{hold:{label:'Isolated hold',open:[],seed:'T-402 to P-402'},circulate:{label:'Circulate · permeate closed',open:['XV-TFFIN','XV-RET402'],seed:'T-402 to P-402'},wash:{label:'Diafilter · RO makeup + permeate',open:['XV-TFFIN','XV-RET402','XV-PERM403','XV-DF402'],seed:'T-402 to P-402',extra:['A400 RO makeup to T-402']},concentrate:{label:'Concentrate · makeup closed',open:['XV-TFFIN','XV-RET402','XV-PERM403'],seed:'T-402 to P-402'},product:{label:'Transfer washed suspension to A500',open:['XV-OUT400','XV-501-IN'],seed:'T-402 to P-402'},cip:{label:'CIP · product isolated',open:['XV-CIP400','XV-CIPRET','XV-PERM403'],seed:'TFF CIP supply'},drain:{label:'Drain · closed collection',open:['XV-DR400','XV-DR402CASE','XV-TFFIN','XV-RET402','XV-PERM403','XV-TFF-VENT'],requires:['pressure','capacity'],seed:'T-402 to P-402',extra:['TFF-401 branch drain header']},vent:{label:'Vent return header · housings isolated',open:['XV-TFF-VENT'],seed:'TFF-401 high point vent'}},requires:['capacity','drive','membrane','endpoint'],note:'Inspect feed/retentate/permeate pressure, crossflow, level and wash chemistry. Product transfer requires the approved endpoint. CIP uses a separate source and return; membrane compatibility and cleaning method remain vendor inputs.'},
 preg:{title:'Pre-G batch operations',states:{premix:{label:'R-101 premix feeds',open:['XV-SA101','XV-H101'],seed:'P-101 sulfuric delivery',extra:['H101 contained drop']},synthesis:{label:'Selected R-141 feed / charge paths',open:['XV-PM141{b}','XV-CH141{b}','XV-CH142{b}'],seed:'A140 premix distribution header',extra:['CH141{b} contained drop','CH142{b} contained drop']},fix:{label:'Synthesis transfer to T-161',open:['XV-OUT141{b}','XV-IN161'],seed:'R-141{b} bottom discharge'},recycle:{label:'T-161 fixing recycle · P-162',open:['XV-P162','XV-REC161'],seed:'T-161 to P-162 suction',drives:['P-162']},holding:{label:'T-161 to T-162 holding · P-162',open:['XV-P162','XV-HOLD162','XV-IN162'],seed:'T-161 to P-162 suction',drives:['P-162']},holdingwater:{label:'T-162 dilution',open:['XV-RO162'],seed:'T-162 RO makeup neck'},fixwaste:{label:'T-161 bottom wastewater · P-163',open:['XV-WASTE161'],seed:'T-161 bottom waste pickup',requires:['capacity','drive'],drives:['P-163']},filtrate:{label:'T-163 filtrate wastewater · P-165',open:['XV-WASTE163'],seed:'T-163 to P-165',requires:['capacity','drive'],drives:['P-165']},dilute:{label:'T-161 dilution / mixing',open:['XV-RO161'],seed:'T-161 RO makeup neck'},settle:{label:'T-161 settling hold',open:[],seed:'T-161 decant neck'},decant:{label:'T-161 supernatant decant',open:['XV-DEC161'],seed:'T-161 decant neck'},press:{label:'T-162 holding to F-161 · P-164',open:['XV-PRESS162','XV-F161','XV-FIL161'],seed:'T-162 press product outlet',drives:['P-164']},presswash:{label:'F-161 cake washing',open:['XV-WASH161','XV-FIL161'],seed:'F-161 RO washing supply'},load:{label:'Press cake to dryer trays',open:['GD-F161','GD-D164-IN'],seed:'F-161 cake release'},dry:{label:'D-164 drying · doors closed',open:['XV-VAC164'],seed:'D-164 vapor to KO-164'},equalize:{label:'Cool / equalize · vacuum isolated',open:['XV-EQ164'],seed:'D-164 equalization source'},unload:{label:'Dry product to selected H-201',open:['GD-D164-OUT','XV-PGLOAD-{d}'],seed:'D-164 tray loading and unloading'}},requires:['capacity','drive','endpoint','pressure'],note:'These illustrate connections, not a reagent addition sequence. T-161 fixing and T-162 holding are sequential inventories. P-162 recycle and transfer branches are mutually exclusive. Drying requires sealed doors; unloading requires verified dryness, cooling, equalization and a ready receiving hopper.'}
};
for(const unit of Object.values(UNITS)){unit.title=formatAreaText(unit.title);unit.note=formatAreaText(unit.note);for(const state of Object.values(unit.states))state.label=formatAreaText(state.label);}
export const UNIT_CONDITIONS={scrubchem:'Scrubber chemistry control unavailable',draft:'Induced draft unavailable',mist:'Mist control differential pressure unacceptable',...FURNACE_CONDITIONS,...DOPING_CONDITIONS,ready:'Illustrated conditions satisfied',quench:'Quench completion unavailable',capacity:'Receiving capacity unavailable',drive:'Required transfer drive unavailable',membrane:'Membrane / circulation unavailable',endpoint:'Required quality endpoint unavailable',pressure:'Required pressure / depressurization condition unavailable',level:'Required inventory level unavailable',flow:'Required circulation flow unavailable',cooling:'Cooling flow unavailable',temperature:'Temperature condition outside approved range',gasflow:'Drying gas flow unavailable',exhaust:'Exhaust / draft unavailable',collector:'Powder collector unavailable / high differential pressure',scrubber:'Scrubber flow or sump condition unavailable',design:'Required equipment design HOLD not closed',cleaning:'Water-cleaning compatibility unverified',media:'Filter media not qualified / removed for wet cleaning'};
export function unitDefinition(model,unit){if(unit==='argon')return argonDefinition(model);if(unit!=='preg'||!model.preg?.alternative)return UNITS[unit];const states={...UNITS.preg.states};for(const key of ['press','presswash','load','dry','equalize','unload'])delete states[key];Object.assign(states,model.preg.alternative.states);return {...UNITS.preg,title:'A-160 '+model.preg.alternative.dryerTag+' alternative operations',states,note:'One selected design configuration. These are illustrative inspection states; design HOLD, thermal stability, capacity and endpoint requirements remain to be qualified.'};}
export function unitConfiguration(model,unit,state,condition='ready',branch='A',fixing='161',isolatedTff=[]){
 if(unit==='ventgas')return ventGasConfiguration(model,state,condition,UNIT_CONDITIONS);
 if(unit==='argon')return argonConfiguration(model,state,condition,UNIT_CONDITIONS);
 if(unit==='doping')return connectArgonSupply(model,dopingConfiguration(model,state,condition,UNIT_CONDITIONS));
 if(unit==='furnace')return connectArgonSupply(model,furnaceConfiguration(model,state,condition,UNIT_CONDITIONS));
 const def=unitDefinition(model,unit),s=def?.states[state];if(!s||!UNIT_CONDITIONS[condition]||!['A','B','C','D'].includes(branch))throw Error('Invalid unit inspection configuration');
 if(!['161','162'].includes(fixing))throw Error('Invalid selected destination');const sub=x=>{let y=x.replaceAll('{b}',branch).replaceAll('{d}',branch);return y;};const valves=Object.fromEntries(model.edges.filter(e=>e.barrierTag).map(e=>[e.barrierTag,'closed']));
 const requires=[...(s.requires??def.requires)];if(unit==='tff'&&!['product'].includes(state))requires.splice(requires.indexOf('endpoint'),1);const enabled=condition==='ready'||!requires.includes(condition);if(enabled)for(const t of s.open)valves[sub(t)]='open';
 if(unit==='tff'){
  const active=model.separations.tff.assemblies.filter(a=>!isolatedTff.includes(a.suffix));
  if(enabled)for(const a of active){const tag=t=>'XV-TFF-'+a.suffix+'-'+t;if(['circulate','wash','concentrate','cip'].includes(state)){valves[tag('IN')]='open';valves[tag('RET')]='open';}if(['wash','concentrate','cip'].includes(state))valves[tag('PERM')]='open';if(state==='drain')for(const t of ['IN','RET','PERM','DR'])valves[tag(t)]='open';}
  if(enabled&&active.length===0&&['circulate','wash','concentrate','cip'].includes(state)){for(const tag in valves)valves[tag]='closed';return {unit,state,condition,branch,isolatedTff,valves,enabled:false,reasons:['All membrane assemblies isolated'],seeds:[s.seed],illustrative:true};}
 }
 return {unit,state,condition,branch,isolatedTff,valves,enabled,reasons:enabled?[]:[UNIT_CONDITIONS[condition]],seeds:[s.seed,...s.extra||[]].map(sub),drives:enabled?(s.drives||[]):[],ultrasound:enabled&&!!s.ultrasound,heater:enabled&&!!s.heater,illustrative:true};
}
export function traceUnit(model,cfg,graph=buildConnectionGraph(model.edges)){
 if(cfg.unit==='ventgas')return traceVentGas(model,cfg,graph);
 if(!cfg.enabled&&!cfg.protectionActive)return {partIds:new Set(),edges:[],edgeIndices:new Set(),blocked:[],boundaries:[],configuration:cfg};
 const queue=[];for(const label of cfg.seeds){const r=model.routes.find(r=>r.label===label);if(!r)throw Error('Missing unit route '+label);queue.push({i:r.edgeIndices[0],from:null});}const visited=new Set(),blocked=new Set();for(let q=0;q<queue.length;q++){const {i,from}=queue[q];if(visited.has(i))continue;const e=model.edges[i];if(e.oneWay&&from!==null&&!([model.edges[from].a,model.edges[from].b].some(p=>p.every((n,j)=>Math.abs(n-e.a[j])<1e-5))))continue;if(((cfg.unit==='preg'&&['load','unload'].includes(cfg.state))||(cfg.unit==='spray'&&['chamberwash','filterwash'].includes(cfg.state)))&&e.transport==='filter medium permeation')continue;if(e.barrierTag&&cfg.valves[e.barrierTag]==='closed'){blocked.add(e.barrierTag);continue;}visited.add(i);for(const j of graph[i])if(!visited.has(j))queue.push({i:j,from:i});}
 const partIds=new Set([...visited].map(i=>model.edges[i].part));for(const r of model.routes)if(r.edgeIndices.length&&r.edgeIndices.every(i=>visited.has(i)))for(const id of r.partIds)partIds.add(id);for(const v of model.valves)if([...visited].some(i=>model.edges[i].barrierTag===v.tag))for(const id of v.partIds||[])partIds.add(id);
 const boundaries=[...model.separations.boundaries,...model.preg.boundaries,...model.sonication.boundaries,...model.sprayDrying.boundaries,...model.furnace.boundaries,...model.doping.boundaries,...model.argonDistribution?.boundaries||[],...model.reclaimedWater?.boundaries||[]].filter(b=>[...visited].some(i=>[model.edges[i].a,model.edges[i].b].some(p=>p.every((n,j)=>Math.abs(n-b.point[j])<1e-5)))).map(b=>b.tag);
 return {partIds,edges:[...visited].map(i=>model.edges[i]),edgeIndices:visited,blocked:[...blocked],boundaries,configuration:cfg};
}
