import * as T from './vendor/three.module.js';
import {TRANSPORT_ROUTES,transportPoses} from './transport-layout.js';
import {walkwayVolume} from './walkway-system.js';
import {inspectWalkways} from './walkway-review.js';
export function createWalkwayVisibility(){const state={markings:true,pedestrians:true,vehicles:false,crossings:true,labels:false,barriers:true};return {state,set(k,v){if(k in state)state[k]=!!v;},visible(p){return !p.walkProtection||state.barriers;},getState:()=>({...state})};}
// Exact rectangle union: each x slab has disjoint merged z intervals, eliminating
// overlapping paint and transverse seam lines at T junctions.
export function walkwayPaintRectangles(segments){const r=segments.map(s=>{const b=walkwayVolume(s);return[b.min[0],b.min[2],b.max[0],b.max[2]];}),xs=[...new Set(r.flatMap(a=>[a[0],a[2]]))].sort((a,b)=>a-b),result=[];for(let i=1;i<xs.length;i++){const x=(xs[i-1]+xs[i])/2,intervals=r.filter(a=>a[0]<x&&a[2]>x).map(a=>[a[1],a[3]]).sort((a,b)=>a[0]-b[0]),merged=[];for(const v of intervals){const p=merged.at(-1);if(p&&v[0]<=p[1]+1e-8)p[1]=Math.max(p[1],v[1]);else merged.push([...v]);}for(const [a,b]of merged)result.push([xs[i-1],a,xs[i],b]);}return result;}
export function mountWalkways({model,scene,host,viewport,getCamera,visibility=createWalkwayVisibility(),onChange=()=>{},onFit=()=>{},isContextVisible=()=>true}){
 const w=model.walkways,review=w.review||inspectWalkways(model),root=document.createElement('aside');root.id='walkway-panel';root.hidden=true;root.setAttribute('aria-labelledby','walkway-heading');host.append(root);
 root.innerHTML=`<div class="walkway-heading"><h3 id="walkway-heading">Walkways &amp; traffic</h3><button id="walkway-close" aria-label="Close walkway settings">×</button></div>
 <p id="walkway-status" role="status"></p>
 <fieldset><legend>Show in the model</legend><label><input id="walkways-toggle" type="checkbox" checked> Show walkways</label><label><input id="walkway-vehicles" type="checkbox"> Forklift lane direction</label><label><input id="walkway-crossings" type="checkbox" checked> Crossings and stop lines</label><label><input id="walkway-labels" type="checkbox"> Walkway labels</label><label><input id="walkway-barriers" type="checkbox" checked> Physical protection barriers</label></fieldset>
 <p class="small-note">Hidden items remain included in clearance checks.</p>
 <label for="walkway-location">Check a connection</label><select id="walkway-location"></select><div class="tool-row"><button id="walkway-locate">Locate connection</button><button id="walkway-fit">Show all walkways</button></div><p id="walkway-location-note"></p>
 <details><summary>Design basis and open items</summary><p>Proposed 1.2 m clear width and 2.3 m headroom. These are project assumptions, not statutory minimums. Assess passing, accessibility, occupancy and egress before fixing widths.</p><p>Yellow barriers are proposed geometry. Impact rating, truck/load energy, deflection and slab anchorage require qualified selection. A 0.35 m deflection allowance is reserved in the model; performance is unverified.</p><p>Use a slip-resistant, chemically suitable surface with flush, drained transitions. No elevated pipe drain is introduced to create a passage.</p><ul id="walkway-holds"></ul><p>Under-rack passages at X57.75, X59.25 and X102.25 keep 1.2 m × 2.3 m clear ground access. Isolate these passages for overhead service or lifting work.</p><p><a href="https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-16-mobile-equipment" target="_blank" rel="noopener">WorkSafeBC 16.6 · pedestrian and mobile equipment separation ↗</a></p><p><a href="https://www.worksafebc.com/en/law-policy/occupational-health-safety/searchable-ohs-regulation/ohs-regulation/part-04-general-conditions" target="_blank" rel="noopener">WorkSafeBC Part 4 · safe access, aisles and floors ↗</a></p></details>`;
 const $=id=>root.querySelector('#'+id),toggle=document.getElementById('walkways-toggle'),settings=document.getElementById('walkways-settings');
 const connected=w.destinations.filter(d=>d.walkPoint),fire=connected.filter(d=>d.kind==='fire').length;
 $('walkway-status').textContent=review.clear?`Model checks · ${connected.filter(d=>d.kind==='local-access').length}/${w.destinations.filter(d=>d.kind==='local-access').length} local approaches · ${fire}/${w.destinations.filter(d=>d.kind==='fire').length} fire points · ${w.widthM.toFixed(1)} m proposed walkway width`:`Geometry review required · ${review.segments.filter(s=>!s.clear).length} obstructed segments`;
 for(const h of w.holds){const li=document.createElement('li');li.textContent=h.label;$('walkway-holds').append(li);}
 for(const d of w.destinations){const o=document.createElement('option');o.value=d.id;o.textContent=d.label+(d.walkPoint?'':' · access gap');$('walkway-location').append(o);} $('walkway-location').value='wastewater-0';
 const groups=Object.fromEntries(['pedestrians','vehicles','crossings','selection'].map(k=>{const g=new T.Group();g.name='Walkway '+k;scene.add(g);return[k,g];}));
 const meshRects=(rects,color,y=.012)=>{const vertices=[];for(const [a,b,c,d]of rects)vertices.push(a,y,b,a,y,d,c,y,d,a,y,b,c,y,d,c,y,b);const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.Float32BufferAttribute(vertices,3));return new T.Mesh(geometry,new T.MeshBasicMaterial({color,side:T.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1}));};
 const clearSegments=w.segments.filter(s=>review.segments.find(r=>r.id===s.id)?.clear);
 groups.pedestrians.add(meshRects(walkwayPaintRectangles(clearSegments),0x207b61));
 // Mark only the outside boundary, subtracting neighbouring corridor interiors.
 const rectangles=clearSegments.map(s=>{const v=walkwayVolume(s);return[v.min[0],v.min[2],v.max[0],v.max[2]];}),boundary=[];
 for(const r of rectangles)for(const [axis,fixed,lo,hi]of[['x',r[1],r[0],r[2]],['x',r[3],r[0],r[2]],['z',r[0],r[1],r[3]],['z',r[2],r[1],r[3]]]){let intervals=[[lo,hi]];for(const q of rectangles){if(q===r)continue;const interior=axis==='x'?fixed>q[1]+1e-8&&fixed<q[3]-1e-8:fixed>q[0]+1e-8&&fixed<q[2]-1e-8;if(!interior)continue;const a=axis==='x'?q[0]:q[1],b=axis==='x'?q[2]:q[3];intervals=intervals.flatMap(([l,h])=>b<=l||a>=h?[[l,h]]:[...(l<a?[[l,a]]:[]),...(h>b?[[b,h]]:[])]);}for(const [l,h]of intervals)boundary.push(axis==='x'?[l,fixed-.025,h,fixed+.025]:[fixed-.025,l,fixed+.025,h]);}
 groups.pedestrians.add(meshRects(boundary,0xe5c44a,.014));
 for(const s of w.segments.filter(s=>!review.segments.find(r=>r.id===s.id)?.clear)){const b=walkwayVolume(s);groups.pedestrians.add(meshRects([[b.min[0],b.min[2],b.max[0],b.max[2]]],0xb84b63));}
 for(const r of TRANSPORT_ROUTES){const poses=transportPoses(r);for(let i=8;i<poses.length;i+=20){const p=poses[i],len=.65,side=.3,c=Math.cos(p.yaw),s=Math.sin(p.yaw),pts=[[-len,-side],[0,0],[-len,side]].map(([x,z])=>new T.Vector3(p.x+x*c-z*s,.016,p.z+x*s+z*c));groups.vehicles.add(new T.Line(new T.BufferGeometry().setFromPoints(pts),new T.LineBasicMaterial({color:0xdde7ed})));}}
 for(const c of w.crossings){const x=c.at[0],z=c.at[1],rects=[];for(let v=z-1.7;v<z+1.7;v+=.55)rects.push([x-.6,v,x+.6,v+.28]);rects.push([x-3.6,z-1.45,x-3.4,z+1.45]);for(const p of c.pedestrian)rects.push([p[0]-.55,p[1]-.06,p[0]+.55,p[1]+.06]);groups.crossings.add(meshRects(rects,0xf2eee3,.017));}
 const labelRoot=document.createElement('div');labelRoot.id='walkway-labels-layer';host.append(labelRoot);const labels=w.routes.map(r=>{const el=document.createElement('span');el.className='walkway-label';el.textContent=r.label.split(' · ')[0]+' · Walkway';labelRoot.append(el);return{el,point:new T.Vector3(r.points[0][0],.15,r.points[0][1])};});
 function sync(){const s=visibility.state;toggle.checked=s.markings;$('walkway-labels').disabled=!s.markings;for(const k of['vehicles','crossings','labels','barriers'])$('walkway-'+k).checked=s[k];onChange();draw();}
 function location(){const d=w.destinations.find(d=>d.id===$('walkway-location').value);$('walkway-location-note').textContent=!d?.walkPoint?'Access gap: no full-width connection is credited.':d.kind==='local-access'?'Ground approach connected. Valve reach, sampling and elevated access remain unverified.':d.finalReachUnverified?'Grade approach only. Final reach, activation space and emergency response time remain unqualified.':d.original?'Alternate viewpoint clears the low utility corridor; it is not a machine control position.':'Connected to the modeled walkway.';return d;}
 function close(){root.hidden=true;settings.setAttribute('aria-expanded','false');settings.setAttribute('aria-pressed','false');groups.selection.visible=false;settings.focus?.({preventScroll:true});}
 toggle.onchange=e=>{visibility.set('markings',e.target.checked);sync();};settings.onclick=()=>{root.hidden=!root.hidden;settings.setAttribute('aria-expanded',String(!root.hidden));settings.setAttribute('aria-pressed',String(!root.hidden));if(!root.hidden)sync();};$('walkway-close').onclick=close;
 for(const k of['vehicles','crossings','labels','barriers'])$('walkway-'+k).onchange=e=>{visibility.set(k,e.target.checked);sync();};
 $('walkway-location').onchange=location;$('walkway-locate').onclick=()=>{const d=location(),p=d.walkPoint||d.point;onFit(new T.Box3(new T.Vector3(p[0]-4,0,p[1]-4),new T.Vector3(p[0]+4,3,p[1]+4)));};
 $('walkway-fit').onclick=()=>{const box=new T.Box3();for(const s of w.segments)box.union(new T.Box3(new T.Vector3(...walkwayVolume(s).min),new T.Vector3(...walkwayVolume(s).max)));onFit(box);};
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}});
 function draw(){const s=visibility.state,context=isContextVisible();for(const k of['pedestrians','vehicles','crossings'])groups[k].visible=context&&s[k]&&(k!=='pedestrians'||s.markings);labelRoot.hidden=!context||!s.markings||!s.pedestrians||!s.labels;const camera=getCamera();for(const l of labels){const p=l.point.clone().project(camera),show=p.z>-1&&p.z<1&&Math.abs(p.x)<1&&Math.abs(p.y)<1;l.el.hidden=!show;if(show)l.el.style.transform=`translate(${(p.x+1)*viewport.clientWidth/2}px,${(1-p.y)*viewport.clientHeight/2}px)`;}}
 location();sync();return {draw,close,visibility,get shown(){return !root.hidden;},getState:()=>({...visibility.getState(),shown:!root.hidden,review,connections:connected.length,unresolved:w.holds,qualified:false})};
}
